export type Category =
  | "all"
  | "text"
  | "image"
  | "video"
  | "coding"
  | "music"
  | "other";

export interface AITool {
  id: string;
  name: string;
  description: string;
  url: string;
  category: Exclude<Category, "all">;
  tags: string[];
  free: boolean;
  popular?: boolean;
}

export const categories: { value: Category; label: string; emoji: string }[] = [
  { value: "all", label: "전체", emoji: "🌐" },
  { value: "text", label: "텍스트 / 글쓰기", emoji: "✍️" },
  { value: "image", label: "이미지 생성", emoji: "🎨" },
  { value: "video", label: "비디오", emoji: "🎬" },
  { value: "coding", label: "코딩", emoji: "💻" },
  { value: "music", label: "음악", emoji: "🎵" },
  { value: "other", label: "기타", emoji: "✨" },
];

export const aiTools: AITool[] = [
  // === TEXT ===
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: "OpenAI의 가장 강력한 대화형 AI. GPT-4o 기반으로 텍스트, 이미지, 파일 분석 등 다양한 작업을 처리합니다.",
    url: "https://chat.openai.com",
    category: "text",
    tags: ["GPT-4o", "대화형 AI", "문서 분석", "OpenAI"],
    free: true,
    popular: true,
  },
  {
    id: "claude",
    name: "Claude",
    description: "Anthropic의 AI 어시스턴트. 긴 문서 처리, 코드 작성, 분석에 뛰어나며 안전성에 중점을 둡니다.",
    url: "https://claude.ai",
    category: "text",
    tags: ["Claude 3.5", "긴 컨텍스트", "안전 AI", "Anthropic"],
    free: true,
    popular: true,
  },
  {
    id: "gemini",
    name: "Gemini",
    description: "Google의 멀티모달 AI. Google 서비스와 완벽하게 통합되며 실시간 정보 검색이 가능합니다.",
    url: "https://gemini.google.com",
    category: "text",
    tags: ["멀티모달", "Google 통합", "실시간 검색", "Google"],
    free: true,
    popular: true,
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    description: "AI 기반 검색 엔진. 실시간 웹 검색과 AI를 결합해 출처가 명확한 답변을 제공합니다.",
    url: "https://www.perplexity.ai",
    category: "text",
    tags: ["AI 검색", "실시간 정보", "출처 인용", "리서치"],
    free: true,
    popular: true,
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    description: "Notion에 내장된 AI 어시스턴트. 문서 작성, 요약, 번역 등 노트와 프로젝트 관리를 도와줍니다.",
    url: "https://www.notion.so/product/ai",
    category: "text",
    tags: ["문서 작성", "요약", "Notion 통합", "협업"],
    free: false,
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    description: "마케팅 카피, 블로그 포스트, 소셜 미디어 콘텐츠 생성에 특화된 AI 글쓰기 도구입니다.",
    url: "https://www.copy.ai",
    category: "text",
    tags: ["카피라이팅", "마케팅", "블로그", "SNS"],
    free: true,
  },
  {
    id: "jasper",
    name: "Jasper AI",
    description: "기업용 AI 콘텐츠 플랫폼. 브랜드 보이스를 학습해 일관된 마케팅 콘텐츠를 생성합니다.",
    url: "https://www.jasper.ai",
    category: "text",
    tags: ["기업용", "브랜드 마케팅", "콘텐츠 자동화"],
    free: false,
  },
  {
    id: "grammarly",
    name: "Grammarly",
    description: "AI 기반 영문 교정 및 글쓰기 어시스턴트. 문법, 스타일, 명확성을 개선합니다.",
    url: "https://www.grammarly.com",
    category: "text",
    tags: ["영문 교정", "문법 검사", "글쓰기 개선"],
    free: true,
  },

  // === IMAGE ===
  {
    id: "midjourney",
    name: "Midjourney",
    description: "가장 인기 있는 AI 이미지 생성 도구. Discord 기반으로 놀라운 아트워크와 사실적인 이미지를 만들어냅니다.",
    url: "https://www.midjourney.com",
    category: "image",
    tags: ["아트워크", "Discord", "고품질", "상업적 사용"],
    free: false,
    popular: true,
  },
  {
    id: "dalle3",
    name: "DALL·E 3",
    description: "OpenAI의 최신 이미지 생성 AI. 텍스트 설명을 정확하게 반영한 고품질 이미지를 생성합니다.",
    url: "https://openai.com/dall-e-3",
    category: "image",
    tags: ["OpenAI", "텍스트→이미지", "정확도", "ChatGPT 통합"],
    free: false,
    popular: true,
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    description: "오픈소스 이미지 생성 모델. 로컬 실행 가능하며 다양한 커스터마이징이 가능합니다.",
    url: "https://stability.ai",
    category: "image",
    tags: ["오픈소스", "로컬 실행", "커스터마이징", "무료"],
    free: true,
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    description: "Adobe의 AI 이미지 생성 도구. Photoshop, Illustrator와 통합되어 창작 워크플로우를 강화합니다.",
    url: "https://firefly.adobe.com",
    category: "image",
    tags: ["Adobe 통합", "상업 라이선스", "제너레이티브 필", "크리에이티브"],
    free: true,
    popular: true,
  },
  {
    id: "ideogram",
    name: "Ideogram",
    description: "텍스트 렌더링에 강점을 가진 AI 이미지 생성 도구. 로고, 포스터 디자인에 특히 유용합니다.",
    url: "https://ideogram.ai",
    category: "image",
    tags: ["텍스트 렌더링", "로고", "포스터", "디자인"],
    free: true,
  },
  {
    id: "leonardo-ai",
    name: "Leonardo AI",
    description: "게임 에셋, 캐릭터 디자인에 특화된 AI 이미지 생성 플랫폼. 다양한 파인튜닝 모델을 제공합니다.",
    url: "https://leonardo.ai",
    category: "image",
    tags: ["게임 에셋", "캐릭터", "파인튜닝", "크리에이티브"],
    free: true,
  },
  {
    id: "canva-ai",
    name: "Canva AI",
    description: "Canva에 통합된 AI 기능. 이미지 생성, 배경 제거, 마법 편집 등 디자인 작업을 자동화합니다.",
    url: "https://www.canva.com/ai-image-generator",
    category: "image",
    tags: ["디자인 통합", "배경 제거", "템플릿", "손쉬운 사용"],
    free: true,
  },

  // === VIDEO ===
  {
    id: "runway",
    name: "Runway",
    description: "전문적인 AI 비디오 생성 및 편집 플랫폼. Gen-2로 텍스트/이미지를 고품질 비디오로 변환합니다.",
    url: "https://runwayml.com",
    category: "video",
    tags: ["비디오 생성", "Gen-2", "영상 편집", "크리에이티브"],
    free: true,
    popular: true,
  },
  {
    id: "sora",
    name: "Sora",
    description: "OpenAI의 혁신적인 텍스트→비디오 AI. 최대 60초의 놀라운 사실적 영상을 생성합니다.",
    url: "https://sora.com",
    category: "video",
    tags: ["텍스트→비디오", "OpenAI", "고품질", "사실적"],
    free: false,
    popular: true,
  },
  {
    id: "pika",
    name: "Pika",
    description: "텍스트와 이미지로 비디오를 생성하는 AI. 쉬운 인터페이스로 빠르게 애니메이션을 만들 수 있습니다.",
    url: "https://pika.art",
    category: "video",
    tags: ["애니메이션", "이미지→비디오", "빠른 생성"],
    free: true,
  },
  {
    id: "heygen",
    name: "HeyGen",
    description: "AI 아바타로 마케팅 비디오를 생성하는 플랫폼. 100개 이상의 언어로 비디오 번역도 지원합니다.",
    url: "https://www.heygen.com",
    category: "video",
    tags: ["AI 아바타", "비디오 번역", "마케팅", "다국어"],
    free: true,
  },
  {
    id: "synthesia",
    name: "Synthesia",
    description: "AI 아바타 기반 기업용 비디오 제작 플랫폼. 텍스트만으로 전문적인 트레이닝 영상을 만듭니다.",
    url: "https://www.synthesia.io",
    category: "video",
    tags: ["기업용", "AI 아바타", "트레이닝 영상", "다국어"],
    free: false,
  },
  {
    id: "kling",
    name: "Kling AI",
    description: "중국 Kuaishou가 개발한 AI 비디오 생성 도구. 2분 길이의 고품질 비디오 생성이 가능합니다.",
    url: "https://klingai.com",
    category: "video",
    tags: ["긴 비디오", "고품질", "텍스트→비디오"],
    free: true,
  },

  // === CODING ===
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description: "GitHub과 OpenAI가 개발한 AI 코딩 어시스턴트. VS Code에서 실시간 코드 제안과 자동 완성을 제공합니다.",
    url: "https://github.com/features/copilot",
    category: "coding",
    tags: ["VS Code", "자동 완성", "GitHub 통합", "페어 프로그래밍"],
    free: false,
    popular: true,
  },
  {
    id: "cursor",
    name: "Cursor",
    description: "AI 네이티브 코드 에디터. Claude, GPT-4 기반으로 코드베이스 전체를 이해하고 편집합니다.",
    url: "https://cursor.sh",
    category: "coding",
    tags: ["AI 에디터", "코드베이스 분석", "자동 편집", "Claude"],
    free: true,
    popular: true,
  },
  {
    id: "v0",
    name: "v0 by Vercel",
    description: "텍스트 설명으로 React UI 컴포넌트를 생성하는 AI. shadcn/ui 기반의 코드를 즉시 생성합니다.",
    url: "https://v0.dev",
    category: "coding",
    tags: ["UI 생성", "React", "shadcn/ui", "Vercel"],
    free: true,
    popular: true,
  },
  {
    id: "bolt",
    name: "Bolt.new",
    description: "브라우저에서 풀스택 앱을 빠르게 프로토타이핑하는 AI 개발 도구. StackBlitz 기반으로 실행됩니다.",
    url: "https://bolt.new",
    category: "coding",
    tags: ["풀스택", "프로토타이핑", "StackBlitz", "브라우저 IDE"],
    free: true,
  },
  {
    id: "tabnine",
    name: "Tabnine",
    description: "프라이버시 중심의 AI 코드 완성 도구. 로컬 실행 옵션으로 코드를 외부 서버에 전송하지 않습니다.",
    url: "https://www.tabnine.com",
    category: "coding",
    tags: ["프라이버시", "로컬 실행", "코드 완성", "기업용"],
    free: true,
  },
  {
    id: "codeium",
    name: "Codeium",
    description: "무료 AI 코딩 어시스턴트. 70개 이상의 언어와 40개 이상의 에디터를 지원하는 빠른 자동 완성 도구.",
    url: "https://codeium.com",
    category: "coding",
    tags: ["무료", "다국어 지원", "빠른 응답", "다양한 에디터"],
    free: true,
  },
  {
    id: "replit-ai",
    name: "Replit AI",
    description: "Replit IDE에 통합된 AI. 코드 생성, 디버깅, 설명을 제공하며 클라우드에서 바로 실행됩니다.",
    url: "https://replit.com",
    category: "coding",
    tags: ["클라우드 IDE", "디버깅", "코드 실행", "교육"],
    free: true,
  },

  // === MUSIC ===
  {
    id: "suno",
    name: "Suno AI",
    description: "텍스트 프롬프트만으로 완성된 노래를 만드는 AI. 가사, 멜로디, 보컬까지 자동으로 생성합니다.",
    url: "https://suno.ai",
    category: "music",
    tags: ["노래 생성", "가사", "보컬", "다양한 장르"],
    free: true,
    popular: true,
  },
  {
    id: "udio",
    name: "Udio",
    description: "고품질 음악을 생성하는 AI 플랫폼. 다양한 장르와 스타일의 음악을 쉽게 만들 수 있습니다.",
    url: "https://www.udio.com",
    category: "music",
    tags: ["고품질 음악", "다양한 장르", "음악 생성"],
    free: true,
    popular: true,
  },
  {
    id: "mubert",
    name: "Mubert",
    description: "AI로 로열티 프리 배경음악을 생성하는 플랫폼. 영상, 팟캐스트, 게임용 음악에 최적화되어 있습니다.",
    url: "https://mubert.com",
    category: "music",
    tags: ["배경음악", "로열티 프리", "영상용", "API 제공"],
    free: true,
  },
  {
    id: "soundraw",
    name: "Soundraw",
    description: "무드, 장르, 길이를 선택해 맞춤 음악을 생성하는 AI. 영상 크리에이터에게 인기 있는 도구입니다.",
    url: "https://soundraw.io",
    category: "music",
    tags: ["맞춤 음악", "크리에이터", "무드 설정", "로열티 프리"],
    free: true,
  },
  {
    id: "aiva",
    name: "AIVA",
    description: "클래식과 영화 OST 스타일 음악 작곡에 특화된 AI. 게임, 광고, 영화 음악 제작에 활용됩니다.",
    url: "https://www.aiva.ai",
    category: "music",
    tags: ["작곡 AI", "클래식", "영화 OST", "게임 음악"],
    free: true,
  },

  // === OTHER ===
  {
    id: "eleven-labs",
    name: "ElevenLabs",
    description: "가장 자연스러운 AI 음성 합성 플랫폼. 음성 클로닝, 텍스트→음성 변환으로 콘텐츠 제작에 혁명을 일으킵니다.",
    url: "https://elevenlabs.io",
    category: "other",
    tags: ["음성 합성", "음성 클로닝", "TTS", "다국어"],
    free: true,
    popular: true,
  },
  {
    id: "descript",
    name: "Descript",
    description: "텍스트 기반 오디오/비디오 편집 AI. 스크립트를 편집하면 미디어도 자동으로 편집되는 혁신적인 도구.",
    url: "https://www.descript.com",
    category: "other",
    tags: ["오디오 편집", "비디오 편집", "팟캐스트", "자막"],
    free: true,
  },
  {
    id: "chatpdf",
    name: "ChatPDF",
    description: "PDF 문서와 대화하는 AI. 논문, 계약서, 보고서를 업로드하고 내용에 대해 질문하세요.",
    url: "https://www.chatpdf.com",
    category: "other",
    tags: ["PDF 분석", "문서 QA", "논문 요약", "리서치"],
    free: true,
  },
  {
    id: "d-id",
    name: "D-ID",
    description: "사진을 말하는 아바타로 변환하는 AI. 디지털 휴먼 기술로 교육, 마케팅 영상을 쉽게 제작합니다.",
    url: "https://www.d-id.com",
    category: "other",
    tags: ["디지털 휴먼", "아바타", "교육 영상", "마케팅"],
    free: true,
  },
  {
    id: "gamma",
    name: "Gamma",
    description: "AI로 프레젠테이션, 문서, 웹페이지를 자동 생성하는 도구. 아이디어만 입력하면 슬라이드를 만들어줍니다.",
    url: "https://gamma.app",
    category: "other",
    tags: ["프레젠테이션", "슬라이드", "문서 생성", "디자인"],
    free: true,
    popular: true,
  },
  {
    id: "otter-ai",
    name: "Otter.ai",
    description: "회의와 인터뷰를 실시간으로 전사하는 AI. Zoom, Meet와 통합되어 자동으로 회의록을 작성합니다.",
    url: "https://otter.ai",
    category: "other",
    tags: ["회의 전사", "실시간", "Zoom 통합", "회의록"],
    free: true,
  },
  {
    id: "khroma",
    name: "Khroma",
    description: "AI가 개인 취향을 학습해 무한한 색상 팔레트를 생성하는 디자이너용 도구입니다.",
    url: "https://www.khroma.co",
    category: "other",
    tags: ["색상 팔레트", "디자인", "UI/UX", "브랜딩"],
    free: true,
  },
];
