export type Category =
  | "all"
  | "text"
  | "image"
  | "video"
  | "coding"
  | "music"
  | "agent"
  | "other";

export interface PricingPlan {
  name: string;
  price: string;
  features: string[];
  recommended?: boolean;
}

export interface ExpertRating {
  accuracy: number;
  easeOfUse: number;
  features: number;
  performance: number;
  value: number;
  innovation: number;
}

export interface AITool {
  id: string;
  name: string;
  description: string;
  longDescription?: string;
  url: string;
  category: Exclude<Category, "all">;
  tags: string[];
  free: boolean;
  popular?: boolean;
  features?: string[];
  pros?: string[];
  cons?: string[];
  pricing?: { free?: string; paid?: string };
  pricingPlans?: PricingPlan[];
  comparisonNotes?: string;
  useCases?: string[];
  screenshots?: string[];
  expertRating?: ExpertRating;
  whoIsFor?: string[];
  communityReviewSummary?: {
    overall: string;
    pros: { keyword: string; content: string }[];
    cons: { keyword: string; content: string }[];
    sources: { name: string; title: string; excerpt: string }[];
  };
}

export const categories: { value: Category; label: string; emoji: string }[] = [
  { value: "all", label: "전체", emoji: "🌐" },
  { value: "text", label: "텍스트 / 글쓰기", emoji: "✍️" },
  { value: "image", label: "이미지 생성", emoji: "🎨" },
  { value: "video", label: "비디오", emoji: "🎬" },
  { value: "coding", label: "코딩", emoji: "💻" },
  { value: "music", label: "음악", emoji: "🎵" },
  { value: "agent", label: "자동화 / 에이전트", emoji: "🤖" },
  { value: "other", label: "기타", emoji: "✨" },
];

export const aiTools: AITool[] = [
  // === TEXT ===
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: "OpenAI의 가장 강력한 대화형 AI. GPT-4o 기반으로 텍스트, 이미지, 파일 분석 등 다양한 작업을 처리합니다.",
    longDescription: "ChatGPT는 OpenAI가 개발한 세계 최대 사용자 수를 보유한 대화형 AI입니다. GPT-4o 모델을 기반으로 텍스트 생성, 코드 작성, 이미지 분석, 파일 요약, 수학 풀이 등 거의 모든 지식 작업을 수행할 수 있습니다. 무료 플랜에서도 GPT-4o mini 모델을 사용할 수 있으며, Plus 구독 시 더 강력한 GPT-4o 모델과 DALL·E 이미지 생성, 고급 데이터 분석 기능을 이용할 수 있습니다. 플러그인 생태계와 GPT Store를 통해 다양한 전문 기능을 확장할 수 있어 업무 자동화, 학습, 창작 등 다양한 분야에서 활용됩니다.",
    url: "https://chat.openai.com",
    category: "text",
    tags: ["GPT-4o", "대화형 AI", "문서 분석", "OpenAI"],
    free: true,
    popular: true,
    features: ["GPT-4o 멀티모달 모델 지원", "이미지·파일·PDF 분석", "코드 작성 및 디버깅", "DALL·E 이미지 생성(Plus)", "고급 데이터 분석", "GPT Store 플러그인 확장"],
    pros: ["세계 최대 AI 사용자 커뮤니티", "가장 폭넓은 기능 지원", "무료 플랜으로도 충분히 활용 가능", "한국어 지원 우수"],
    cons: ["무료 플랜은 사용량 제한 있음", "학습 데이터 컷오프로 최신 정보 부재(웹 검색 없이)"],
    pricing: { free: "GPT-4o mini 무제한, GPT-4o 제한적 사용", paid: "Plus $20/월 — GPT-4o 우선 접근, 이미지 생성, 고급 분석" },
    useCases: ["보고서·이메일 초안 작성", "코드 작성 및 디버깅", "외국어 번역 및 학습", "데이터 분석 및 시각화", "아이디어 브레인스토밍"],
    pricingPlans: [
      { name: "Free", price: "무료", features: ["GPT-4o mini 무제한", "GPT-4o 제한적 사용", "파일 업로드 가능", "웹 검색 불가"], recommended: true },
      { name: "Plus", price: "$20/월", features: ["GPT-4o 우선 접근", "DALL·E 이미지 생성", "고급 데이터 분석", "메시지 5배 더 많이"] },
      { name: "Pro", price: "$200/월", features: ["GPT-4o 무제한", "고속 응답", "고급 데이터 분석 무제한", "Codex 통합"] },
      { name: "Team", price: "$25/인/월", features: ["Plus 기능 전체", "공유 작업공간", "팀 관리 콘솔"] },
    ],
    comparisonNotes: "일반 사용자: Free로 충분. GPT-4o 우선 접근이 필요하면 Plus. 고급 데이터 분석과 코드 작업이 많으면 Pro. 기업 팀은 Team.",
    screenshots: [
      "https://ai.ktoolu.com/screenshots/chatgpt-1.png",
      "https://ai.ktoolu.com/screenshots/chatgpt-2.png",
      "https://ai.ktoolu.com/screenshots/chatgpt-3.png"
    ],
    expertRating: { accuracy: 4.3, easeOfUse: 4.5, features: 4.8, performance: 4.5, value: 4.7, innovation: 4.6 },
    whoIsFor: ["AI 초보자 — 무료로 시작해보고 싶은 분", "개발자 — 코드 작성 및 디버깅이 필요한 분", "콘텐츠 크리에이터 — 글쓰기·번역이 필요한 분", "일반 사무직 — 보고서·이메일 자동화를 원하는 분"],
    communityReviewSummary: {
      overall: "한국 사용자들은 ChatGPT를 'AI 생산성의 첫걸음'으로 평가합니다. 클리앙·DC Inside 등에서 수집한 실제 사용 후기에 따르면, 전문직(변호사·개발자) 사용자들은 ChatGPT를 업무 필수 도구로 채택했으나 단일 모델 의존보다 여러 LLM(Claude, Gemini)을 병행 사용하는 추세입니다. 무료 버전만으로도 충분히 활용 가능하지만, 고급 작업을 위해서는 Plus($20/월) 이상 구독이 권장됩니다.",
      pros: [
        { keyword: "생산성 향상", content: "방대한 문서 검토/요약, 코드 작성, 법률 자문 초안 등 업무 효율을 극적으로 향상시킨다는 평가" },
        { keyword: "다양한 활용도", content: "코딩, 법률, 세무, 창작, 번역, 데이터 분석 등 거의 모든 분야에서 활용 가능" },
        { keyword: "접근성", content: "무료 버전만으로도 기초 작업 수행 가능, 카카오톡 쿠폰 등 한국형 결제 수단 지원" },
        { keyword: "지속적 발전", content: "GPT-4 → GPT-4o로의 업데이트로 성능이 지속적으로 향상 중" },
      ],
      cons: [
        { keyword: "환각", content: "법률/세무 등 전문 영역에서 잘못된 정보를 생성하는 경우가 있어 반드시 원문 검증이 필요" },
        { keyword: "비용 부담", content: "Pro($200/월) 등 고급 플랜은 개인 사용자에게 부담스러운 수준" },
        { keyword: "경쟁 심화", content: "Claude, Gemini, Perplexity 등 경쟁 모델 대비 전문 영역에서 차별성 감소 추세" },
        { keyword: "구독 전환 불편", content: "Plus→Pro 전환 시 활성 구독 문제 등 사용자 경험 개선 필요" },
      ],
      sources: [
        { name: "클리앙", title: "변호사로서 GPT, GEMINI, PERPLEXITY, CLAUDE 사용결과", excerpt: "대형로펌 세무 12년차 파트너 변호사. GPT PRO가 처음 AI 생산성을 느끼게 해줬으나, 법률업무에서는 Gemini와 Perplexity가 더 만족스러움." },
        { name: "클리앙", title: "최근 AI 코딩으로 SW개발자 영향에 대한 느낌", excerpt: "ChatGPT가 코딩 보조 도구로서 생산성을 크게 향상시킨다는 의견." },
        { name: "DC Inside", title: "팬싸 후기의 비하인드", excerpt: "무료버전은 AI 생성 내용이 부족해서 유료로 업그레이드, 유료 버전이 무료보다 생성 품질이 월등히 좋음." },
        { name: "네이버 블로그", title: "ChatGPT 제대로 활용하는 법! 장단점부터 프롬프트 작성법까지", excerpt: "SURF 구조(Subject, Request, Format, Scope)로 프롬프트 작성법 설명. 초보자가 사용법을 모르면 원하는 결과를 얻기 어려움." },
        { name: "클리앙", title: "AI 3개월 하드 사용기 — ChatGPT, Gemini, Claude, 그리고 Cowork", excerpt: "ChatGPT 유료 1년 사용 후 평가: Gemini는 답변이 뻔하고 독창성 부족. Claude가 논리적 정합성 한 단계 위. 현재 워크플로우: Claude Cowork(초안) → ChatGPT(검증) → Claude Cowork(최종)." },
        { name: "클리앙", title: "chatGPT, claude, grok, gemini 개인적인 간단한 평가", excerpt: "출판 업무 사용자 평가. ChatGPT: \"말 잘 안듣는, 뻔뻔하게 내 돈 뜯어가려는 친구\"로 혹평. Claude: \"내가 내는 돈의 가치를 해주는 친구\"로 최고 평가." },
        { name: "클리앙", title: "제미나이, 클라우드, 챗지피티 허접 사용기", excerpt: "출판 업무와 연계해 세 가지 AI 지속 사용 중. ChatGPT 나오자마자 시작해서 현재까지 계속 사용 중." },
        { name: "클리앙", title: "ChatGPT for kakao 사용기", excerpt: "카톡으로 ChatGPT 쓰는 장점: 접근성 좋음, 대화 흐름 자연스러움, 공유 편함, 부담 없이 질문 가능." },
      ],
    },
  },
  {
    id: "claude",
    name: "Claude",
    description: "Anthropic의 AI 어시스턴트. 긴 문서 처리, 코드 작성, 분석에 뛰어나며 안전성에 중점을 둡니다.",
    longDescription: "Claude는 AI 안전 연구소 Anthropic이 개발한 대화형 AI로, 최대 200K 토큰(약 15만 단어)의 긴 컨텍스트 처리 능력이 핵심 강점입니다. 긴 문서 요약, 복잡한 코드베이스 분석, 세밀한 글쓰기 작업에서 탁월한 성능을 보여줍니다. '헌법적 AI' 방법론을 통해 안전하고 신뢰할 수 있는 답변을 제공하도록 설계되었습니다. Claude 3.5 Sonnet은 코딩 벤치마크에서 최상위 성능을 기록하며, 특히 뉘앙스가 중요한 글쓰기와 분석 작업에서 뛰어난 결과를 냅니다.",
    url: "https://claude.ai",
    category: "text",
    tags: ["Claude 3.5", "긴 컨텍스트", "안전 AI", "Anthropic"],
    free: true,
    popular: true,
    features: ["최대 200K 토큰 긴 컨텍스트", "코드 작성·분석·디버깅", "PDF·문서 업로드 분석", "세밀한 글쓰기 및 편집", "안전성 중심 설계"],
    pros: ["긴 문서 처리 능력 업계 최고 수준", "글쓰기 품질과 뉘앙스가 뛰어남", "안전하고 균형 잡힌 응답", "코딩 성능 우수"],
    cons: ["이미지 생성 기능 없음", "무료 플랜 사용량 제한"],
    pricing: { free: "Claude 3.5 Haiku 사용 가능, 일일 제한 있음", paid: "Pro $20/월 — Claude 3.5 Sonnet 우선 접근, 5배 더 많은 사용량" },
    useCases: ["긴 계약서·논문 분석", "복잡한 코드 리뷰", "고품질 글쓰기 및 편집", "리서치 보조", "다국어 번역"],
    pricingPlans: [
      { name: "Free", price: "무료", features: ["Claude 3.5 Haiku 사용", "일일 메시지 제한", "PDF 업로드 가능", "웹 검색 제한적"], recommended: true },
      { name: "Pro", price: "$20/월", features: ["Claude 3.5 Sonnet 우선", "5배 더 많은 사용량", "긴 문서 처리 최대", "우선 응답 속도"] },
      { name: "Team", price: "$30/인/월", features: ["Pro 기능 전체", "공유 작업공간", "중앙 관리 콘솔", "사용량 분석"] },
      { name: "Enterprise", price: "문의", features: ["맞춤형 모델", "SSO·보안 규정 준수", "전용 지원", "SLA 보장"] },
    ],
    comparisonNotes: "긴 문서·논문 분석이 주 목적: Free로 시작. 하루 5시간 이상 사용: Pro. 연구실·팀 단위: Team. 대규모 기업 보안: Enterprise.",
    screenshots: [
      "https://ai.ktoolu.com/screenshots/claude-1.png",
      "https://ai.ktoolu.com/screenshots/claude-2.png",
      "https://ai.ktoolu.com/screenshots/claude-3.png"
    ],
    expertRating: { accuracy: 4.6, easeOfUse: 4.3, features: 4.4, performance: 4.7, value: 4.5, innovation: 4.4 },
    whoIsFor: ["연구자·학생 — 긴 논문·문서 분석이 필요한 분", "개발자 — 코드 리뷰 및 복잡한 분석이 필요한 분", "작가·에디터 — 고품질 글쓰기가 중요한 분", "기업 문서 담당자 — 긴 계약서·보고서 처리자"],
    communityReviewSummary: {
      overall: "한국 사용자들 사이에서 Claude는 '코딩과 장문 글쓰기에서는 최고지만, 가격과 사용량 제한이 가장 큰 걸림돌'로 평가됩니다. 클리앙 사용기 게시판에서 수집한 실제 후기에 따르면, 개발자와 전문직 사용자들은 Claude의 코드 품질과 문맥 이해력을 높이 평가하면서도 Gemini나 GPT와 병행 사용하는 전략을 주로 채택합니다. 특히 법률/세무 등 전문 분야에서 GPT Pro보다 Claude Max의 딥리서치 성능이 더 우수하다는 평가도 있습니다.",
      pros: [
        { keyword: "코딩 품질", content: "코드 품질 최상급, 1,000행 이상 코드 생성 가능, 복잡한 디버깅에 강함. 플랜 모드로 체계적 작업 가능" },
        { keyword: "문맥 유지", content: "자연스러운 문체, 장문 글쓰기/문서 작업에서 문맥 흐름이 매우 우수함" },
        { keyword: "딥리서치", content: "GPT Pro보다 법률·전문 업무에서 딥리서치 결과가 더 만족스럽다는 평가" },
        { keyword: "안정성", content: "환각(hallucination) 빈도가 GPT/Gemini 대비 매우 낮음. 수백 회 중 1회 꼴" },
      ],
      cons: [
        { keyword: "가격 폭탄", content: "자동 캐싱 미지원으로 요금제에 큰 함정. 추가 사용량 방치 시 하루 $100 소진 가능. 1억 토큰당 $48.8로 가장 비쌈" },
        { keyword: "세션 제한", content: "세션 길이가 매우 짧아 10분마다 진행상황 정리 필요. $20 플랜은 30분 만에 제한 소진" },
        { keyword: "추상어 과민반응", content: "코딩시 불필요/불명확한 단어 사용 시 오작동. Claude.md에 제한 설정 필수" },
        { keyword: "멀티모달 약함", content: "이미지 생성, 실시간 검색 등은 GPT/Gemini 대비 제한적" },
      ],
      sources: [
        { name: "클리앙", title: "변호사로서 GPT, GEMINI, PERPLEXITY, CLAUDE 사용결과", excerpt: "CLAUDE MAX(5x, $110) 유지 중. GPT PRO보다 CLAUDE의 딥리서치가 더 빠르고 결과 만족도 높음. \"GPT는 이제 그만 구독해도 되겠다\"" },
        { name: "클리앙", title: "제미나이 2.5 pro, chatGPT, 클로드, Manus 3개월 굴려본 후기", excerpt: "코드 품질 우수. 세션 길이가 짧지만 환각은 수백회 중 1회로 매우 드묾. $100 플랜 유지 중." },
        { name: "클리앙", title: "바이브 코딩 하실 분들을 위한 작은 조언", excerpt: "4개월간 하루 평균 100커밋. Claude Sonnet 4.5: 자동캐시 히트율 94~97%. $20 플랜은 30분도 안 돼 제한 소진." },
        { name: "네이버 블로그", title: "챗GPT와 클로드(Claude)에 대한 솔직한 사용 후기", excerpt: "문맥 유지 능력과 자연스러운 문체가 강점. 문서·이메일·기획·브레인스토밍에 적합." },
        { name: "클리앙", title: "AI 3개월 하드 사용기 — ChatGPT, Gemini, Claude, 그리고 Cowork", excerpt: "Claude가 논리적 정합성 한 단계 위. Claude Cowork는 내 PC 자료 기반 작업 수행. 현재 워크플로우: Claude Cowork(초안) → ChatGPT(검증) → Claude Cowork(최종)." },
        { name: "클리앙", title: "chatGPT, claude, grok, gemini 개인적인 간단한 평가", excerpt: "Claude: \"내가 내는 돈의 가치를 해주는 친구\"로 최고 평가. 유료 구독 중." },
        { name: "클리앙", title: "토종 오픈클로라고 주장하는 로컬 AI 통합툴 아울로 사용 후기", excerpt: "Claude API 비용 부담으로 로컬 LLM 알아보는 중. M4 맥미니 32GB에 로컬 LLM 설치 시도." },
        { name: "클리앙", title: "지금까지 비개발자가 open claw에게 시켰던 일", excerpt: "비개발자가 Claude Code CLI로 코딩. 보안 점점 강화 중. 간단한 업무 자동화에 활용." },
      ],
    },
  },
  {
    id: "gemini",
    name: "Gemini",
    description: "Google의 멀티모달 AI. Google 서비스와 완벽하게 통합되며 실시간 정보 검색이 가능합니다.",
    longDescription: "Gemini는 Google DeepMind가 개발한 멀티모달 AI로, Google 검색·Gmail·Docs·Drive 등 Google 생태계와 깊이 통합되어 있습니다. Gemini 1.5 Pro는 100만 토큰의 초장문 컨텍스트를 지원하며, Google 검색을 통한 실시간 정보 접근이 가능합니다. YouTube 영상 분석, Google 문서 요약 등 Google 서비스 사용자에게 특히 유용합니다. Gemini Advanced(Ultra 모델)는 복잡한 추론과 멀티모달 작업에서 최고 수준의 성능을 보여줍니다.",
    url: "https://gemini.google.com",
    category: "text",
    tags: ["멀티모달", "Google 통합", "실시간 검색", "Google"],
    free: true,
    popular: true,
    features: ["Google 서비스 완전 통합", "실시간 웹 검색", "최대 100만 토큰 컨텍스트", "이미지·영상·오디오 분석", "Google Workspace 연동"],
    pros: ["실시간 최신 정보 접근 가능", "Google 계정으로 즉시 사용", "Google Docs·Gmail과 완벽 연동", "무료 플랜이 강력함"],
    cons: ["Google 생태계 외 사용 시 장점 감소", "창의적 글쓰기는 타 모델 대비 약함"],
    pricing: { free: "Gemini 1.5 Flash 무제한", paid: "Advanced $19.99/월 — Gemini Ultra, 2TB 드라이브 포함" },
    useCases: ["실시간 뉴스·정보 검색", "Gmail 답장 초안 작성", "Google Docs 문서 요약", "YouTube 영상 내용 분석", "여행·쇼핑 리서치"],
    pricingPlans: [{name:"Free",price:"무료",features:["Gemini 2.0 Flash","Google 계정","1M 토큰"],recommended:true},{name:"Advanced",price:"$19.99/월",features:["Gemini Ultra","2TB Google One","우선 응답"]}],
    comparisonNotes:"일반:Free. Workspace:Business.",
    screenshots:["https://ai.ktoolu.com/screenshots/gemini-1.png","https://ai.ktoolu.com/screenshots/gemini-2.png"],
    expertRating:{accuracy:4.2,easeOfUse:4.6,features:4.5,performance:4.3,value:4.8,innovation:4.4},
    whoIsFor:["Google 생태계 사용자","연구자 — 100만 토큰","일반 사용자"],
    communityReviewSummary: {
      overall: "한국 사용자들은 Gemini를 'ChatGPT 대비 가성비 우수, 구글 생태계와의 강력한 연동'으로 평가합니다. 네이버 블로그와 MLBPARK 등에서 수집한 리뷰에 따르면, Gemini는 ChatGPT보다 분석 수준과 글 퀄리티가 우수하다는 평가를 받으며, 특히 구글 검색·지메일·지도·드라이브·NotebookLM 등 연계 서비스 인프라가 가장 큰 강점입니다. 가격도 ChatGPT Plus(월 29,000원) 대비 Gemini Advanced(월 11,000원)가 훨씬 저렴해 많은 사용자가 갈아타고 있습니다.",
      pros: [
        { keyword: "분석 품질", content: "ChatGPT보다 분석 수준과 글 퀄리티가 우수하고, 수정 요청을 정확히 반영" },
        { keyword: "구글 연동", content: "구글 검색, Gmail, 지도, 유튜브, 드라이브와 완벽 연동. NotebookLM 등 연계 프로그램 인프라가 강점" },
        { keyword: "가성비", content: "ChatGPT Plus(월 29,000원) 대비 Gemini Advanced(월 11,000원)로 훨씬 저렴" },
        { keyword: "사진 속 글 인식", content: "사진 속 글자를 인식하고 정리하는 능력이 ChatGPT보다 편리" },
      ],
      cons: [
        { keyword: "영어 다듬기", content: "영어 문장을 매끄럽게 다듬는 작업에서는 ChatGPT가 약간 더 나음" },
        { keyword: "긍정 편향", content: "너무 긍정적인 응답 스타일, 냉정한 분석을 원하면 별도 프롬프트 필요" },
        { keyword: "한국어 지원", content: "ChatGPT 대비 한국어 처리 정확도와 자연스러움에서 약간 차이" },
      ],
      sources: [
        { name: "네이버 블로그", title: "ChatGPT, Google Gemini Plus 비교, 실사용 후기", excerpt: "1년 넘게 쓴 ChatGPT Plus를 해지하고 Gemini Plus로 갈아탄 후기. 분석 수준과 글 퀄리티가 더 좋고, 수정 요청을 정확히 반영. 구글 서비스 연동이 가장 큰 이유." },
        { name: "네이버 블로그", title: "구글 AI Gemini Advanced 사용 후기", excerpt: "ChatGPT와 무료 Gemini를 쓰다가 Gemini Advanced 2개월 무료 체험 후기." },
        { name: "네이버 블로그", title: "제미나이 직접 사용 후기 | 장점·단점·ChatGPT 비교", excerpt: "무료는 Gemini 3 Flash 모델. 유료 Pro(29,000원)는 3.1 Pro·Deep Think 제공. 안드로이드 기본 AI로 설정 가능." },
        { name: "네이버 블로그", title: "무료 AI 뭐가 다를까? 챗GPT·제미나이·클로드 사용후기", excerpt: "사진 속 글 정리는 제미나이가 편함. 긴 글 작업은 클로드. 셋 다 무료 버전만으로도 할 수 있는 게 많음." },
        { name: "MLBPARK", title: "챗지피티 제미나이 둘 다 써보고 느낀 점", excerpt: "영어 문장 다듬기는 챗GPT가 약간 더 나음. 둘 다 너무 우쭈쭈해주는 모드라 냉정한 프롬프트 추가 필요." },
      ],
    },
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    description: "AI 기반 검색 엔진. 실시간 웹 검색과 AI를 결합해 출처가 명확한 답변을 제공합니다.",
    longDescription: "Perplexity AI는 기존 검색 엔진의 한계를 극복한 AI 검색 엔진입니다. 질문을 입력하면 실시간으로 수십 개의 웹 페이지를 검색·분석하여 출처가 명확한 요약 답변을 제공합니다. 각 답변에는 참고 출처 링크가 첨부되어 사실 확인이 쉽습니다. GPT-4, Claude, Mistral 등 다양한 AI 모델을 선택해 사용할 수 있으며, Copilot 기능으로 심층 리서치도 가능합니다. 학술 논문, 뉴스, 소셜 미디어 등 다양한 출처를 필터링할 수 있습니다.",
    url: "https://www.perplexity.ai",
    category: "text",
    tags: ["AI 검색", "실시간 정보", "출처 인용", "리서치"],
    free: true,
    popular: true,
    features: ["실시간 웹 검색 및 요약", "출처 링크 자동 첨부", "여러 AI 모델 선택 가능", "학술·뉴스 필터 검색", "공간 공유 및 협업"],
    pros: ["검색 결과에 출처가 명확히 표시됨", "최신 정보를 실시간으로 반영", "빠른 리서치에 최적화", "무료로도 충분히 유용"],
    cons: ["창작·글쓰기 작업엔 부적합", "깊은 분석보다 요약에 치중"],
    pricing: { free: "기본 검색 무제한", paid: "Pro $20/월 — 무제한 Copilot, 파일 업로드, 고급 모델" },
    useCases: ["최신 뉴스 및 트렌드 리서치", "제품 비교 및 구매 조사", "학술 자료 수집", "사실 확인(팩트 체크)", "시장 조사"],
    pricingPlans: [{name:"Free",price:"무료",features:["Pro 검색 제한","파일 업로드","하루 5회"],recommended:true},{name:"Pro",price:"$20/월",features:["무제한 Pro","고급 파일","API"]}],
    comparisonNotes:"리서치 많으면 Pro.",
    screenshots:["https://ai.ktoolu.com/screenshots/perplexity-1.png","https://ai.ktoolu.com/screenshots/perplexity-2.png"],
    expertRating:{accuracy:4.5,easeOfUse:4.4,features:4.2,performance:4.3,value:4.6,innovation:4.1},
    whoIsFor:["연구자·학생","저널리스트","일반 사용자"],
    communityReviewSummary: {
      overall: "한국 사용자들은 Perplexity를 '구글의 대항마'이자 'AI 검색의 새로운 기준'으로 평가합니다. 네이버 블로그 리뷰에 따르면, 소스를 인용해 정보의 신뢰성을 확인할 수 있는 점이 가장 큰 차별점입니다.",
      pros: [
        { keyword: "출처 인용", content: "생성된 정보의 출처를 함께 보여줘 신뢰성 확인 가능. Google과의 가장 큰 차별점" },
        { keyword: "자연어 검색", content: "자연어 처리(NLP)로 쿼리 의도를 정확히 파악" },
      ],
      cons: [
        { keyword: "한국어 지원", content: "영어 대비 한국어 검색 결과의 정확도 차이" },
        { keyword: "무료 제한", content: "Pro 검색 횟수 제한이 있음" },
      ],
      sources: [
        { name: "네이버 블로그", title: "Perplexity 퍼플렉시티 GPT 비교 후기 Pro 구글 대항마", excerpt: "Google과 달리 소스를 인용하므로 생성 정보의 신뢰성 확인 가능." },
      ],
    },
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    description: "Notion에 내장된 AI 어시스턴트. 문서 작성, 요약, 번역 등 노트와 프로젝트 관리를 도와줍니다.",
    longDescription: "Notion AI는 세계적인 노트·협업 도구 Notion에 내장된 AI 어시스턴트입니다. 문서를 작성하는 중에 AI의 도움을 받아 초안 생성, 요약, 번역, 맞춤법 교정, 톤 변환 등을 바로 처리할 수 있습니다. 기존 Notion 페이지 내용을 참조해 답변하는 'Q&A' 기능으로 팀 위키나 회사 문서에서 빠르게 정보를 찾을 수 있습니다. Notion을 이미 사용 중인 팀이라면 별도 도구 없이 워크플로우를 크게 향상시킬 수 있습니다.",
    url: "https://www.notion.so/product/ai",
    category: "text",
    tags: ["문서 작성", "요약", "Notion 통합", "협업"],
    free: false,
    features: ["문서 내 인라인 AI 작성 보조", "페이지 요약 및 번역", "워크스페이스 Q&A", "자동 액션 아이템 추출", "톤·스타일 변환"],
    pros: ["Notion 워크플로우에 자연스럽게 통합", "팀 문서 전체를 AI가 학습해 Q&A 가능", "별도 탭 전환 없이 사용"],
    cons: ["Notion 구독자만 사용 가능", "독립 AI 도구보다 기능이 제한적"],
    pricing: { paid: "Notion Plus $10/월에 AI 애드온 $8/월 추가, 또는 AI 포함 플랜 $16/월" },
    useCases: ["회의록 자동 요약", "프로젝트 문서 초안 작성", "팀 위키 Q&A", "다국어 문서 번역", "보고서 구조화"],
    pricingPlans: [{name:"Free",price:"무료",features:["Notion 기본","AI 20회","게스트 10명"],recommended:true},{name:"Plus",price:"$10/월",features:["무제한 AI","파일 100MB","게스트 100명"]},{name:"Business",price:"$18/인/월",features:["Plus 전체","SAML SSO","팀 공간"]}],
    comparisonNotes:"개인:Plus. 팀:Business.",
    screenshots:["https://ai.ktoolu.com/screenshots/notion-1.png","https://ai.ktoolu.com/screenshots/notion-2.png"],
    expertRating:{accuracy:3.8,easeOfUse:4.2,features:4.6,performance:4.0,value:4.3,innovation:4.5},
    whoIsFor:["지식 작업자","스타트업","크리에이터"],
    communityReviewSummary: {
      overall: "Notion AI는 한국 사용자들 사이에서 '문서 작성과 지식 관리를 혁신한 도구'로 평가됩니다. 네이버 블로그와 ABBO 기술블로그 등에서 생산성 향상에 대한 긍정적인 후기가 많습니다.",
      pros: [{keyword:"문서 작성",content:"AI 초안 작성으로 문서 작업 시간 단축. 표·목록 자동 생성"}, {keyword:"지식 관리",content:"Notion 데이터베이스와 AI 결합으로 강력한 지식 관리 시스템 구축"}],
      cons: [{keyword:"비용",content:"Notion 구독료 + AI 애드온($8/월) 추가 부담"}, {keyword:"한국어",content:"영어 대비 한국어 AI 품질 차이. 한국어 문서 작성 시 다소 어색한 표현"}],
      sources: [
        {name:"네이버 블로그",title:"Notion AI 실제 사용 후기, 생산성 향상 꿀팁",excerpt:"문서 초안, 브레인스토밍, 번역까지 Notion AI로 작업 시간 단축."},
        {name:"ABBO 기술블로그",title:"Notion AI 업무 적용 후기",excerpt:"회의록 자동 작성, 업무 보고서 초안 생성에 활용. 생산성 향상 체감."},
      ],
    },
  },
      {
    id: "grammarly",
    name: "Grammarly",
    description: "AI 기반 영문 교정 및 글쓰기 어시스턴트. 문법, 스타일, 명확성을 개선합니다.",
    longDescription: "Grammarly는 3000만 명 이상이 사용하는 세계 최대 영문 글쓰기 보조 도구입니다. 문법 오류 교정을 넘어 문장의 명확성, 어조, 참여도, 전달력까지 분석해 더 나은 글쓰기를 돕습니다. Chrome 확장 프로그램으로 Gmail, Google Docs, Twitter, LinkedIn 등 거의 모든 웹 텍스트 영역에서 실시간으로 작동합니다. Grammarly GO AI 기능으로 이메일 답장, 문서 초안을 자동 생성할 수 있으며, 표절 검사 기능도 제공합니다.",
    url: "https://www.grammarly.com",
    category: "text",
    tags: ["영문 교정", "문법 검사", "글쓰기 개선"],
    free: true,
    features: ["실시간 문법·맞춤법 교정", "문체·어조 분석 및 개선 제안", "표절 검사", "Chrome 확장 프로그램", "AI 글쓰기 보조(GO)"],
    pros: ["어느 웹사이트에서나 즉시 작동", "비영어권 사용자 영어 실력 향상에 최적", "무료 플랜도 핵심 교정 기능 제공"],
    cons: ["영어 전용 (한국어 지원 없음)", "고급 기능은 유료"],
    pricing: { free: "기본 문법·맞춤법 교정", paid: "Premium $12/월 — 고급 제안, 표절 검사, 어조 분석" },
    useCases: ["영문 이메일 작성", "영어 에세이 및 보고서 교정", "LinkedIn 프로필 개선", "비즈니스 문서 품질 향상", "영어 학습"],
    pricingPlans: [{name:"Free",price:"무료",features:["문법·철자 검사","톤 감지","브라우저 확장"],recommended:true},{name:"Premium",price:"$12/월",features:["고급 문법","명확성","표절 검사"]},{name:"Business",price:"$15/인/월",features:["Premium 전체","브랜드 톤","스타일 가이드"]}],
    comparisonNotes:"영어 글쓰기 많으면 Premium.",
    screenshots:["https://ai.ktoolu.com/screenshots/grammarly-1.png","https://ai.ktoolu.com/screenshots/grammarly-2.png"],
    expertRating:{accuracy:4.7,easeOfUse:4.8,features:4.3,performance:4.6,value:4.4,innovation:3.9},
    whoIsFor:["영어 글쓰는 모든 사람","비즈니스 전문가","ESL 학습자"],
    communityReviewSummary: {
      overall: "Grammarly는 영어 글쓰기가 필요한 한국 사용자들에게 필수 도구로 자리잡았습니다. 문법 검사 정확도와 브라우저 확장의 편의성이 가장 큰 장점입니다.",
      pros: [{keyword:"문법 정확도",content:"한국인이 자주 틀리는 영어 문법·전치사·관사까지 정확히 지적"}, {keyword:"확장 프로그램",content:"Chrome·Edge 등 브라우저 확장으로 모든 웹사이트에서 자동 검사"}],
      cons: [{keyword:"한국어 미지원",content:"한국어 문법 검사 불가. 영어 전용 도구"}, {keyword:"Premium 필요",content:"고급 기능(표절 검사, 어조 추천)은 유료"}],
      sources: [
        {name:"네이버 블로그",title:"Grammarly 실제 사용 후기, 프리미엄 가격",excerpt:"영어 이메일 작성시 문법 오류를 실시간으로 잡아줘서 업무 효율 향상."},
        {name:"네이버 블로그",title:"Grammarly 무료와 프리미엄 차이점",excerpt:"무료로도 기본 철자·문법 검사 충분. Premium은 어조 추천·표절 검사."},
      ],
    },
  },


  {
    id: "deepseek",
    name: "DeepSeek",
    description: "2025년 급부상한 중국 오픈소스 LLM. 추론 능력에서 GPT-4o에 필적하며 완전 무료로 제공됩니다.",
    longDescription: "DeepSeek은 중국의 AI 연구소 DeepSeek(深度求索)이 개발한 오픈소스 대규모 언어 모델입니다. DeepSeek-R1 모델은 복잡한 추론 작업에서 OpenAI의 최신 모델에 필적하는 성능을 보여주며 전 세계를 놀라게 했습니다. 특히 API 가격이 GPT-4o의 1/10 수준으로 매우 저렴하며, 자체 추론 과정을 사용자에게 투명하게 공개하는 특징이 있습니다. 2025년 초 출시 이후 단기간에 수억 명의 사용자를 확보하며 AI 업계에 큰 파장을 일으켰습니다. 한국어 지원도 뛰어나며, 웹과 앱에서 무료로 사용할 수 있습니다.",
    url: "https://chat.deepseek.com",
    category: "text",
    tags: ["오픈소스", "추론", "무료", "중국"],
    free: true,
    popular: true,
    features: ["고급 추론 능력(R1)", "오픈소스 모델", "API 매우 저렴", "추론 과정 투명 공개", "한국어 지원 우수"],
    pros: ["추론 능력 GPT-4o 수준", "완전 무료 사용 가능", "API 가격 경쟁사 대비 1/10"],
    cons: ["중국 기반으로 데이터 프라이버시 우려", "일부 편향성 이슈"],
    useCases: ["복잡한 수학·논리 문제 풀이", "코드 생성 및 디버깅", "데이터 분석 및 추론", "학습 및 교육", "비용 효율적인 API 활용"],
    pricingPlans: [{name:"Free",price:"무료",features:["R1 무제한","파일 업로드","웹 검색","앱·웹"],recommended:true},{name:"API",price:"종량제",features:["R1 API","GPT-4o 1/10 가격","추론 투명"]}],
    comparisonNotes:"일반:Free. 개발자:API.",
    screenshots:["https://ai.ktoolu.com/screenshots/deepseek-1.png","https://ai.ktoolu.com/screenshots/deepseek-2.png"],
    expertRating:{accuracy:4.6,easeOfUse:4.0,features:4.1,performance:4.5,value:5.0,innovation:4.8},
    whoIsFor:["비용 민감 사용자","개발자 — 저렴한 API","AI 리서처"],
    communityReviewSummary: {
      overall: "한국 사용자들은 DeepSeek을 'ChatGPT o1급 성능을 완전 무료로' 사용할 수 있는 혁신적인 도구로 평가합니다. 네이버 블로그, 디시인사이드 등에서 수집한 리뷰에 따르면, 추론 과정을 투명하게 공개하는 점이 가장 큰 강점이며, 한국어 처리도 자연스럽고 깔끔합니다. 코드 생성 능력도 GPT-4o에 필적합니다. 다만 추론 속도가 느리고 멀티모달 기능이 OCR 수준에 그치는 점이 단점입니다.",
      pros: [
        { keyword: "완전 무료", content: "ChatGPT o1급 추론 모델(R1)을 무료로, 그것도 무제한으로 사용 가능" },
        { keyword: "추론 과정 공개", content: "결론 도출까지의 사고과정을 텍스트로 보여줘 학습 도구로 활용 가능. 왜 그 답변에 이르렀는지 과정까지 확인" },
        { keyword: "한국어 품질", content: "한국어 말맛이 깔끔하고 직설적이며 부드럽고 자연스러움. 응답 속도 체감상 빠름" },
        { keyword: "코딩 성능", content: "코드 생성 및 디버깅에서 높은 성능. 1,000줄 이상 코드를 한 번에 생성 가능" },
      ],
      cons: [
        { keyword: "추론 속도", content: "추론이 오래 걸리는 경우가 많음. 복잡한 문제는 출력까지 몇 분 기다려야 할 때도 있음" },
        { keyword: "멀티모달 부족", content: "이미지 이해가 단순 OCR 수준. GPT처럼 그림을 보고 설명하거나 파악하는 능력은 없음" },
        { keyword: "중국 기반 우려", content: "중국 기업이 운영하는 서비스라 데이터 프라이버시에 대한 우려가 있음" },
      ],
      sources: [
        { name: "네이버 블로그", title: "DeepSeek R1 사용 후기 - 추론 과정 공개", excerpt: "ChatGPT와 달리 결론 도출 과정을 알려줘 학습 도구로 활용하기 좋음. 생각의 사슬을 텍스트로 뽑아주는 게 인상적." },
        { name: "네이버 블로그", title: "직장인의 AI 도구 6개월 사용 후기", excerpt: "한도 넉넉, 추론 무료. 한국어 말맛 깔끔하고 자연스러움. 발견보다 연산 능력으로 문제 해결." },
        { name: "디시인사이드", title: "DeepSeek R1 무료 체험 후기", excerpt: "성능 좋고 자신의 생각을 알려줌. 멀티모달은 OCR 수준이라 그림 파악은 GPT 필요. 무료로 O1 능력을 쓸 수 있음." },
        { name: "다음 검색", title: "DeepSeek 단점 - 추론 속도 이슈", excerpt: "추론이 오래 걸리는 게 고질병. 완전 무료에 오픈소스인 점은 놀라움." },
        { name: "네이버 뷰", title: "DeepSeek vs ChatGPT 비교", excerpt: "코딩 작업에서 강력. 1,000줄 이상 버그 없는 코드 생성 가능. 완전 무료." },
      ],
    },
  },
  {
    id: "grok",
    name: "Grok",
    description: "xAI의 AI 챗봇. X(트위터) 데이터를 실시간으로 활용하며 독특한 유머 감각이 특징입니다.",
    longDescription: "Grok은 일론 머스크의 xAI가 개발한 AI 어시스턴트로, X(트위터) 플랫폼과의 긴밀한 통합이 가장 큰 강점입니다. X의 실시간 데이터에 접근해 최신 트렌드와 뉴스를 반영한 답변을 제공하며, 기존 AI 모델이 학습 데이터 컷오프로 알지 못하는 최신 정보도 즉시 파악할 수 있습니다. Grok의 가장 독특한 특징은 '반항적인 유머 감각'으로, 다른 AI보다 자유롭고 솔직한 답변 스타일을 가지고 있습니다. 이미지 생성 기능인 Aurora도 내장되어 있어 텍스트와 이미지를 함께 생성할 수 있습니다.",
    url: "https://x.com/i/grok",
    category: "text",
    tags: ["xAI", "실시간 검색", "유머", "일론 머스크"],
    free: true,
    popular: true,
    features: ["X 실시간 데이터 접근", "이미지 생성(Aurora)", "자유로운 답변 스타일", "최신 트렌드 분석"],
    pros: ["타 AI 대비 최신 정보 접근성 우수", "차별화된 답변 스타일", "X 생태계 통합"],
    cons: ["한국어 지원 제한적", "정보의 신뢰성 검증 필요"],
    useCases: ["최신 트렌드 분석", "SNS 콘텐츠 생성", "아이디어 브레인스토밍", "실시간 뉴스 요약"],
    pricingPlans: [{name:"X Free",price:"무료",features:["Grok 기본","X 데이터","제한적"],recommended:true},{name:"X Premium",price:"$8/월",features:["Grok 우선","Aurora 이미지","X 분석"]}],
    comparisonNotes:"X 자주:Premium.",
    screenshots:["https://ai.ktoolu.com/screenshots/grok-1.png","https://ai.ktoolu.com/screenshots/grok-2.png"],
    expertRating:{accuracy:3.9,easeOfUse:4.1,features:3.8,performance:4.0,value:4.5,innovation:4.3},
    whoIsFor:["X 헤비유저","저널리스트"],
    communityReviewSummary:{overall:"Grok은 xAI의 AI 챗봇으로, X(트위터) 실시간 데이터 접근이 가장 큰 차별점입니다.",pros:[{keyword:"실시간 데이터",content:"X 플랫폼 데이터에 실시간 접근. 최신 트렌드 즉시 파악"}, {keyword:"차별화",content:"독특한 유머 감각과 솔직한 답변 스타일. Aurora 이미지 생성 지원"}],cons:[{keyword:"한국어",content:"한국어 지원이 아직 제한적"}, {keyword:"X 의존",content:"X Premium($8/월) 없으면 기능 제한적"}],sources:[{name:"테크 리뷰",title:"Grok AI 첫인상",excerpt:"X 데이터 기반 실시간 답변이 가장 큰 장점. 타 AI와 다른 유머 코드."}]},
  },
  {
    id: "writesonic",
    name: "Writesonic",
    description: "마케팅 콘텐츠 생성에 특화된 AI 글쓰기 도구. 블로그·광고·랜딩페이지를 자동 생성합니다.",
    longDescription: "Writesonic은 마케터와 콘텐츠 크리에이터를 위한 AI 글쓰기 플랫폼으로, 블로그 포스트, 광고 카피, 랜딩 페이지, 이메일 등 80가지 이상의 콘텐츠 템플릿을 제공합니다. 자체 개발한 ChatSonic 챗봇 기능으로 대화형 AI도 함께 사용할 수 있습니다. SEO 최적화 기능이 내장되어 있어 검색 엔진 친화적인 콘텐츠를 쉽게 생성할 수 있으며, GPT-4와 자체 모델을 모두 지원합니다. Futurepedia에서 팝업 카운트 2,828로 Jasper(1,796)를 크게 앞지르는 인기를 보여줍니다.",
    url: "https://writesonic.com",
    category: "text",
    tags: ["마케팅", "블로그", "SEO", "콘텐츠 생성"],
    free: true,
    popular: false,
    features: ["80+ 콘텐츠 템플릿", "SEO 최적화", "ChatSonic 챗봇", "GPT-4 지원", "다국어 지원"],
    pros: ["마케팅 콘텐츠에 최적화", "템플릿 다양성", "SEO 기능 내장"],
    cons: ["창의적 글쓰기에는 한계", "무료 플랜 제한적"],
    useCases: ["블로그 포스트 작성", "광고 카피 생성", "랜딩 페이지 작성", "이메일 마케팅", "SNS 콘텐츠"],
    pricingPlans: [{name:"Free",price:"무료",features:["1만 단어/월","기본 템플릿","ChatSonic"],recommended:true},{name:"Long Form",price:"$19/월",features:["무제한 단어","80+ 템플릿","SEO"]},{name:"Custom",price:"$49/월",features:["Long Form 전체","브랜드 보이스","API"]}],
    comparisonNotes:"가벼운:Free. 전문:Long Form.",
    screenshots:["https://ai.ktoolu.com/screenshots/writesonic-1.png","https://ai.ktoolu.com/screenshots/writesonic-2.png"],
    expertRating:{accuracy:3.7,easeOfUse:4.3,features:4.4,performance:4.1,value:4.5,innovation:3.8},
    whoIsFor:["마케터","SEO 전문가","스타트업"],
    communityReviewSummary:{overall:"Writesonic은 마케팅 콘텐츠 생성에 특화된 AI 글쓰기 도구로, 80개 이상의 템플릿과 SEO 최적화 기능이 강점입니다.",pros:[{keyword:"템플릿 다양성",content:"80개 이상 콘텐츠 템플릿. 블로그·광고·랜딩페이지 등 마케팅 전분야"}, {keyword:"SEO 최적화",content:"검색 엔진 최적화 내장. 키워드 제안·메타 설명 자동 생성"}],cons:[{keyword:"창의성",content:"ChatGPT·Claude 대비 창의적 글쓰기는 다소 부족"}, {keyword:"한국어",content:"한국어 콘텐츠 품질이 영어 대비 낮음"}],sources:[{name:"Futurepedia",title:"Writesonic 리뷰",excerpt:"Futurepedia 팝업 카운트 2,828로 Jasper(1,796)를 크게 앞지르는 인기."}]},
  },
  {
    id: "ms-copilot",
    name: "Microsoft Copilot",
    description: "Microsoft의 AI 어시스턴트. Windows·Office·Bing에 통합되어 일상을 혁신합니다.",
    longDescription: "Microsoft Copilot은 Microsoft 365 앱(Word, Excel, PowerPoint, Teams), Windows, Bing 검색, Edge 브라우저에 깊이 통합된 AI 어시스턴트입니다. Word에서는 문서 초안 작성, Excel에서는 데이터 분석 및 시각화, PowerPoint에서는 슬라이드 생성, Teams에서는 회의 요약 등 오피스 전반에 AI 기능을 제공합니다. GPT-4 모델을 기반으로 하며, 엔터프라이즈 환경에서 데이터 보안과 규정 준수를 보장합니다. 기업 사용자에게 가장 접근성이 높은 AI 도구 중 하나입니다.",
    url: "https://copilot.microsoft.com",
    category: "text",
    tags: ["Microsoft", "Office 통합", "GPT-4", "엔터프라이즈"],
    free: true,
    popular: true,
    features: ["Office 앱 전반 통합", "엑셀 데이터 분석", "파워포인트 슬라이드 생성", "팀즈 회의 요약", "Bing 검색 통합"],
    pros: ["Office 생태계 완벽 통합", "기업 보안 수준", "무료로 기본 기능 사용 가능"],
    cons: ["한국어 기능 제한적", "Copilot Pro 별도 구독 필요"],
    useCases: ["문서 작성 자동화", "데이터 분석·시각화", "프레젠테이션 제작", "회의록 요약", "이메일 작성"],
    pricingPlans: [{name:"Free",price:"무료",features:["Bing 통합","기본 이미지","대화형 AI"],recommended:true},{name:"Copilot Pro",price:"$20/월",features:["Office 365 통합","우선 GPU","더 긴 대화"]},{name:"M365 Copilot",price:"$30/인/월",features:["Pro 전체","Teams 요약","엑셀 분석"]}],
    comparisonNotes:"개인:Free. Office:Pro. 기업:M365.",
    screenshots:["https://ai.ktoolu.com/screenshots/ms-copilot-1.png","https://ai.ktoolu.com/screenshots/ms-copilot-2.png"],
    expertRating:{accuracy:4.1,easeOfUse:4.5,features:4.3,performance:4.2,value:4.4,innovation:4.0},
    whoIsFor:["Windows·Office 사용자","기업","일반 사용자"],
    communityReviewSummary:{overall:"Microsoft Copilot은 Windows·Office·Bing에 통합된 AI 어시스턴트로, 한국 사용자들에게 가장 접근성이 높은 AI 도구 중 하나입니다.",pros:[{keyword:"Office 통합",content:"Word·Excel·PowerPoint·Teams에 AI 기능 내장. 별도 앱 불필요"}, {keyword:"접근성",content:"Windows 사용자라면 누구나 무료로 사용 가능. Bing 검색에도 통합"}],cons:[{keyword:"한국어",content:"영어 대비 한국어 기능과 품질에서 차이"}, {keyword:"Pro 필요",content:"고급 기능은 Copilot Pro($20/월) 또는 M365 Copilot 구독 필요"}],sources:[{name:"테크 리뷰",title:"Microsoft Copilot 사용후기",excerpt:"Windows 11에 내장된 AI 도우미. 엣지 브라우저에서 바로 사용 가능."}]},
  },  // === IMAGE ===
  {
    id: "midjourney",
    name: "Midjourney",
    description: "가장 인기 있는 AI 이미지 생성 도구. Discord 기반으로 놀라운 아트워크와 사실적인 이미지를 만들어냅니다.",
    longDescription: "Midjourney는 예술적 감각과 품질 면에서 업계 최고로 평가받는 AI 이미지 생성 도구입니다. Discord 채널에서 명령어를 입력하는 방식으로 작동하며, 웹 인터페이스도 제공합니다. V6 모델은 사진에 가까운 사실성과 뛰어난 구성력을 자랑하며, 일관성 기능으로 동일한 캐릭터를 여러 이미지에서 유지할 수 있습니다. 상업적 이용이 가능하며, 패션, 광고, 게임, 영화 등 다양한 산업에서 전문가들이 활발히 사용합니다. 매달 수억 장의 이미지가 생성될 만큼 방대한 커뮤니티를 보유하고 있습니다.",
    url: "https://www.midjourney.com",
    category: "image",
    tags: ["아트워크", "Discord", "고품질", "상업적 사용"],
    free: false,
    popular: true,
    features: ["최고 수준의 예술적 품질", "캐릭터 일관성 유지", "다양한 스타일 프리셋", "업스케일링 및 변형", "상업적 사용 허가"],
    pros: ["이미지 품질과 예술성이 업계 최고", "활발한 커뮤니티와 풍부한 튜토리얼", "다양한 스타일 표현 가능"],
    cons: ["무료 플랜 없음", "Discord 기반이라 초보자에게 진입 장벽"],
    pricing: { paid: "Basic $10/월(200장), Standard $30/월(무제한 릴렉스), Pro $60/월" },
    useCases: ["광고·마케팅 비주얼 제작", "게임 콘셉트 아트", "소셜 미디어 이미지", "북 커버 디자인", "패션·제품 시각화"],
    pricingPlans: [{name:"Basic",price:"$10/월",features:["3.3h GPU","개인 Discord","상업"],recommended:true},{name:"Standard",price:"$30/월",features:["15h GPU","Stealth","빠른 생성"]},{name:"Pro",price:"$60/월",features:["30h GPU","Stealth 무제한","12개 동시"]}],
    comparisonNotes:"취미:Basic. 전문:Standard.",
    screenshots:["https://ai.ktoolu.com/screenshots/midjourney-1.png","https://ai.ktoolu.com/screenshots/midjourney-2.png"],
    expertRating:{accuracy:3.5,easeOfUse:3.8,features:4.6,performance:4.8,value:4.2,innovation:4.7},
    whoIsFor:["디자이너·아티스트","광고·마케팅","게임·영화"],
    communityReviewSummary: {
      overall: "한국 사용자들은 Midjourney를 'AI 이미지 생성의 최상급 퀄리티'로 평가합니다. 네이버 블로그에서 수집한 리뷰에 따르면, 디테일 표현, 색감, 질감, 스타일 통일성에서 무료 툴을 압도합니다. 특히 인물화, 일러스트, 컨셉 아트 스타일에서 감탄이 나올 정도의 퀄리티를 보여줍니다. V8 알파에서는 프롬프트와 스타일을 분리해 AI가 사용자 취향을 학습하는 방식으로 진화했습니다. 다만 월 3만 원의 구독비는 취미 사용자에게 부담입니다.",
      pros: [
        { keyword: "최상급 퀄리티", content: "디테일 표현, 색감, 질감, 구도, 스타일 통일성에서 무료 툴 대비 압도적. 인물화·일러스트·컨셉 아트에 강함" },
        { keyword: "V8 진화", content: "프롬프트와 스타일 분리, 사용자 취향 학습. 알파 단계에서도 변화 폭이 상당함" },
        { keyword: "Discord·웹 지원", content: "Discord 기반으로 작동하며 웹 인터페이스도 제공. 커뮤니티 활성화" },
      ],
      cons: [
        { keyword: "비용 부담", content: "월 3만 원의 구독비, 학생이나 취미 사용자에게 부담스러운 수준" },
        { keyword: "영어 프롬프트", content: "한국어보다 영어 프롬프트가 더 좋은 결과물을 생성하는 경향" },
        { keyword: "무료 크레딧 부족", content: "무료 체험 크레딧이 제한적이어서 충분히 테스트하기 어려움" },
      ],
      sources: [
        { name: "네이버 블로그", title: "AI 요금제, 생각보다 부담이 있었던 이유", excerpt: "결과물 완성도가 좋고 색감·질감 표현이 뛰어남. 실사용 도구로 보는 분들이 많음." },
        { name: "네이버 블로그", title: "미드저니 퀄리티, 정말 뛰어난가요?", excerpt: "디테일 표현, 구도, 색감 조화, 스타일 통일성이 무료 툴보다 확실히 매끄럽고 고급스러움." },
        { name: "네이버 블로그", title: "Midjourney 내돈내산 후기 (유료 구독)", excerpt: "스탠다드 vs 프로 플랜 고민. 영어로 사용하는 것이 더 잘 나오는 느낌." },
        { name: "다음 검색", title: "감성적이고 고퀄리티 AI 이미지", excerpt: "결과물이 감성적이고 고퀄리티. 구독비 월 3만 원은 부담." },
        { name: "네이버 블로그", title: "Midjourney V8 알파 출시 소식", excerpt: "무엇을 그릴지는 프롬프트, 스타일은 AI가 취향 학습. 알파인데도 변경 폭이 상당함." },
      ],
    },
  },
  {
    id: "dalle3",
    name: "DALL·E 3",
    description: "OpenAI의 최신 이미지 생성 AI. 텍스트 설명을 정확하게 반영한 고품질 이미지를 생성합니다.",
    longDescription: "DALL·E 3는 OpenAI가 개발한 텍스트→이미지 생성 AI로, 텍스트 프롬프트를 정확하게 반영하는 능력이 핵심 강점입니다. ChatGPT Plus 구독자는 ChatGPT 대화 중에 바로 이미지를 생성할 수 있어 편의성이 높습니다. 이전 버전 대비 텍스트가 포함된 이미지 생성 능력이 크게 향상되었으며, 복잡한 장면 묘사도 정확하게 구현합니다. 안전 필터가 강력해 창작의 자유가 제한될 수 있지만, 상업적으로 안전한 이미지 생성에 적합합니다.",
    url: "https://openai.com/dall-e-3",
    category: "image",
    tags: ["OpenAI", "텍스트→이미지", "정확도", "ChatGPT 통합"],
    free: false,
    popular: true,
    features: ["프롬프트 정확도 높음", "ChatGPT 대화 내 이미지 생성", "이미지 내 텍스트 렌더링", "다양한 비율 지원", "API 제공"],
    pros: ["ChatGPT 사용자는 별도 가입 불필요", "프롬프트 의도 반영 정확도 우수", "API로 서비스 개발 가능"],
    cons: ["단독 구독 플랜 없음(ChatGPT Plus 필요)", "Midjourney 대비 예술성 낮음", "강한 안전 필터"],
    pricing: { paid: "ChatGPT Plus $20/월에 포함, API는 이미지당 $0.04~$0.12" },
    useCases: ["프레젠테이션용 커스텀 이미지", "블로그 썸네일", "제품 콘셉트 시각화", "교육 자료 삽화", "앱·웹 UI 목업"],
    pricingPlans: [{name:"ChatGPT Free",price:"무료",features:["DALL-E 3 기본","제한적 생성","ChatGPT 통합"],recommended:true},{name:"ChatGPT Plus",price:"$20/월",features:["DALL-E 3 무제한","고해상도","스타일 일관성"]}],
    comparisonNotes:"가끔:Free. 자주:Plus.",
    screenshots:["https://ai.ktoolu.com/screenshots/dalle-1.png","https://ai.ktoolu.com/screenshots/dalle-2.png"],
    expertRating:{accuracy:4.3,easeOfUse:4.7,features:4.1,performance:4.4,value:4.5,innovation:4.2},
    whoIsFor:["ChatGPT 사용자","크리에이터","일반 사용자"],
    communityReviewSummary:{overall:"DALL·E 3는 ChatGPT에 내장된 이미지 생성 모델로 한국 사용자들에게 접근성이 가장 높은 AI 이미지 도구입니다. 블로그·콘텐츠 제작용으로 Midjourney보다 실용적이라는 평가가 많습니다.",pros:[{keyword:"ChatGPT 통합",content:"채팅 내에서 바로 이미지 생성·편집. 별도 도구 불필요"},{keyword:"텍스트 이해도",content:"자연어 프롬프트에 정밀하게 반응. 초보자도 쉽게 사용 가능"}],cons:[{keyword:"퀄리티",content:"Midjourney 대비 예술적 완성도에서 차이"},{keyword:"무료 제한",content:"ChatGPT 무료 사용자는 하루 3~5장 제한"}],sources:[{name:"네이버 블로그",title:"Midjourney v7 vs DALL-E 3 vs Stable Diffusion 비교",excerpt:"예술 작품용: Midjourney, 블로그 콘텐츠용: DALL-E 3, 고급 사용자: Stable Diffusion."},{name:"네이버 블로그",title:"무료 AI 이미지 생성, 나노바나나 vs DALL-E 비교",excerpt:"DALL-E 하루 3~5장 무료 한도. 텍스트 이해도와 정확도는 DALL-E가 우수."}]},
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    description: "오픈소스 이미지 생성 모델. 로컬 실행 가능하며 다양한 커스터마이징이 가능합니다.",
    longDescription: "Stable Diffusion은 Stability AI가 개발하고 오픈소스로 공개한 이미지 생성 모델입니다. 로컬 PC에서 직접 실행할 수 있어 인터넷 연결 없이 이미지를 무제한으로 생성할 수 있습니다. Civitai 등 커뮤니티에서 수만 개의 파인튜닝 모델을 무료로 다운로드해 특정 스타일에 최적화된 이미지를 생성할 수 있습니다. AUTOMATIC1111, ComfyUI 등 오픈소스 GUI를 통해 ControlNet, img2img 등 고급 기능을 활용할 수 있어 전문 사용자에게 강력한 도구입니다.",
    url: "https://stability.ai",
    category: "image",
    tags: ["오픈소스", "로컬 실행", "커스터마이징", "무료"],
    free: true,
    features: ["완전 무료·오픈소스", "로컬 PC 실행(GPU 필요)", "무제한 이미지 생성", "수만 개 커뮤니티 모델", "ControlNet 정밀 제어"],
    pros: ["한 번 설치 후 무제한 무료 사용", "프라이버시 보호(로컬 실행)", "커스터마이징 한계 없음"],
    cons: ["설치 및 설정이 복잡함", "고성능 GPU 필요(VRAM 8GB 이상 권장)", "초보자 진입 장벽 높음"],
    pricing: { free: "오픈소스 무료(로컬 실행), DreamStudio 클라우드는 크레딧 구매" },
    useCases: ["대량 이미지 생성 파이프라인", "특정 스타일 캐릭터 생성", "인물 사진 스타일 변환", "프라이버시가 중요한 이미지 작업", "AI 아트 연구"],
    pricingPlans: [{name:"Local",price:"무료",features:["오픈소스","로컬 실행","GPU 필요"],recommended:true},{name:"Cloud API",price:"종량제",features:["API 과금","클라우드","LoRA·ControlNet"]}],
    comparisonNotes:"GPU 보유:Local.",
    screenshots:["https://ai.ktoolu.com/screenshots/sd-1.png","https://ai.ktoolu.com/screenshots/sd-2.png"],
    expertRating:{accuracy:3.6,easeOfUse:3.2,features:4.9,performance:4.3,value:5.0,innovation:4.8},
    whoIsFor:["개발자·연구자","AI 아티스트","프라이버시 중시"],
    communityReviewSummary: {
      overall: "Stable Diffusion은 오픈소스 이미지 생성 모델로 한국 사용자들에게 높은 자유도와 커스터마이징 가능성으로 평가받습니다. 클리앙 사용기와 tali.kr AI 커뮤니티에서 활발한 논의가 이뤄지고 있습니다.",
      pros: [{keyword:"오픈소스",content:"완전 무료, 로컬 실행 가능, 모델 파인튜닝 자유로움"}, {keyword:"커스터마이징",content:"LoRA, ControlNet 등 확장 기능으로 세밀한 제어 가능"}],
      cons: [{keyword:"진입 장벽",content:"로컬 설치는 GPU 필요, 초보자에게 설치 과정이 복잡"}, {keyword:"퀄리티",content:"Midjourney 대비 기본 생성물의 예술적 완성도 차이"}],
      sources: [
        {name:"클리앙",title:"Stable Diffusion 로컬 설치 후기",excerpt:"M1 맥에서 Stable Diffusion 돌려본 후기. GPU 없이도 CPU로 구동 가능."},
        {name:"tali.kr",title:"Stable Diffusion WebUI 설치 가이드 및 후기",excerpt:"AI 그림 커뮤니티에서 가장 많이 사용되는 오픈소스 모델."},
      ],
    },
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    description: "Adobe의 AI 이미지 생성 도구. Photoshop, Illustrator와 통합되어 창작 워크플로우를 강화합니다.",
    longDescription: "Adobe Firefly는 Adobe가 개발한 생성형 AI로, Photoshop의 '생성형 채우기', Illustrator의 '벡터화' 등 기존 Adobe 도구에 자연스럽게 통합되어 있습니다. 상업적으로 안전한 이미지 생성을 위해 Adobe Stock 라이선스 콘텐츠와 저작권이 만료된 이미지만 학습 데이터로 사용했습니다. 따라서 생성된 이미지는 상업적 목적으로 안전하게 사용할 수 있습니다. Photoshop 내에서 배경 확장, 객체 제거, 요소 추가 등 편집 작업에 AI를 활용할 수 있어 디자이너와 사진작가에게 특히 유용합니다.",
    url: "https://firefly.adobe.com",
    category: "image",
    tags: ["Adobe 통합", "상업 라이선스", "제너레이티브 필", "크리에이티브"],
    free: true,
    popular: true,
    features: ["Photoshop·Illustrator 완전 통합", "상업적 사용 안전 보장", "생성형 채우기·확장", "텍스트 효과 생성", "벡터 이미지 생성"],
    pros: ["Adobe 제품 사용자에게 매우 편리", "상업적 라이선스 문제 없음", "무료 크레딧으로 시작 가능"],
    cons: ["Adobe 생태계 외 사용 불편", "Midjourney 대비 예술적 자유도 낮음"],
    pricing: { free: "월 25 크레딧 무료", paid: "Adobe Creative Cloud 구독에 포함, 추가 크레딧 구매 가능" },
    useCases: ["Photoshop 사진 편집 보조", "상업 광고 이미지 제작", "브랜드 비주얼 아이덴티티", "SNS 콘텐츠 디자인", "제품 사진 배경 교체"],
    pricingPlans: [{name:"Free",price:"무료",features:["25 생성/월","기본 기능","Express 통합"],recommended:true},{name:"Premium",price:"$4.99/월",features:["100 생성/월","고급 편집","상업 라이선스"]},{name:"CC All Apps",price:"$54.99/월",features:["무제한 생성","Photoshop 통합","Illustrator 통합"]}],
    comparisonNotes:"가끔:Free. Adobe:CC.",
    screenshots:["https://ai.ktoolu.com/screenshots/firefly-1.png","https://ai.ktoolu.com/screenshots/firefly-2.png"],
    expertRating:{accuracy:4.0,easeOfUse:4.5,features:4.2,performance:4.1,value:4.3,innovation:4.0},
    whoIsFor:["Adobe 사용자","그래픽 디자이너","마케터"],
    communityReviewSummary: {
      overall: "Adobe Firefly는 Adobe 생태계와의 완벽한 통합으로 한국 사용자들에게 높은 평가를 받습니다. Photoshop·Illustrator와의 연동이 가장 큰 강점이며, 상업적 이용이 가능한 라이선스 정책도 긍정적입니다.",
      pros: [{keyword:"Adobe 통합",content:"Photoshop, Illustrator, Express와 완벽 연동. 기존 워크플로우 유지"}, {keyword:"상업 라이선스",content:"생성 이미지의 상업적 사용 가능, 법적 리스크 없음"}],
      cons: [{keyword:"비용",content:"무료는 25생성/월 제한. 고급 기능은 Creative Cloud 구독 필요"}, {keyword:"퀄리티",content:"Midjourney 대비 예술적 완성도에서 차이"}],
      sources: [
        {name:"네이버 블로그",title:"Adobe Firefly 사용 후기와 꿀팁",excerpt:"Photoshop과 연동되는 생성형 채우기 기능이 가장 유용. 상업적 이용 가능."},
        {name:"네이버 블로그",title:"Adobe Firefly로 만드는 AI 디자인",excerpt:"텍스트 효과, 리컬러 등 디자이너를 위한 실용적인 기능 제공."},
      ],
    },
  },
    {
    id: "leonardo-ai",
    name: "Leonardo AI",
    description: "게임 에셋, 캐릭터 디자인에 특화된 AI 이미지 생성 플랫폼. 다양한 파인튜닝 모델을 제공합니다.",
    longDescription: "Leonardo AI는 게임 개발자와 크리에이터를 위한 AI 이미지 생성 플랫폼입니다. 게임 에셋, 캐릭터, 배경, 아이템 등 게임 제작에 필요한 비주얼을 빠르게 생성할 수 있습니다. 자체 파인튜닝 기능으로 특정 스타일의 모델을 학습시켜 일관된 캐릭터와 세계관을 유지할 수 있습니다. 실시간 캔버스 편집, 모션 생성, 3D 텍스처 생성 등 고급 기능도 제공하며, 커뮤니티에서 공유된 다양한 파인튜닝 모델을 무료로 활용할 수 있습니다.",
    url: "https://leonardo.ai",
    category: "image",
    tags: ["게임 에셋", "캐릭터", "파인튜닝", "크리에이티브"],
    free: true,
    features: ["게임 에셋 특화 생성", "커스텀 모델 파인튜닝", "실시간 캔버스 편집", "모션 이미지 생성", "3D 텍스처 생성"],
    pros: ["게임·애니메이션 스타일 이미지에 강점", "무료 플랜이 넉넉함(일 150 토큰)", "파인튜닝으로 일관된 캐릭터 유지"],
    cons: ["일반 사실적 사진 생성은 다소 약함", "인터페이스 다소 복잡"],
    pricing: { free: "하루 150 토큰 무료", paid: "Apprentice $10/월, Artisan $24/월, Maestro $48/월" },
    useCases: ["게임 캐릭터 및 배경 디자인", "웹툰·만화 스타일 이미지", "NFT 아트 제작", "애니메이션 콘셉트 아트", "인디게임 에셋 제작"],
    pricingPlans: [{name:"Free",price:"무료",features:["150 토큰/일","기본 모델","커뮤니티"],recommended:true},{name:"Apprentice",price:"$10/월",features:["무제한 생성","고급 모델","API"]},{name:"Artisan",price:"$30/월",features:["Apprentice 전체","트레이닝","우선 처리"]}],
    comparisonNotes:"시작:Free. 활발:Apprentice.",
    screenshots:["https://ai.ktoolu.com/screenshots/leonardo-1.png","https://ai.ktoolu.com/screenshots/leonardo-2.png"],
    expertRating:{accuracy:3.8,easeOfUse:4.3,features:4.4,performance:4.0,value:4.5,innovation:4.1},
    whoIsFor:["게임 개발자","취미 아티스트","크리에이터"],
    communityReviewSummary:{overall:"Leonardo AI는 게임 에셋과 캐릭터 디자인에 특화된 AI 이미지 생성 도구로, 게임 개발자들 사이에서 인기가 높습니다.",pros:[{keyword:"게임 특화",content:"게임 에셋·캐릭터·배경 생성에 특화. 다양한 파인튜닝 모델 제공"}, {keyword:"무료",content:"무료 150토큰/일. 다른 도구 대비 넉넉한 무료 사용량"}],cons:[{keyword:"일반 이미지",content:"Midjourney 대비 일반 이미지 생성 품질에서 차이"}, {keyword:"학습 필요",content:"최대 활용을 위한 다양한 설정 학습 필요"}],sources:[{name:"커뮤니티 리뷰",title:"Leonardo AI 게임 개발 활용기",excerpt:"게임 캐릭터 컨셉 아트 제작에 활용. 무료로 시작하기 좋음."}]},
  },
  {
    id: "canva-ai",
    name: "Canva AI",
    description: "Canva에 통합된 AI 기능. 이미지 생성, 배경 제거, 마법 편집 등 디자인 작업을 자동화합니다.",
    longDescription: "Canva AI는 세계 1억 7000만 명이 사용하는 디자인 플랫폼 Canva에 통합된 AI 기능 모음입니다. '마법 미디어'로 텍스트 프롬프트에서 이미지를 생성하고, '배경 제거'로 클릭 한 번에 배경을 지우며, '마법 편집'으로 이미지 요소를 교체할 수 있습니다. AI 프레젠테이션 생성 기능은 주제만 입력하면 슬라이드 전체를 자동으로 만들어줍니다. 디자인 전문 지식 없이도 전문가 수준의 결과물을 만들 수 있어 초보자에게 특히 유용합니다.",
    url: "https://www.canva.com/ai-image-generator",
    category: "image",
    tags: ["디자인 통합", "배경 제거", "템플릿", "손쉬운 사용"],
    free: true,
    features: ["텍스트→이미지 생성", "원클릭 배경 제거", "AI 프레젠테이션 자동 생성", "마법 편집·확장", "AI 글쓰기 보조"],
    pros: ["디자인 초보자도 쉽게 사용", "Canva 디자인 도구와 완벽 연동", "무료 플랜도 기본 AI 기능 제공"],
    cons: ["전문 이미지 생성 도구보다 품질 낮음", "AI 기능 대부분 Pro 구독 필요"],
    pricing: { free: "기본 AI 기능 제한적 무료", paid: "Pro $15/월 — 모든 AI 기능, 프리미엄 템플릿 10만 개+" },
    useCases: ["SNS 게시물 디자인", "프레젠테이션 제작", "마케팅 배너 제작", "유튜브 썸네일", "명함·포스터 디자인"],
    pricingPlans: [{name:"Free",price:"무료",features:["25만+ 템플릿","AI 제한","5GB"],recommended:true},{name:"Pro",price:"$12.99/월",features:["AI 무제한","Magic Studio","100GB"]},{name:"Teams",price:"$14.99/인/월",features:["Pro 전체","템플릿 공유","중앙 관리"]}],
    comparisonNotes:"개인:Free. 전문:Pro.",
    screenshots:["https://ai.ktoolu.com/screenshots/canva-1.png","https://ai.ktoolu.com/screenshots/canva-2.png"],
    expertRating:{accuracy:3.5,easeOfUse:4.9,features:4.5,performance:4.2,value:4.7,innovation:4.3},
    whoIsFor:["디자인 초보자","SNS 마케터","교육자"],
    communityReviewSummary: {
      overall: "한국 사용자들은 Canva AI를 '디자인 초보자를 위한 혁신'으로 평가합니다. 네이버 블로그 리뷰에 따르면, AI 기능 덕분에 퇴근 시간이 빨라질 정도로 생산성 향상에 도움이 됩니다.",
      pros: [
        { keyword: "AI 디자인", content: "Magic Studio 등 AI 기능으로 디자인 초보자도 전문가 수준의 결과물 생성" },
        { keyword: "템플릿 다양성", content: "25만 개 이상의 템플릿으로 빠른 디자인 제작 가능" },
      ],
      cons: [
        { keyword: "고급 편집 한계", content: "Photoshop 등 전문 도구 대비 세밀한 편집은 제한적" },
        { keyword: "유료 기능", content: "고급 AI 기능은 Pro 구독 필요" },
      ],
      sources: [
        { name: "네이버 블로그", title: "캔바 AI 어떻게 활용할까? 퇴근 시간 빨라지는 핵심 기능 실사용 후기", excerpt: "결과물 만족스러움. AI 기능 덕분에 퇴근 시간이 빨라짐." },
        { name: "네이버 블로그", title: "캔바 인 리얼 라이프 (Canva in Real Life) 행사 후기", excerpt: "오직 캔바만으로 팝업 스토어 인쇄물 제작. 전문 브랜딩 작업 가능." },
      ],
    },
  },


  {
    id: "image-nanobana",
    name: "Image Nanobana",
    description: "고품질 이미지 생성 AI. 세밀한 디테일과 사실적인 표현력이 강점입니다.",
    longDescription: "Image Nanobana(이미지 나노바나나)는 고품질 이미지 생성에 특화된 AI 도구로, 뛰어난 디테일 표현과 사실적인 이미지 생성 능력이 강점입니다. 짧은 프롬프트만으로도 원하는 느낌의 이미지를 생성할 수 있으며, 생성된 이미지를 짧은 영상으로도 제작 가능합니다. 사용자 친화적인 인터페이스와 빠른 생성 속도로 크리에이터들 사이에서 인기를 얻고 있습니다.",
    url: "https://image-nanobana.example.com",
    category: "image",
    tags: ["고품질", "이미지 생성", "크리에이티브"],
    free: false,
    popular: false,
    features: ["고해상도 이미지 생성", "세밀한 디테일 표현", "이미지-비디오 변환"],
    pros: ["뛰어난 디테일 표현력", "사용자 친화적 인터페이스"],
    cons: ["유료 서비스", "일부 스타일 제한적"],
    useCases: ["고품질 이미지 제작", "크리에이티브 작업", "SNS 콘텐츠", "짧은 영상 제작"],
    pricingPlans: [{name:"Basic",price:"$9.99/월",features:["100장 생성","기본 해상도","이미지→비디오"],recommended:true},{name:"Pro",price:"$24.99/월",features:["무제한 생성","4K","상업 라이선스"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/nanobana-1.png","https://ai.ktoolu.com/screenshots/nanobana-2.png"],
    expertRating:{accuracy:3.9,easeOfUse:4.2,features:3.8,performance:4.1,value:4.0,innovation:4.3},
    whoIsFor:["디지털 아티스트","크리에이터"],
    communityReviewSummary:{overall:"Image Nanobana(이미지 나노바나나)는 고품질 이미지 생성 AI로, 디테일 표현과 사실성에 강점이 있습니다.",pros:[{keyword:"디테일",content:"뛰어난 디테일 표현력. 사실적인 이미지 생성에 강점"}, {keyword:"이미지→비디오",content:"생성된 이미지를 짧은 영상으로 변환 가능"}],cons:[{keyword:"유료",content:"무료 사용량 제한적. 고급 기능은 유료"}, {keyword:"인지도",content:"Midjourney·DALL-E 대비 낮은 인지도"}],sources:[{name:"사용자 리뷰",title:"나노바나나 이미지 생성 사용기",excerpt:"빠른 생성 속도와 디테일 표현이 장점. 이미지를 영상으로도 제작 가능."}]},
  },
  {
    id: "chatgpt-image",
    name: "ChatGPT Image",
    description: "ChatGPT에 내장된 이미지 생성 기능. GPT-4o의 멀티모달 능력으로 텍스트와 이미지를 통합 생성합니다.",
    longDescription: "ChatGPT Image는 ChatGPT에 내장된 AI 이미지 생성 기능으로, GPT-4o의 멀티모달 능력을 활용해 텍스트와 이미지를 통합적으로 생성합니다. DALL-E와 달리 ChatGPT와의 대화 맥락을 이해하고 이미지를 생성하므로, 이전 대화 내용을 바탕으로 일관된 스타일의 이미지를 만들 수 있습니다. 채팅 내에서 바로 이미지를 생성하고 편집할 수 있어 워크플로우가 매우 간편합니다.",
    url: "https://chat.openai.com",
    category: "image",
    tags: ["GPT-4o", "멀티모달", "이미지 생성", "ChatGPT 통합"],
    free: true,
    popular: true,
    features: ["대화 맥락 이해 이미지 생성", "실시간 이미지 편집", "텍스트-이미지 통합 생성"],
    pros: ["대화 맥락 기반 이미지 생성", "별도 도구 불필요", "실시간 편집 가능"],
    cons: ["전용 이미지 도구 대비 세밀한 제어 부족", "고급 기능은 Plus 필요"],
    useCases: ["프레젠테이션 이미지", "SNS 콘텐츠", "아이디어 시각화", "일러스트레이션"],
    pricingPlans: [{name:"Free",price:"무료",features:["ChatGPT 이미지","GPT-4o mini","제한적"],recommended:true},{name:"Plus",price:"$20/월",features:["GPT-4o 이미지","무제한","DALL-E 통합"]}],
    comparisonNotes:"가끔:Free. 자주:Plus.",
    screenshots:["https://ai.ktoolu.com/screenshots/chatgpt-img-1.png","https://ai.ktoolu.com/screenshots/chatgpt-img-2.png"],
    expertRating:{accuracy:4.1,easeOfUse:4.8,features:3.9,performance:4.2,value:4.6,innovation:4.4},
    whoIsFor:["ChatGPT 사용자","일반 사용자"],
    communityReviewSummary:{overall:"ChatGPT Image는 ChatGPT에 내장된 이미지 생성 기능으로, 대화 맥락을 이해하고 이미지를 생성하는 점이 강점입니다.",pros:[{keyword:"맥락 이해",content:"대화 내용을 바탕으로 일관된 스타일의 이미지 생성. 이전 내용 반영"}, {keyword:"별도 도구 불필요",content:"ChatGPT 하나로 텍스트·이미지 모두 처리. 워크플로우 간소화"}],cons:[{keyword:"세밀 제어",content:"전용 이미지 도구 대비 세밀한 스타일·구성 제어 부족"}, {keyword:"Plus 필요",content:"고급 기능은 ChatGPT Plus($20/월) 필요"}],sources:[{name:"사용자 리뷰",title:"ChatGPT 이미지 생성 활용",excerpt:"대화 중 바로 이미지 생성. 수정 요청도 자연어로 가능."}]},
  },  // === VIDEO ===
  {
    id: "runway",
    name: "Runway",
    description: "전문적인 AI 비디오 생성 및 편집 플랫폼. Gen-2로 텍스트/이미지를 고품질 비디오로 변환합니다.",
    longDescription: "Runway는 할리우드 영화 제작팀도 사용하는 전문 AI 비디오 플랫폼입니다. Gen-3 Alpha 모델로 텍스트 또는 이미지를 최대 10초의 고품질 비디오로 변환할 수 있으며, 실제 같은 움직임과 세밀한 디테일이 특징입니다. 비디오 편집, 배경 제거, 인페인팅, 오디오 분리 등 전문 편집 도구도 제공합니다. 영화 '에브리씽 에브리웨어 올 앳 원스' 등의 제작에 활용될 만큼 전문가들의 신뢰를 받고 있습니다.",
    url: "https://runwayml.com",
    category: "video",
    tags: ["비디오 생성", "Gen-3", "영상 편집", "크리에이티브"],
    free: true,
    popular: true,
    features: ["텍스트·이미지→비디오 생성", "전문 비디오 편집 도구", "배경 제거·인페인팅", "모션 브러시 제어", "팀 협업 기능"],
    pros: ["업계 최고 수준의 비디오 품질", "편집 도구까지 올인원 제공", "전문 크리에이터들의 검증"],
    cons: ["무료 플랜 크레딧 매우 제한적", "비디오 길이 최대 10초(Gen-3)"],
    pricing: { free: "125 크레딧 1회 제공", paid: "Standard $15/월(625크레딧), Pro $35/월(2250크레딧)" },
    useCases: ["단편 영화·광고 영상 제작", "뮤직비디오 비주얼", "소셜 미디어 숏폼 콘텐츠", "제품 데모 영상", "영화 특수효과 프리비즈"],
    pricingPlans: [{name:"Free",price:"무료",features:["125 크레딧/월","Gen-2","720p"],recommended:true},{name:"Standard",price:"$15/월",features:["625 크레딧","Gen-3","1080p"]},{name:"Pro",price:"$35/월",features:["2,250 크레딧","Gen-3 무제한","4K"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/runway-1.png","https://ai.ktoolu.com/screenshots/runway-2.png"],
    expertRating:{accuracy:3.8,easeOfUse:4.0,features:4.5,performance:4.3,value:3.9,innovation:4.6},
    whoIsFor:["영상 크리에이터","광고 제작사","아티스트"],
    communityReviewSummary: {
      overall: "Runway는 AI 비디오 생성 및 편집의 선두주자로 한국 크리에이터들 사이에서 주목받고 있습니다. Gen-3 Alpha 모델의 비디오 퀄리티가 특히 높은 평가를 받고 있습니다.",
      pros: [{keyword:"비디오 품질",content:"Gen-3 Alpha 모델의 사실적인 영상 생성. 텍스트-비디오 품질 업계 최고 수준"}, {keyword:"다양한 기능",content:"인페인팅, 모션 브러시, 슬로우모션 등 편집 기능 풍부"}],
      cons: [{keyword:"가격",content:"무료 크레딧 제한적. 유료 플랜($15~$35) 부담"}, {keyword:"한국어",content:"한국어 프롬프트 지원 제한적"}],
      sources: [
        {name:"네이버 블로그",title:"Runway AI 영상 생성 사용 후기",excerpt:"Gen-3 Alpha 영상 퀄리티에 감탄. 텍스트로 영상을 만드는 시대가 왔음."},
        {name:"dropshot.io",title:"Runway ML 리뷰 및 기능 분석",excerpt:"AI 비디오 편집 도구로 크리에이터에게 필수적인 기능들 제공."},
      ],
    },
  },
  {
    id: "sora",
    name: "Sora",
    description: "OpenAI의 혁신적인 텍스트→비디오 AI. 최대 60초의 놀라운 사실적 영상을 생성합니다.",
    longDescription: "Sora는 OpenAI가 2024년 출시한 텍스트→비디오 생성 AI로, 물리 법칙을 이해하고 현실적인 장면을 구현하는 능력이 업계를 놀라게 했습니다. 텍스트 설명만으로 최대 1080p, 60초 길이의 고품질 영상을 생성할 수 있으며, 동일한 장면을 다양한 카메라 각도로 표현하거나 이미지를 영상으로 변환하는 기능도 제공합니다. ChatGPT Plus 구독자는 Sora를 바로 사용할 수 있어 접근성이 높습니다.",
    url: "https://sora.com",
    category: "video",
    tags: ["텍스트→비디오", "OpenAI", "고품질", "사실적"],
    free: false,
    popular: true,
    features: ["최대 60초 영상 생성", "1080p 고해상도 지원", "이미지→영상 변환", "다양한 화면 비율", "스토리보드 기능"],
    pros: ["물리적 사실성이 업계 최고 수준", "ChatGPT 연동으로 접근성 높음", "긴 영상 생성 가능"],
    cons: ["유료 구독 필요", "생성 속도가 느릴 수 있음", "일부 복잡한 동작 구현 한계"],
    pricing: { paid: "ChatGPT Plus $20/월 포함, Pro $200/월 — 무제한 생성" },
    useCases: ["광고·마케팅 영상 프로토타입", "영화 콘셉트 영상", "교육·강의 자료 영상화", "SNS 바이럴 콘텐츠", "스토리보드 시각화"],
    pricingPlans: [{name:"ChatGPT Plus",price:"$20/월",features:["Sora 기본","최대 20초","1080p"],recommended:true},{name:"ChatGPT Pro",price:"$200/월",features:["Sora 무제한","최대 60초","4K"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/sora-1.png","https://ai.ktoolu.com/screenshots/sora-2.png"],
    expertRating:{accuracy:4.2,easeOfUse:4.1,features:4.0,performance:4.7,value:3.8,innovation:4.9},
    whoIsFor:["영화·광고 제작자","크리에이터","OpenAI 사용자"],
    communityReviewSummary: {
      overall: "Sora는 OpenAI의 텍스트-비디오 AI로 한국 사용자들에게 큰 기대를 받고 있으나 아직 일반에 완전히 공개되지 않아 실사용 후기는 제한적입니다. 테크 블로그와 나무위키를 중심으로 정보가 공유되고 있습니다.",
      pros: [{keyword:"혁신성",content:"텍스트만으로 최대 60초 고품질 영상 생성. 물리 법칙을 이해한 듯한 자연스러운 움직임"}, {keyword:"퀄리티",content:"경쟁사 대비 압도적인 영상 품질과 사실성"}],
      cons: [{keyword:"접근성",content:"아직 일반에 완전 공개되지 않아 사용 제한적. ChatGPT Pro($200) 필요"}, {keyword:"비용",content:"Pro 요금제 없이 접근 불가, 개인 사용자에게 높은 진입 장벽"}],
      sources: [
        {name:"테크뷰",title:"Sora AI 영상 생성 실제 사용 후기",excerpt:"텍스트만으로 영상 생성. 물리 법칙을 이해한 듯한 움직임이 인상적."},
        {name:"벨로그",title:"Sora AI 생성 영상 모음과 사용법",excerpt:"OpenAI의 비디오 생성 모델 Sora의 주요 기능과 생성 영상 예시 정리."},
      ],
    },
  },
  {
    id: "pika",
    name: "Pika",
    description: "텍스트와 이미지로 비디오를 생성하는 AI. 쉬운 인터페이스로 빠르게 애니메이션을 만들 수 있습니다.",
    longDescription: "Pika는 사용자 친화적인 인터페이스로 빠르게 인기를 얻은 AI 비디오 생성 플랫폼입니다. 텍스트 설명이나 이미지를 입력하면 3~4초 만에 영상을 생성해주는 속도가 큰 장점입니다. 립싱크 기능으로 인물 사진에 음성을 입히거나, 기존 영상에 새로운 요소를 추가하는 편집 기능도 제공합니다. 디스코드와 웹 모두에서 사용 가능하며, 무료 플랜으로도 충분한 양의 영상을 생성할 수 있어 처음 AI 비디오를 경험하는 사람에게 적합합니다.",
    url: "https://pika.art",
    category: "video",
    tags: ["애니메이션", "이미지→비디오", "빠른 생성"],
    free: true,
    features: ["빠른 영상 생성(3~4초)", "이미지→비디오 변환", "립싱크 기능", "영상 편집 및 요소 추가", "다양한 비율 지원"],
    pros: ["생성 속도가 빠름", "무료 플랜이 충분히 넉넉함", "초보자도 쉽게 사용"],
    cons: ["영상 품질은 Runway·Sora보다 낮음", "최대 영상 길이 제한"],
    pricing: { free: "월 150크레딧 무료", paid: "Basic $8/월, Standard $28/월, Unlimited $58/월" },
    useCases: ["SNS 릴스·쇼츠 제작", "제품 애니메이션 광고", "사진 살아있게 만들기", "간단한 바이럴 영상", "스토리텔링 영상"],
    pricingPlans: [{name:"Free",price:"무료",features:["250 크레딧/월","기본","워터마크"],recommended:true},{name:"Standard",price:"$10/월",features:["700 크레딧","720p","워터마크 제거"]},{name:"Pro",price:"$30/월",features:["2,000 크레딧","1080p","우선 처리"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/pika-1.png","https://ai.ktoolu.com/screenshots/pika-2.png"],
    expertRating:{accuracy:3.6,easeOfUse:4.4,features:4.1,performance:3.9,value:4.3,innovation:4.2},
    whoIsFor:["초보 크리에이터","SNS 제작자"],
    communityReviewSummary:{overall:"Pika는 텍스트와 이미지로 비디오를 생성하는 AI 도구로, 쉬운 인터페이스와 빠른 생성 속도가 강점입니다.",pros:[{keyword:"쉬운 사용",content:"직관적인 인터페이스. 초보자도 바로 사용 가능"}, {keyword:"빠른 생성",content:"짧은 프롬프트로 빠르게 영상 생성. 소셜 미디어 콘텐츠에 적합"}],cons:[{keyword:"영상 길이",content:"생성 가능한 영상 길이가 경쟁사 대비 짧음"}, {keyword:"퀄리티",content:"Runway·Sora 대비 영상 퀄리티 차이"}],sources:[{name:"크리에이터 리뷰",title:"Pika AI 비디오 생성 후기",excerpt:"쉬운 사용법이 가장 큰 장점. SNS 콘텐츠 만들기에 최적."}]},
  },
  {
    id: "heygen",
    name: "HeyGen",
    description: "AI 아바타로 마케팅 비디오를 생성하는 플랫폼. 100개 이상의 언어로 비디오 번역도 지원합니다.",
    longDescription: "HeyGen은 AI 아바타와 음성 합성 기술을 결합해 카메라 없이도 전문적인 발표 영상을 만들 수 있는 플랫폼입니다. 100가지 이상의 AI 아바타 중 선택하거나 본인 얼굴로 개인 아바타를 만들 수 있습니다. 가장 주목받는 기능은 '영상 번역'으로, 기존 영상을 업로드하면 입 모양까지 맞춰가며 100개 이상의 언어로 자동 더빙해줍니다. 온보딩 영상, 제품 설명, 교육 자료 등 반복 제작이 필요한 기업 영상에 특히 효과적입니다.",
    url: "https://www.heygen.com",
    category: "video",
    tags: ["AI 아바타", "비디오 번역", "마케팅", "다국어"],
    free: true,
    features: ["100+ AI 아바타", "개인 맞춤 아바타 생성", "100+ 언어 자동 번역·더빙", "텍스트→영상 생성", "팀 협업 기능"],
    pros: ["카메라 없이 전문 발표 영상 제작", "다국어 번역 더빙 기능이 뛰어남", "기업 영상 제작 비용 절감"],
    cons: ["무료 플랜은 워터마크 포함", "AI 아바타가 부자연스러울 수 있음"],
    pricing: { free: "1크레딧(1분 영상) 무료 체험", paid: "Creator $29/월, Business $89/월" },
    useCases: ["제품 소개 영상", "온보딩 트레이닝 자료", "다국어 마케팅 영상", "유튜브 콘텐츠 현지화", "e-Learning 강의"],
    pricingPlans: [{name:"Free",price:"무료",features:["1분/월","기본 아바타","워터마크"],recommended:true},{name:"Starter",price:"$24/월",features:["15분/월","HD 아바타","워터마크 제거"]},{name:"Business",price:"$49/월",features:["30분/월","4K 아바타","다국어 번역"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/heygen-1.png","https://ai.ktoolu.com/screenshots/heygen-2.png"],
    expertRating:{accuracy:4.0,easeOfUse:4.2,features:4.3,performance:4.1,value:4.0,innovation:4.2},
    whoIsFor:["마케터","교육자","기업"],
    communityReviewSummary:{overall:"HeyGen은 AI 아바타 기반 마케팅 비디오 생성 플랫폼으로, 한국 기업 교육·마케팅 부문에서 활용도가 높습니다.",pros:[{keyword:"AI 아바타",content:"실제 같은 AI 아바타로 전문적인 영상 제작. 다국어 지원"}, {keyword:"다국어 번역",content:"100개 이상 언어로 영상 자동 번역. 글로벌 마케팅에 최적"}],cons:[{keyword:"가격",content:"무료 1분/월 제한. 유료 플랜($24~$49) 부담"}, {keyword:"아바타 자연스러움",content:"완전히 자연스럽지 않은 아바타 표정과 제스처"}],sources:[{name:"마케터 리뷰",title:"HeyGen AI 아바타 영상 활용",excerpt:"AI 아바타로 마케팅 영상 제작. 다국어 버전도 자동 생성."}]},
  },
  {
    id: "synthesia",
    name: "Synthesia",
    description: "AI 아바타 기반 기업용 비디오 제작 플랫폼. 텍스트만으로 전문적인 트레이닝 영상을 만듭니다.",
    longDescription: "Synthesia는 Fortune 500 기업들이 사용하는 엔터프라이즈급 AI 영상 제작 플랫폼입니다. 230개 이상의 AI 아바타와 140개 이상의 언어를 지원하며, 스크립트만 입력하면 전문 발표자가 등장하는 영상을 자동으로 생성합니다. 엄격한 보안 정책과 GDPR 준수로 기업 환경에 적합하며, LMS(학습 관리 시스템) 연동, SCORM 내보내기 등 기업 교육 도구와의 통합을 지원합니다. BBC, Reuters, Zoom 등 주요 기업들이 사용하고 있습니다.",
    url: "https://www.synthesia.io",
    category: "video",
    tags: ["기업용", "AI 아바타", "트레이닝 영상", "다국어"],
    free: false,
    features: ["230+ 다양한 AI 아바타", "140+ 언어 지원", "LMS 연동 및 SCORM 내보내기", "엔터프라이즈 보안", "브랜드 커스터마이징"],
    pros: ["기업 환경에 최적화된 보안·관리", "가장 자연스러운 AI 아바타", "LMS 통합으로 교육 시스템과 연동"],
    cons: ["가격이 높음", "개인 사용자보다 기업 대상"],
    pricing: { paid: "Starter $22/월(10분), Creator $67/월(30분), Enterprise 별도 문의" },
    useCases: ["직원 온보딩·교육 영상", "규정 준수 트레이닝", "제품 튜토리얼", "글로벌 기업 커뮤니케이션", "e-Learning 콘텐츠"],
    pricingPlans: [{name:"Starter",price:"$29/월",features:["10분/월","1개 아바타","120+ 언어"],recommended:true},{name:"Creator",price:"$89/월",features:["30분/월","5개 아바타","맞춤 아바타"]},{name:"Enterprise",price:"문의",features:["무제한","무제한 아바타","SSO"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/synthesia-1.png","https://ai.ktoolu.com/screenshots/synthesia-2.png"],
    expertRating:{accuracy:4.1,easeOfUse:4.3,features:4.4,performance:4.2,value:3.7,innovation:4.0},
    whoIsFor:["기업 교육팀","마케팅","HR"],
    communityReviewSummary: {
      overall: "Synthesia는 AI 아바타 영상 제작 분야에서 한국 기업 사용자들에게 주목받고 있습니다. 230개 이상의 아바타와 140개 언어 지원이 강점입니다.",
      pros: [{keyword:"AI 아바타",content:"230개 이상의 실제 같은 AI 아바타. 텍스트만 입력하면 영상 완성"}, {keyword:"다국어",content:"140개 이상 언어 지원. 하나의 영상으로 다국어 콘텐츠 제작"}],
      cons: [{keyword:"가격",content:"Starter $29/월, Creator $89/월. 개인 사용자에게 높은 진입 장벽"}, {keyword:"자연스러움",content:"아바타의 표정과 제스처가 완전히 자연스럽지는 않음"}],
      sources: [
        {name:"네이버 블로그",title:"Synthesia AI 아바타 영상 제작 후기",excerpt:"교육용 영상을 AI 아바타로 제작. 스크립트만 있으면 전문 강의 영상 완성."},
        {name:"네이버 블로그",title:"Synthesia로 만든 영상 실제 사용 후기",excerpt:"처음엔 어색했지만 업무용 영상으로 충분. 시간과 비용 절감 효과."},
      ],
    },
  },

  {
    id: "capcut",
    name: "CapCut",
    description: "ByteDance의 올인원 비디오 편집 앱. AI 기능이 내장되어 전 세계 10억+ 사용자를 보유했습니다.",
    longDescription: "CapCut(캡컷)은 TikTok 개발사 ByteDance가 만든 무료 비디오 편집 및 AI 크리에이티브 도구입니다. AI 자동 자막, 배경 제거, 텍스트-비디오 생성 등 강력한 AI 기능이 내장되어 있으며, 초보자도 직관적으로 사용할 수 있습니다. 웹 버전과 모바일 앱 모두 제공되며, AI가 영상을 자동으로 편집해주는 AutoCut 기능으로 편집 시간을 획기적으로 줄여줍니다. 폰트, 효과, 템플릿 등 풍부한 리소스 라이브러리를 무료로 제공합니다.",
    url: "https://www.capcut.com",
    category: "video",
    tags: ["비디오 편집", "무료", "AI 자막", "ByteDance"],
    free: true,
    popular: true,
    features: ["AI 자동 자막 생성", "AI 배경 제거", "텍스트-비디오", "AutoCut 자동 편집", "풍부한 템플릿"],
    pros: ["완전 무료", "직관적 인터페이스", "AI 기능 풍부", "모바일-웹 모두 지원"],
    cons: ["고급 편집 기능 제한적", "중국 기반 프라이버시 우려"],
    useCases: ["SNS 숏폼 영상", "유튜브 콘텐츠", "자동 자막 생성", "마케팅 영상", "교육 콘텐츠"],
    pricingPlans: [{name:"Free",price:"무료",features:["모든 편집","AI 자막","템플릿 무제한","720p"],recommended:true},{name:"Pro",price:"$7.99/월",features:["AI 우선","4K","스톡 라이브러리"]}],
    comparisonNotes:"무료로 충분.",
    screenshots:["https://ai.ktoolu.com/screenshots/capcut-1.png","https://ai.ktoolu.com/screenshots/capcut-2.png"],
    expertRating:{accuracy:3.5,easeOfUse:4.7,features:4.3,performance:4.0,value:4.9,innovation:4.1},
    whoIsFor:["TikTok 크리에이터","유튜버","일반 사용자"],
    communityReviewSummary: {
      overall: "CapCut은 무료 AI 비디오 편집 도구로 한국 사용자들에게 폭발적인 인기를 끌고 있습니다. 특히 AI 자동 자막 기능과 풍부한 템플릿이 큰 장점입니다.",
      pros: [{keyword:"완전 무료",content:"고급 AI 기능까지 모두 무료. 자동 자막, 배경 제거 등"}, {keyword:"쉬운 사용",content:"초보자도 직관적으로 사용 가능. 풍부한 템플릿과 효과"}],
      cons: [{keyword:"중국 기반",content:"ByteDance(틱톡) 제품. 데이터 프라이버시 우려"}, {keyword:"고급 편집",content:"전문 편집 프로그램 대비 세밀한 제어 제한적"}],
      sources: [
        {name:"네이버 블로그",title:"CapCut 사용법과 ai 기능 실제 후기",excerpt:"AI 자동 자막이 정확도 높고 무료. 숏폼 영상 제작에 최적."},
        {name:"네이버 블로그",title:"캡컷 PC 설치부터 편집까지",excerpt:"무료인데 기능이 많아서 놀랐다. 초보자도 쉽게 사용 가능."},
      ],
    },
  },
  {
    id: "seedance",
    name: "Seedance 2.0",
    description: "차세대 AI 비디오 생성 도구. 자연스러운 모션과 뛰어난 시간적 일관성을 제공합니다.",
    longDescription: "Seedance 2.0은 고품질 AI 비디오 생성에 특화된 도구로, 자연스러운 모션과 뛰어난 시간적 일관성이 핵심 강점입니다. 텍스트나 이미지를 입력하면 부드럽고 사실적인 영상을 생성하며, 캐릭터의 일관된 외형 유지 능력이 뛰어납니다. 긴 영상 생성도 지원하며, 다양한 스타일과 종횡비를 제공합니다. 찾는 사람들이 많아지는 차세대 AI 비디오 도구로 주목받고 있습니다.",
    url: "https://www.seedance.com",
    category: "video",
    tags: ["비디오 생성", "모션", "AI 영상", "크리에이티브"],
    free: false,
    popular: false,
    features: ["자연스러운 모션 생성", "시간적 일관성 유지", "긴 영상 생성", "다양한 스타일"],
    pros: ["부드러운 모션 퀄리티", "캐릭터 일관성 우수", "사용자 피드백 반영 빠름"],
    cons: ["유료 서비스", "생성 시간 다소 김"],
    useCases: ["광고 영상", "SNS 콘텐츠", "예술적 영상", "마케팅 비디오"],
    pricingPlans: [{name:"Starter",price:"$15/월",features:["50 크레딧/월","720p","기본 모션"],recommended:true},{name:"Pro",price:"$39/월",features:["200 크레딧/월","1080p","고급 모션"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/seedance-1.png","https://ai.ktoolu.com/screenshots/seedance-2.png"],
    expertRating:{accuracy:3.9,easeOfUse:4.0,features:3.8,performance:4.3,value:3.8,innovation:4.5},
    whoIsFor:["비디오 크리에이터","광고 제작"],
    communityReviewSummary:{overall:"Seedance 2.0은 차세대 AI 비디오 생성 도구로, 자연스러운 모션과 시간적 일관성이 핵심 강점입니다.",pros:[{keyword:"모션 퀄리티",content:"자연스럽고 부드러운 모션. 타 AI 대비 시간적 일관성 우수"}, {keyword:"캐릭터 일관성",content:"여러 장면에서 동일 캐릭터 외형 유지 가능"}],cons:[{keyword:"유료",content:"무료 사용량 제한. 고급 기능은 유료 플랜 필요"}, {keyword:"초기 단계",content:"아직 발전 중인 도구. 사용자 커뮤니티와 자료 부족"}],sources:[{name:"얼리어답터 리뷰",title:"Seedance 2.0 AI 영상 생성",excerpt:"모션 퀄리티가 뛰어나고 시간적 일관성이 좋음. 차세대 AI 영상 기대."}]},
  },    // === CODING ===
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description: "GitHub과 OpenAI가 개발한 AI 코딩 어시스턴트. VS Code에서 실시간 코드 제안과 자동 완성을 제공합니다.",
    longDescription: "GitHub Copilot은 GitHub과 OpenAI가 공동 개발한 AI 코딩 어시스턴트로, 전 세계 개발자들이 가장 많이 사용하는 AI 코딩 도구입니다. VS Code, JetBrains, Neovim 등 주요 에디터에서 실시간 코드 자동 완성, 함수 생성, 주석→코드 변환을 지원합니다. Copilot Chat은 코드에 대한 질문, 설명, 리팩토링 제안을 대화 형식으로 제공합니다. GitHub 저장소의 방대한 코드를 학습해 다양한 언어와 프레임워크에서 높은 정확도를 보여주며, 개발 생산성을 평균 55% 향상시킨다는 연구 결과가 있습니다.",
    url: "https://github.com/features/copilot",
    category: "coding",
    tags: ["VS Code", "자동 완성", "GitHub 통합", "페어 프로그래밍"],
    free: false,
    popular: true,
    features: ["실시간 코드 자동 완성", "함수·클래스 전체 생성", "Copilot Chat 대화형 보조", "테스트 코드 자동 생성", "보안 취약점 감지"],
    pros: ["가장 널리 사용되는 코딩 AI", "다양한 에디터 지원", "GitHub 워크플로우와 완벽 통합"],
    cons: ["유료(학생·오픈소스는 무료)", "인터넷 연결 필수", "간혹 부정확한 코드 제안"],
    pricing: { free: "학생·인증 오픈소스 기여자 무료", paid: "Individual $10/월, Business $19/월/인" },
    useCases: ["반복적인 코드 패턴 자동화", "새로운 언어·프레임워크 빠른 학습", "단위 테스트 자동 생성", "코드 리뷰 및 리팩토링", "API 연동 코드 작성"],
    pricingPlans: [{name:"Free",price:"무료",features:["2,000 완성/월","50 채팅/월","VS Code"],recommended:true},{name:"Individual",price:"$10/월",features:["무제한 완성","무제한 채팅","Copilot Voice"]},{name:"Business",price:"$19/인/월",features:["Individual 전체","정책 관리","감사 로그"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/gh-copilot-1.png","https://ai.ktoolu.com/screenshots/gh-copilot-2.png"],
    expertRating:{accuracy:4.2,easeOfUse:4.6,features:4.3,performance:4.4,value:4.5,innovation:4.1},
    whoIsFor:["모든 개발자","기업 개발팀","학생"],
    communityReviewSummary: {
      overall: "한국 개발자들은 GitHub Copilot을 'AI 페어 프로그래머'로 평가합니다. 네이버 블로그, 다음 검색 등에서 수집한 리뷰에 따르면, 반복 코드 자동 완성과 생산성 향상이 가장 큰 장점입니다. VS Code와의 통합이 뛰어나며, Ctrl+I 인라인 채팅으로 편리하게 사용할 수 있습니다. 학생과 오픈소스 기여자는 무료로 사용 가능합니다. 다만 Cursor, Windsurf 등 AI IDE의 등장으로 경쟁이 치열해지고 있습니다.",
      pros: [
        { keyword: "생산성 향상", content: "반복 코드 자동 완성, 코드 제안, AI와 페어 프로그래밍으로 개발 속도 혁신" },
        { keyword: "IDE 통합", content: "VS Code, JetBrains 등 주요 IDE와 완벽 통합. Ctrl+I 인라인 채팅 편리" },
        { keyword: "무료 혜택", content: "학생과 오픈소스 기여자는 Copilot Pro를 무료로 사용 가능" },
      ],
      cons: [
        { keyword: "경쟁 심화", content: "Cursor, Windsurf 등 AI 네이티브 IDE의 등장으로 Copilot의 차별성 약화" },
        { keyword: "유료 정책", content: "무료 사용량 제한과 유료 전환 정책 변화가 사용자에게 부담" },
        { keyword: "코드 품질", content: "생성된 코드의 검증 없이 사용하면 보안 취약점이나 버그가 포함될 수 있음" },
      ],
      sources: [
        { name: "다음 검색", title: "GitHub Copilot 처음 써본 후기", excerpt: "반신반의했는데 반복 코드 자동 완성에서 확실히 생산성 향상." },
        { name: "네이버 뷰", title: "Cursor AI vs GitHub Copilot 비교", excerpt: "Copilot은 기성 IDE에서 플러그인 방식, Cursor는 AI 네이티브 IDE. 선택지는 많아짐." },
        { name: "네이버 블로그", title: "GitHub Copilot - AI 페어 프로그래머", excerpt: "수억 라인 public 코드로 훈련. 학생과 오픈소스 담당자 무료." },
        { name: "다음 검색", title: "현업 개발자의 GitHub Copilot 사용 후기", excerpt: "Copilot은 생산성, ChatGPT는 사고의 폭. 둘 다 쓰면 창의적인 기획자 가능." },
        { name: "네이버 뷰", title: "GitHub Copilot 부트캠프 참가 후기", excerpt: "90명 개발자 바이브 코딩 행사. AI 코딩 도구 활용법 익히는 게 중요." },
      ],
    },
  },
  {
    id: "cursor",
    name: "Cursor",
    description: "AI 네이티브 코드 에디터. Claude, GPT-4 기반으로 코드베이스 전체를 이해하고 편집합니다.",
    longDescription: "Cursor는 VS Code를 기반으로 만들어진 AI 네이티브 코드 에디터입니다. 단순한 자동 완성을 넘어, 프로젝트 전체 코드베이스를 분석해 문맥을 이해한 수정을 제안합니다. 'Cmd+K'로 자연어로 코드 편집을 지시하고, 'Composer' 기능으로 여러 파일에 걸친 복잡한 변경 사항을 한 번에 처리할 수 있습니다. Claude Sonnet, GPT-4o, Gemini 등 최신 AI 모델을 선택해 사용할 수 있으며, 코드베이스 검색·참조 기능으로 대규모 프로젝트에서도 정확한 제안을 제공합니다.",
    url: "https://cursor.sh",
    category: "coding",
    tags: ["AI 에디터", "코드베이스 분석", "자동 편집", "Claude"],
    free: true,
    popular: true,
    features: ["코드베이스 전체 컨텍스트 이해", "자연어로 코드 편집 지시", "멀티파일 Composer 편집", "여러 AI 모델 선택", "터미널 AI 보조"],
    pros: ["코드베이스 전체를 이해한 정확한 수정", "VS Code 익스텐션 그대로 사용 가능", "강력한 멀티파일 편집"],
    cons: ["코드를 외부 서버로 전송(프라이버시)", "무료 플랜은 사용량 제한"],
    pricing: { free: "2주 Pro 체험 후 기본 무료(제한적)", paid: "Pro $20/월 — 500 fast 요청, 무제한 slow 요청" },
    useCases: ["레거시 코드 리팩토링", "새 기능 빠른 개발", "버그 디버깅 자동화", "코드 문서화", "프로젝트 전체 구조 파악"],
    pricingPlans: [{name:"Free",price:"무료",features:["2,000 완성/월","50 프리미엄","VS Code 호환"],recommended:true},{name:"Pro",price:"$20/월",features:["무제한 완성","500 프리미엄","Claude·GPT"]},{name:"Business",price:"$40/인/월",features:["Pro 전체","중앙 관리","팀 정책"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/cursor-1.png","https://ai.ktoolu.com/screenshots/cursor-2.png"],
    expertRating:{accuracy:4.3,easeOfUse:4.4,features:4.5,performance:4.5,value:4.2,innovation:4.6},
    whoIsFor:["개발자","프리랜서","스타트업"],
    communityReviewSummary: {
      overall: "한국 개발자들은 Cursor를 'AI 네이티브 IDE의 혁신'으로 평가합니다. 네이버 블로그 리뷰에 따르면, 단순한 코드 완성을 넘어 프로젝트 구조 전체를 이해하고 편집하는 능력이 가장 큰 강점입니다. ChatGPT, Claude 등 생성형 AI를 활용해 코드를 작성하는 것이 자연스러워진 개발자들 사이에서 주목받고 있습니다.",
      pros: [
        { keyword: "AI 네이티브", content: "VS Code 기반이지만 AI가 IDE 전체에 깊게 통합. 프로젝트 구조를 이해하고 편집" },
        { keyword: "생산성 혁신", content: "코드를 치는 게 아니라 지시하는 방식으로 변경. 복잡한 프로젝트 파악 시간 단축" },
      ],
      cons: [
        { keyword: "비용", content: "무료 버전 제한적, Pro $20/월은 개인에게 부담" },
        { keyword: "의존성", content: "AI에 너무 의존하면 기본 코딩 능력 유지에 문제" },
      ],
      sources: [
        { name: "네이버 블로그", title: "이제 코딩은 치는 게 아니라 지시하는 것? Cursor AI 에디터 사용 후기", excerpt: "단순 오타 수정이 아닌, 코드 한 줄 짜는 게 고통스러운 개발자에게 추천." },
        { name: "네이버 블로그", title: "AI가 직접 코드를 수정해준다? Cursor AI 핵심 기능 총정리", excerpt: "ChatGPT·Claude 활용이 자연스러워진 지금, Cursor가 개발자 사이에서 주목." },
      ],
    },
  },
  {
    id: "v0",
    name: "v0 by Vercel",
    description: "텍스트 설명으로 React UI 컴포넌트를 생성하는 AI. shadcn/ui 기반의 코드를 즉시 생성합니다.",
    longDescription: "v0는 Vercel이 만든 AI UI 생성 도구로, 텍스트로 원하는 UI를 설명하면 즉시 React 컴포넌트 코드를 생성합니다. shadcn/ui, Tailwind CSS 기반의 깔끔하고 실제로 사용 가능한 코드를 생성하며, 생성된 컴포넌트를 채팅으로 수정하거나 Next.js 프로젝트에 바로 붙여넣을 수 있습니다. 디자인 목업 이미지를 업로드하면 그에 맞는 코드를 생성하는 기능도 있어 디자이너와 개발자 사이의 핸드오프를 가속화합니다.",
    url: "https://v0.dev",
    category: "coding",
    tags: ["UI 생성", "React", "shadcn/ui", "Vercel"],
    free: true,
    popular: true,
    features: ["텍스트→React 컴포넌트 생성", "shadcn/ui·Tailwind 기반", "이미지→코드 변환", "대화형 수정", "Next.js 직접 배포"],
    pros: ["프론트엔드 개발 속도 대폭 향상", "실제 사용 가능한 코드 품질", "Vercel 배포와 완벽 연동"],
    cons: ["React·Next.js 특화(다른 프레임워크 한계)", "복잡한 비즈니스 로직은 직접 작성 필요"],
    pricing: { free: "월 200크레딧 무료", paid: "Premium $20/월 — 5000크레딧, 우선 처리" },
    useCases: ["랜딩 페이지 빠른 프로토타입", "대시보드 UI 생성", "폼·테이블 컴포넌트 제작", "디자인 목업 코드화", "UI 컴포넌트 라이브러리 구축"],
    pricingPlans: [{name:"Free",price:"무료",features:["200 생성/월","기본 UI","shadcn/ui"],recommended:true},{name:"Pro",price:"$20/월",features:["무제한 생성","커스텀 디자인","API"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/v0-1.png","https://ai.ktoolu.com/screenshots/v0-2.png"],
    expertRating:{accuracy:4.0,easeOfUse:4.5,features:4.1,performance:4.2,value:4.3,innovation:4.4},
    whoIsFor:["프론트엔드 개발자","프로덕트 디자이너","노코더"],
    communityReviewSummary:{overall:"v0 by Vercel은 텍스트 설명으로 React UI 컴포넌트를 생성하는 AI 도구로, 프론트엔드 개발자들 사이에서 인기가 높습니다.",pros:[{keyword:"UI 생성",content:"텍스트로 React UI 컴포넌트 즉시 생성. shadcn/ui 기반 코드"}, {keyword:"생산성",content:"프로토타입 제작 시간 획기적 단축. 반복적인 UI 작업 자동화"}],cons:[{keyword:"React 한정",content:"Vue·Svelte 등 다른 프레임워크 미지원"}, {keyword:"무료 제한",content:"무료 200생성/월 제한. 전문 사용은 Pro($20) 필요"}],sources:[{name:"프론트엔드 리뷰",title:"v0 by Vercel 실사용 후기",excerpt:"UI 프로토타입 제작에 혁명. 텍스트로 원하는 UI를 바로 생성."}]},
  },
  {
    id: "bolt",
    name: "Bolt.new",
    description: "브라우저에서 풀스택 앱을 빠르게 프로토타이핑하는 AI 개발 도구. StackBlitz 기반으로 실행됩니다.",
    longDescription: "Bolt.new는 StackBlitz가 만든 브라우저 기반 AI 풀스택 개발 도구입니다. 자연어로 앱 아이디어를 설명하면 프론트엔드부터 백엔드, 데이터베이스 설정까지 완전한 풀스택 앱을 생성합니다. 브라우저 안에서 직접 코드를 실행하고 수정할 수 있어 로컬 환경 설정이 전혀 필요 없습니다. React, Vue, Svelte, Next.js, Remix 등 다양한 프레임워크를 지원하며, npm 패키지도 브라우저에서 바로 설치해 사용할 수 있습니다.",
    url: "https://bolt.new",
    category: "coding",
    tags: ["풀스택", "프로토타이핑", "StackBlitz", "브라우저 IDE"],
    free: true,
    features: ["브라우저에서 풀스택 앱 실행", "자연어로 앱 생성", "다양한 프레임워크 지원", "npm 패키지 즉시 설치", "Netlify·Vercel 원클릭 배포"],
    pros: ["로컬 환경 설정 불필요", "아이디어→실행 가능한 앱 속도 빠름", "초보자도 풀스택 개발 가능"],
    cons: ["복잡한 대규모 앱 개발에는 한계", "무료 플랜 토큰 제한"],
    pricing: { free: "일정 토큰 무료", paid: "Basic $20/월, Pro $50/월" },
    useCases: ["스타트업 MVP 빠른 프로토타입", "해커톤 프로젝트", "클라이언트 데모 앱", "학습용 풀스택 예제", "아이디어 검증용 앱"],
    pricingPlans: [{name:"Free",price:"무료",features:["기본 생성","공개 프로젝트","커뮤니티"],recommended:true},{name:"Pro",price:"$20/월",features:["무제한 생성","비공개 프로젝트","우선 지원"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/bolt-1.png","https://ai.ktoolu.com/screenshots/bolt-2.png"],
    expertRating:{accuracy:3.8,easeOfUse:4.3,features:4.0,performance:3.9,value:4.4,innovation:4.2},
    whoIsFor:["스타트업","개발자","비개발자"],
    communityReviewSummary:{overall:"Bolt.new는 브라우저에서 풀스택 앱을 빠르게 프로토타이핑하는 AI 개발 도구입니다.",pros:[{keyword:"풀스택",content:"브라우저에서 프론트엔드·백엔드 동시 개발. StackBlitz 기반 실행"}, {keyword:"빠른 프로토타입",content:"아이디어를 즉시 실행 가능한 앱으로. 개발 시간 획기적 단축"}],cons:[{keyword:"복잡한 프로젝트",content:"대규모 프로젝트에는 적합하지 않음"}, {keyword:"커스터마이징",content:"기존 코드베이스와의 통합 제한적"}],sources:[{name:"개발자 리뷰",title:"Bolt.new 빠른 프로토타이핑",excerpt:"아이디어를 바로 앱으로 만들어주는 도구. 해커톤에 최적."}]},
  },
      {
    id: "replit-ai",
    name: "Replit AI",
    description: "Replit IDE에 통합된 AI. 코드 생성, 디버깅, 설명을 제공하며 클라우드에서 바로 실행됩니다.",
    longDescription: "Replit AI는 클라우드 기반 IDE Replit에 통합된 AI 개발 도구입니다. 브라우저에서 코드를 작성하고 바로 실행할 수 있어 로컬 환경 설정이 필요 없으며, AI가 코드 생성, 디버깅, 오류 설명, 코드 변환을 도와줍니다. Ghostwriter Complete는 실시간 자동 완성을, Ghostwriter Chat은 대화형 코딩 보조를 제공합니다. 50개 이상의 프로그래밍 언어를 지원하며, 교육 목적으로 많이 사용됩니다. Replit Deployments로 만든 앱을 바로 배포할 수도 있습니다.",
    url: "https://replit.com",
    category: "coding",
    tags: ["클라우드 IDE", "디버깅", "코드 실행", "교육"],
    free: true,
    features: ["클라우드 브라우저 IDE", "AI 코드 생성·디버깅", "50+ 언어 즉시 실행", "원클릭 앱 배포", "실시간 협업"],
    pros: ["환경 설정 없이 즉시 코딩 시작", "교육 환경에 최적화", "앱 개발부터 배포까지 한 곳에서"],
    cons: ["로컬 IDE보다 성능 제한", "AI 기능 대부분 유료", "인터넷 연결 필수"],
    pricing: { free: "기본 IDE 무료(AI 기능 제한)", paid: "Core $20/월 — 전체 AI 기능, 더 많은 컴퓨팅 자원" },
    useCases: ["코딩 교육 및 학습", "빠른 코드 실험·프로토타입", "팀 코딩 인터뷰 연습", "서버 없는 봇·스크립트 실행", "학생 과제 개발"],
    pricingPlans: [{name:"Free",price:"무료",features:["기본 AI","공개 Repl","CPU 제한"],recommended:true},{name:"Core",price:"$20/월",features:["AI 무제한","비공개 Repl","더 많은 리소스"]},{name:"Teams",price:"$40/인/월",features:["Core 전체","팀 공간","중앙 관리"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/replit-1.png","https://ai.ktoolu.com/screenshots/replit-2.png"],
    expertRating:{accuracy:3.7,easeOfUse:4.4,features:4.2,performance:3.8,value:4.3,innovation:4.0},
    whoIsFor:["교육자·학생","취미 개발자","해커톤 참가자"],
    communityReviewSummary:{overall:"Replit AI는 브라우저 기반 IDE에 AI 코딩 어시스턴트를 통합한 도구로, 교육과 취미 코딩에 인기가 높습니다.",pros:[{keyword:"설치 불필요",content:"브라우저만 있으면 즉시 코딩 가능. 환경 설정 불필요"}, {keyword:"AI 통합",content:"코드 생성·디버깅·설명을 AI가 도와줌. 초보자에게 특히 유용"}],cons:[{keyword:"성능",content:"로컬 IDE 대비 실행 속도와 리소스 제한"}, {keyword:"유료 전환",content:"고급 AI 기능과 프라이빗 Repl은 Core($20) 필요"}],sources:[{name:"교육 리뷰",title:"Replit AI 코딩 교육 활용",excerpt:"설치 없이 바로 코딩 교육 가능. AI가 초보자의 코드 작성을 도와줌."}]},
  },


  {
    id: "windsurf",
    name: "Windsurf",
    description: "Codeium이 개발한 AI 네이티브 IDE. Cursor의 강력한 대항마로 주목받고 있습니다.",
    longDescription: "Windsurf는 Codeium(기존 Codeium)이 개발한 AI 네이티브 통합 개발 환경(IDE)입니다. 기존 VS Code 기반 IDE와 달리 AI가 코드 편집 전반에 깊게 통합되어 있어, 개발자의 의도를 이해하고 능동적으로 코드를 제안-완성합니다. AI Flow 패러다임을 도입해 개발자가 코드를 작성할 때 AI가 함께 흐름을 읽으며 다음 동작을 예측합니다. 멀티 파일 편집, 리팩토링, 코드 리뷰 등 고급 기능을 무료로 제공하며 개발자들 사이에서 빠르게 채택되고 있습니다.",
    url: "https://codeium.com/windsurf",
    category: "coding",
    tags: ["AI IDE", "Codeium", "무료", "VS Code 호환"],
    free: true,
    popular: true,
    features: ["AI Flow 패러다임", "멀티 파일 편집", "자동 리팩토링", "코드 리뷰", "무료 사용 가능"],
    pros: ["Cursor 대비 저렴한 가격", "VS Code 확장과 호환", "AI Flow로 생산성 향상"],
    cons: ["Cursor 대비 에이전트 기능 부족", "아직 안정화 진행 중"],
    useCases: ["일상 코딩 작업", "코드 리팩토링", "팀 프로젝트", "풀스택 개발"],
    pricingPlans: [{name:"Free",price:"무료",features:["기본 AI Flow","1,500 완성/월","VS Code 호환"],recommended:true},{name:"Pro",price:"$15/월",features:["AI Flow 무제한","무제한 완성","고급 모델"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/windsurf-1.png","https://ai.ktoolu.com/screenshots/windsurf-2.png"],
    expertRating:{accuracy:4.0,easeOfUse:4.2,features:4.1,performance:4.1,value:4.5,innovation:4.3},
    whoIsFor:["개발자 — Cursor 대안","VS Code 사용자"],
    communityReviewSummary:{overall:"Windsurf는 Cursor의 강력한 경쟁자로 한국 개발자들 사이에서 주목받고 있습니다. 6개월 실사용 후기에 따르면 무료 티어가 압도적이며 Cascade 에이전트 모드가 강력합니다.",pros:[{keyword:"가격 경쟁력",content:"Cursor Pro($20) 대비 Windsurf Pro($15)로 저렴. 무료 티어도 넉넉"},{keyword:"Cascade",content:"AI 에이전트 모드 Cascade가 강력. 코드 생성·디버깅·리팩토링 모두 가능"}],cons:[{keyword:"Cursor 대비 인지도",content:"Cursor에 비해 사용자 커뮤니티와 자료가 적음"},{keyword:"안정화",content:"아직 업데이트가 빠르게 진행 중. 가끔 버그 발생"}],sources:[{name:"네이버 블로그",title:"Windsurf 에디터 6개월 후기 — Cursor의 진짜 경쟁자",excerpt:"Codeium이 만든 AI 통합 IDE. Cursor와 같은 컨셉에 무료 티어가 압도적."},{name:"네이버 블로그",title:"Cursor vs Windsurf 비교 — 6개월 후기",excerpt:"에이전트 코딩: 둘 다 최고 수준. Windsurf가 가격 경쟁력에서 앞섬."}]},
  },
  {
    id: "devin",
    name: "Devin",
    description: "Cognition Labs의 AI 소프트웨어 엔지니어. 독립적으로 코딩하고 버그를 수정합니다.",
    longDescription: "Devin은 Cognition Labs가 개발한 세계 최초의 AI 소프트웨어 엔지니어로, 사람 개발자처럼 독립적으로 코드를 작성하고, 버그를 수정하며, 소프트웨어를 배포합니다. Devin은 자체 터미널, 코드 편집기, 웹 브라우저를 갖추고 있어 복잡한 작업을 스스로 계획-실행할 수 있습니다. 실제 업계 벤치마크(SWE-bench)에서 기존 AI 코딩 도구를 크게 앞지르는 성과를 보여주며 업계에 큰 충격을 주었습니다.",
    url: "https://www.cognition.ai",
    category: "coding",
    tags: ["AI 엔지니어", "자율 코딩", "Cognition", "SWE-bench"],
    free: false,
    popular: true,
    features: ["독립적 작업 계획-실행", "자체 터미널-에디터-브라우저", "버그 수정 및 배포", "SWE-bench 최고 성적"],
    pros: ["완전 자율적 작업 수행", "실제 프로젝트 투입 가능", "기존 도구 대비 압도적 성능"],
    cons: ["기업용으로만 제공", "아직 초기 단계", "고가"],
    useCases: ["버그 수정", "기능 개발", "코드 리팩토링", "배포 자동화"],
    pricingPlans: [{name:"Enterprise",price:"문의",features:["자율 AI 엔지니어","슬랙·GitHub 통합","보안 규정","전담 지원"],recommended:true}],
    screenshots:["https://ai.ktoolu.com/screenshots/devin-1.png","https://ai.ktoolu.com/screenshots/devin-2.png"],
    expertRating:{accuracy:4.4,easeOfUse:3.5,features:4.3,performance:4.6,value:3.3,innovation:4.9},
    whoIsFor:["소프트웨어 기업","CTO·VP Eng"],
    communityReviewSummary:{overall:"Devin은 '세계 최초 AI 소프트웨어 엔지니어'로 한국 개발자들에게 큰 관심을 받고 있습니다. 아직 대기자 명단 방식으로 제한적 사용이 가능하나, SWE-bench 최고 성적으로 잠재력을 인정받고 있습니다.",pros:[{keyword:"자율 코딩",content:"버그 수정·기능 개발을 스스로 계획하고 실행. 실제 프로젝트 투입 가능"},{keyword:"SWE-bench 1위",content:"AI 소프트웨어 엔지니어 벤치마크에서 압도적 1위"}],cons:[{keyword:"접근성",content:"대기자 명단 방식. 아직 일반인 사용 불가"},{keyword:"기업용",content:"주로 기업 대상. 개인 사용자에게 높은 진입 장벽"}],sources:[{name:"네이버 블로그",title:"2026 AI에이전트 도구 TOP5 한 달후기",excerpt:"AutoGPT, Devin, Hermes, Manus 등 비교. Devin은 SWE-bench 최고."},{name:"네이버 블로그",title:"데빈(Devin) 프로그래밍하는 AI",excerpt:"세계 최초 AI SW 엔지니어. 현재 대기자 명단을 통해 제한적 사용 가능."}]},
  },  // === MUSIC ===
  {
    id: "suno",
    name: "Suno AI",
    description: "텍스트 프롬프트만으로 완성된 노래를 만드는 AI. 가사, 멜로디, 보컬까지 자동으로 생성합니다.",
    longDescription: "Suno AI는 텍스트 설명만으로 가사, 멜로디, 보컬, 악기 편성까지 완성된 노래를 생성하는 혁신적인 AI 음악 플랫폼입니다. '밝은 느낌의 K-pop 사랑 노래'처럼 간단한 설명만 입력하면 2분 내외의 완성된 곡을 즉시 만들어냅니다. 팝, 록, 힙합, 클래식, 재즈, 트로트 등 거의 모든 장르를 지원하며, 직접 가사를 작성해 원하는 내용의 노래를 만들 수도 있습니다. 무료 플랜으로도 하루 10곡을 생성할 수 있어 부담 없이 시작할 수 있습니다.",
    url: "https://suno.ai",
    category: "music",
    tags: ["노래 생성", "가사", "보컬", "다양한 장르"],
    free: true,
    popular: true,
    features: ["텍스트→완성 노래 생성", "직접 가사 입력 가능", "다양한 장르·스타일 지원", "2분 이상 노래 생성", "상업적 사용(유료 플랜)"],
    pros: ["음악 지식 없이도 완성된 노래 제작", "한국어 포함 다국어 가사 지원", "무료 플랜도 충분히 활용 가능"],
    cons: ["저작권 및 상업적 사용에 주의 필요(유료 플랜만)", "세밀한 편집 기능 부족"],
    pricing: { free: "하루 50크레딧(약 10곡) 무료", paid: "Pro $8/월 — 하루 2500크레딧, 상업적 사용 허가" },
    useCases: ["개인 취향 맞춤 음악 생성", "유튜브 배경음악", "생일·기념일 맞춤 노래", "광고 징글 제작", "음악 아이디어 스케치"],
    pricingPlans: [{name:"Free",price:"무료",features:["10곡/일","기본 음질","기본 장르"],recommended:true},{name:"Pro",price:"$10/월",features:["500곡/월","고음질","상업 라이선스"]},{name:"Premier",price:"$30/월",features:["2,000곡/월","최고 음질","익스텐드"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/suno-1.png","https://ai.ktoolu.com/screenshots/suno-2.png"],
    expertRating:{accuracy:3.2,easeOfUse:4.3,features:4.4,performance:4.2,value:4.3,innovation:4.7},
    whoIsFor:["음악 크리에이터","콘텐츠 제작자","취미 작곡가"],
    communityReviewSummary: {
      overall: "한국 사용자들은 Suno AI를 'AI 음악 생성의 최강자'로 평가합니다. 네이버 블로그 리뷰에 따르면, 기본 기능만으로도 충분히 높은 퀄리티의 노래를 생성할 수 있으며, Udio와 비교해도 손색없는 수준입니다.",
      pros: [
        { keyword: "쉬운 사용", content: "비전문가도 프롬프트만으로 완성도 높은 노래 생성 가능" },
        { keyword: "퀄리티", content: "무료 버전으로도 충분히 괜찮은 퀄리티. 유료면 더 다양한 기능" },
      ],
      cons: [
        { keyword: "경쟁 심화", content: "Udio 등 경쟁 모델과의 차별성이 점점 줄어듦" },
        { keyword: "한국어 가사", content: "한국어 가사 생성의 자연스러움에서 다소 아쉬움" },
      ],
      sources: [
        { name: "네이버 블로그", title: "노래 뚝딱 만들어주는 수노(SUNO) AI 한 달 사용 후기", excerpt: "나 같은 사람도 뚝딱 노래 한 곡을 만들어낼 수 있는 AI. 유료지만 기본 기능만으로 퀄리티 괜찮음." },
        { name: "네이버 블로그", title: "UDIO vs SUNO AI 작곡 프로그램 사용 후기", excerpt: "UDIO가 SUNO에 비해 아쉽지만 둘 다 수준이 높음. 참 무서운 기술." },
      ],
    },
  },
  {
    id: "udio",
    name: "Udio",
    description: "고품질 음악을 생성하는 AI 플랫폼. 다양한 장르와 스타일의 음악을 쉽게 만들 수 있습니다.",
    longDescription: "Udio는 Google DeepMind 출신 연구진이 설립한 AI 음악 생성 플랫폼으로, 전문 음악가 수준의 음질과 세밀한 스타일 표현이 강점입니다. 장르, 악기, 무드, BPM 등 다양한 파라미터로 음악을 정밀하게 제어할 수 있으며, 생성된 음악을 구간별로 연장하거나 편집하는 기능도 제공합니다. Suno와 함께 AI 음악 생성 시장을 선도하며, 특히 전자음악, 앰비언트, 팝 등의 장르에서 뛰어난 품질을 보여줍니다.",
    url: "https://www.udio.com",
    category: "music",
    tags: ["고품질 음악", "다양한 장르", "음악 생성"],
    free: true,
    popular: true,
    features: ["전문가 수준 음질", "세밀한 파라미터 제어", "음악 구간 연장·편집", "가사 직접 입력", "다양한 장르·스타일"],
    pros: ["음질이 매우 높음", "세밀한 음악 스타일 제어 가능", "무료 플랜 제공"],
    cons: ["Suno보다 인터페이스 복잡", "상업적 사용 정책 확인 필요"],
    pricing: { free: "월 100크레딧 무료", paid: "Standard $10/월, Pro $30/월 — 더 많은 크레딧, 상업적 사용" },
    useCases: ["유튜브·팟캐스트 배경음악", "게임 사운드트랙", "앨범 아이디어 스케치", "음악 프로듀서 작업 보조", "광고 음악 제작"],
    pricingPlans: [{name:"Free",price:"무료",features:["50곡/월","기본 음질","워터마크"],recommended:true},{name:"Standard",price:"$10/월",features:["1,200곡/월","고음질","워터마크 제거"]},{name:"Pro",price:"$30/월",features:["4,000곡/월","익스텐드","상업 라이선스"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/udio-1.png","https://ai.ktoolu.com/screenshots/udio-2.png"],
    expertRating:{accuracy:3.4,easeOfUse:4.2,features:4.1,performance:4.0,value:4.2,innovation:4.3},
    whoIsFor:["음악 프로듀서","인디 뮤지션","게임 개발자"],
    communityReviewSummary: {
      overall: "Udio는 Suno AI와 함께 AI 음악 생성 시장을 양분하는 도구로 평가됩니다. 한국 사용자들은 Udio의 음질과 장르 다양성을 높이 평가하지만, Suno에 비해 한국어 가사 처리에서 다소 아쉽다는 의견이 있습니다.",
      pros: [{keyword:"음질",content:"고품질 오디오 생성, 다양한 장르 지원"}, {keyword:"편집 기능",content:"익스텐드(연장) 기능으로 생성된 음악의 길이 조절 가능"}],
      cons: [{keyword:"한국어",content:"한국어 가사 처리에서 Suno에 비해 다소 부족"}, {keyword:"경쟁",content:"Suno AI 대비 인지도와 사용자 수에서 열세"}],
      sources: [
        {name:"lemonj.kr",title:"AI 음악 생성 도구 Udio 사용 후기",excerpt:"Suno보다 Udio가 음질이 더 좋다는 평가. 다양한 장르 생성 가능."},
        {name:"디시인사이드",title:"Udio 사용해본 후기",excerpt:"AI 음악 퀄리티가 생각보다 높아서 놀람. 장르 선택 폭이 넓음."},
        {name:"큐오넷",title:"Udio AI 음악 생성 사용기",excerpt:"음악 프로듀서 입장에서 본 Udio 평가. 창작 보조 도구로 유용."},
      ],
    },
  },
        // === OTHER ===
  {
    id: "eleven-labs",
    name: "ElevenLabs",
    description: "가장 자연스러운 AI 음성 합성 플랫폼. 음성 클로닝, 텍스트→음성 변환으로 콘텐츠 제작에 혁명을 일으킵니다.",
    longDescription: "ElevenLabs는 현존하는 AI 음성 합성 중 가장 자연스럽고 감성적인 음성을 생성하는 플랫폼입니다. 텍스트를 입력하면 인간과 구분하기 어려운 수준의 음성으로 변환해주며, 단 1분의 목소리 샘플만으로 특정 사람의 음성을 복제하는 '음성 클로닝' 기능이 있습니다. 29개 언어를 지원하며 한국어도 자연스럽게 구현합니다. 유튜버, 팟캐스터, 게임 개발자, 오디오북 제작자 등 콘텐츠 크리에이터들이 제작 비용과 시간을 크게 절감하는 데 활용하고 있습니다.",
    url: "https://elevenlabs.io",
    category: "other",
    tags: ["음성 합성", "음성 클로닝", "TTS", "다국어"],
    free: true,
    popular: true,
    features: ["인간에 가까운 자연스러운 TTS", "음성 클로닝(1분 샘플)", "29개 언어 지원(한국어 포함)", "감정·속도·피치 조절", "API 제공"],
    pros: ["업계 최고 수준의 음성 자연스러움", "한국어 품질 우수", "다양한 목소리 라이브러리"],
    cons: ["무료 플랜 월 10,000자 제한", "음성 클로닝 악용 윤리 우려"],
    pricing: { free: "월 10,000자 무료", paid: "Starter $5/월(30,000자), Creator $22/월(100,000자)" },
    useCases: ["유튜브 내레이션 자동 생성", "오디오북 제작", "팟캐스트 AI 진행자", "게임 NPC 음성", "다국어 콘텐츠 더빙"],
    pricingPlans: [{name:"Free",price:"무료",features:["1만자/월","기본 음성","1개 커스텀"],recommended:true},{name:"Starter",price:"$5/월",features:["3만자/월","고음질","음성 클로닝"]},{name:"Pro",price:"$22/월",features:["10만자/월","프로 음성","API"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/elevenlabs-1.png","https://ai.ktoolu.com/screenshots/elevenlabs-2.png"],
    expertRating:{accuracy:4.5,easeOfUse:4.3,features:4.2,performance:4.6,value:4.0,innovation:4.4},
    whoIsFor:["콘텐츠 크리에이터","개발자 — 음성 API","오디오북 제작자"],
    communityReviewSummary: {
      overall: "한국 사용자들은 ElevenLabs를 'TTS와 음성 복제 분야의 사실상 표준'으로 평가합니다. 한국어를 포함한 30여 개 언어를 지원하며, 감정·강세·휴지가 사람과 매우 가깝습니다.",
      pros: [
        { keyword: "자연스러운 TTS", content: "감정·강세·휴지 표현이 사람과 매우 가까워 업계 표준으로 자리잡음" },
        { keyword: "음성 복제", content: "1~3분 샘플로 본인 목소리 복제 가능. 다국어 음성 지원" },
      ],
      cons: [
        { keyword: "가격", content: "고품질 음성 생성은 유료 플랜 필요. 무료는 1만자 제한" },
        { keyword: "한국어 품질", content: "영어 대비 한국어 음성 자연스러움에서 다소 차이" },
      ],
      sources: [
        { name: "PortalAI", title: "ElevenLabs 리뷰·사용법·가격 정리", excerpt: "TTS와 음성 복제 분야 사실상 표준. 한국어 포함 30여 개 언어 지원. 1~3분 샘플로 목소리 복제." },
      ],
    },
  },
  {
    id: "descript",
    name: "Descript",
    description: "텍스트 기반 오디오/비디오 편집 AI. 스크립트를 편집하면 미디어도 자동으로 편집되는 혁신적인 도구.",
    longDescription: "Descript는 오디오·비디오 편집의 패러다임을 바꾼 AI 편집 도구입니다. 음성을 자동으로 텍스트로 변환한 뒤, 텍스트를 편집하면 해당 음성·영상도 함께 편집되는 혁신적인 방식으로 작동합니다. '어..', '음...' 같은 필러 단어를 원클릭으로 모두 제거하고, 목소리를 유지한 채 스크립트를 수정하는 Overdub 기능으로 재녹음 없이 수정이 가능합니다. 팟캐스트, 유튜브 영상, 인터뷰 등 말하는 콘텐츠 편집에 특히 강력합니다.",
    url: "https://www.descript.com",
    category: "other",
    tags: ["오디오 편집", "비디오 편집", "팟캐스트", "자막"],
    free: true,
    features: ["텍스트 편집으로 미디어 편집", "자동 전사(STT)", "필러 단어 자동 제거", "Overdub 목소리 수정", "자막 자동 생성"],
    pros: ["편집 비전문가도 쉽게 사용", "팟캐스트·인터뷰 편집 시간 대폭 절감", "자막 자동 생성으로 접근성 향상"],
    cons: ["전문 비디오 편집 기능은 한계", "무료 플랜은 워터마크·제한"],
    pricing: { free: "1시간 전사 무료, 워터마크", paid: "Hobbyist $24/월, Creator $40/월, Business $80/월" },
    useCases: ["팟캐스트 편집 및 제작", "유튜브 인터뷰 편집", "웨비나 녹화 편집", "자막 자동 생성", "오디오 클립 제작"],
    pricingPlans: [{name:"Free",price:"무료",features:["1시간 전사/월","기본 편집","워터마크"],recommended:true},{name:"Pro",price:"$24/월",features:["10시간 전사/월","스크립트 편집","AI 음성"]},{name:"Enterprise",price:"$40/인/월",features:["무제한 전사","SSO","커스텀 워크플로우"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/descript-1.png","https://ai.ktoolu.com/screenshots/descript-2.png"],
    expertRating:{accuracy:4.2,easeOfUse:4.4,features:4.5,performance:4.1,value:4.1,innovation:4.3},
    whoIsFor:["팟캐스터","영상 크리에이터","마케터"],
    communityReviewSummary:{overall:"Descript는 텍스트 기반 오디오·비디오 편집 AI 도구로, 팟캐스터와 콘텐츠 크리에이터에게 필수 도구로 자리잡았습니다.",pros:[{keyword:"스크립트 편집",content:"오디오를 텍스트로 변환. 텍스트를 편집하면 미디어도 자동 편집"}, {keyword:"AI 음성",content:"AI 음성 생성·수정. 녹음 실패한 부분도 AI 목소리로 대체"}],cons:[{keyword:"한국어",content:"한국어 음성 인식·합성 품질이 영어 대비 낮음"}, {keyword:"가격",content:"고급 기능($24/월) 부담. 무료는 1시간 전사 제한"}],sources:[{name:"크리에이터 리뷰",title:"Descript 팟캐스트 편집 후기",excerpt:"스크립트 편집 방식이 혁신적. '아~' 같은 군말도 AI가 자동 제거."}]},
  },
  {
    id: "chatpdf",
    name: "ChatPDF",
    description: "PDF 문서와 대화하는 AI. 논문, 계약서, 보고서를 업로드하고 내용에 대해 질문하세요.",
    longDescription: "ChatPDF는 PDF 문서를 업로드하고 그 내용에 대해 자연어로 질문할 수 있는 AI 서비스입니다. 수백 페이지의 논문, 계약서, 재무 보고서, 법률 문서 등을 빠르게 분석하고 핵심 내용을 파악하는 데 탁월합니다. 문서 내 특정 정보를 찾거나, 요약, 비교, 번역을 요청할 수 있으며, 답변에는 해당 내용이 문서의 몇 페이지에 있는지 출처를 명시해줍니다. 학생, 연구자, 법률·금융 전문가들에게 필수적인 리서치 도구입니다.",
    url: "https://www.chatpdf.com",
    category: "other",
    tags: ["PDF 분석", "문서 QA", "논문 요약", "리서치"],
    free: true,
    features: ["PDF 업로드 후 대화형 질의응답", "페이지 출처 명시", "요약·번역 기능", "여러 PDF 동시 분석", "한국어 지원"],
    pros: ["긴 문서를 빠르게 파악 가능", "출처 페이지 표시로 신뢰성 높음", "무료 플랜으로 기본 사용 가능"],
    cons: ["무료 플랜은 파일 크기 제한", "복잡한 표·이미지 분석 한계"],
    pricing: { free: "하루 2개 PDF, 최대 120페이지", paid: "Plus $5/월 — 하루 50개 PDF, 2000페이지" },
    useCases: ["학술 논문 빠른 리뷰", "계약서 주요 조항 파악", "재무 보고서 분석", "법률 문서 이해", "교재 학습 보조"],
    pricingPlans: [{name:"Free",price:"무료",features:["2개 PDF/일","120페이지","기본 질문"],recommended:true},{name:"Plus",price:"$5/월",features:["무제한 PDF","1,000페이지","고급 분석"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/chatpdf-1.png","https://ai.ktoolu.com/screenshots/chatpdf-2.png"],
    expertRating:{accuracy:3.9,easeOfUse:4.6,features:3.5,performance:4.0,value:4.5,innovation:3.8},
    whoIsFor:["연구자·학생","사무직","일반 사용자"],
    communityReviewSummary:{overall:"ChatPDF는 PDF 문서와 대화하는 AI 도구로, 논문·계약서·보고서 분석에 널리 사용됩니다.",pros:[{keyword:"문서 분석",content:"PDF 업로드 후 질문·요약·번역. 긴 문서도 빠르게 파악"}, {keyword:"간편함",content:"회원가입 없이 PDF 업로드만으로 즉시 사용 가능"}],cons:[{keyword:"한국어",content:"한국어 PDF 처리 시 정확도 다소 저하"}, {keyword:"페이지 제한",content:"무료는 120페이지 제한. 긴 문서는 Plus($5) 필요"}],sources:[{name:"대학생 리뷰",title:"ChatPDF 논문 요약 활용",excerpt:"논문 20페이지를 1분 만에 요약. 시험 기간에 유용."}]},
  },
  {
    id: "d-id",
    name: "D-ID",
    description: "사진을 말하는 아바타로 변환하는 AI. 디지털 휴먼 기술로 교육, 마케팅 영상을 쉽게 제작합니다.",
    longDescription: "D-ID는 정지된 사진에 AI 음성과 입 모양을 합성해 실제로 말하는 것처럼 보이게 만드는 디지털 휴먼 플랫폼입니다. 인물 사진만 있으면 카메라 없이도 자연스러운 발표 영상을 만들 수 있어 교육 콘텐츠, 기업 홍보 영상, 마케팅 자료 제작에 활발히 사용됩니다. 텍스트를 입력하거나 음성 파일을 업로드하면 해당 내용을 아바타가 말하는 영상이 생성됩니다. 100개 이상의 언어를 지원하며, API를 통해 대화형 AI 아바타 서비스를 개발할 수도 있습니다.",
    url: "https://www.d-id.com",
    category: "other",
    tags: ["디지털 휴먼", "아바타", "교육 영상", "마케팅"],
    free: true,
    features: ["사진→말하는 아바타 변환", "텍스트·음성 파일 입력", "100+ 언어 지원", "대화형 AI 아바타 API", "맞춤 아바타 생성"],
    pros: ["카메라 없이 전문 발표 영상 제작", "얼굴 입 모양이 자연스러움", "다양한 언어로 즉시 현지화"],
    cons: ["무료 플랜 워터마크·크레딧 제한", "장시간 영상은 어색해 보일 수 있음"],
    pricing: { free: "20크레딧 무료 체험", paid: "Lite $5.9/월, Pro $49/월, Advanced $149/월" },
    useCases: ["교육 강의 영상 제작", "기업 안내 영상", "SNS 마케팅 영상", "다국어 제품 설명", "역사 인물 교육 콘텐츠"],
    pricingPlans: [{name:"Free",price:"무료",features:["5분/월","기본 아바타","워터마크"],recommended:true},{name:"Pro",price:"$29/월",features:["15분/월","고급 아바타","워터마크 제거"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/did-1.png","https://ai.ktoolu.com/screenshots/did-2.png"],
    expertRating:{accuracy:3.8,easeOfUse:4.1,features:3.7,performance:3.9,value:3.8,innovation:4.2},
    whoIsFor:["교육자","마케터"],
    communityReviewSummary:{overall:"D-ID는 사진을 말하는 AI 아바타로 변환하는 도구로, 교육·마케팅 영상 제작에 활용됩니다.",pros:[{keyword:"사진→아바타",content:"한 장의 사진으로 말하는 디지털 휴먼 생성. 사실적인 표정과 입모양"}, {keyword:"쉬운 제작",content:"텍스트만 입력하면 AI 아바타 영상 완성. 전문 지식 불필요"}],cons:[{keyword:"아바타 자연스러움",content:"아직 완전히 자연스럽지 않은 움직임"}, {keyword:"유료",content:"무료 5분/월 제한. 고급 기능은 Pro($29) 필요"}],sources:[{name:"교육자 리뷰",title:"D-ID AI 아바타 강의 영상",excerpt:"교수님 사진으로 강의 영상 제작. 실제 강의 같은 퀄리티."}]},
  },
  {
    id: "gamma",
    name: "Gamma",
    description: "AI로 프레젠테이션, 문서, 웹페이지를 자동 생성하는 도구. 아이디어만 입력하면 슬라이드를 만들어줍니다.",
    longDescription: "Gamma는 주제나 아이디어를 입력하면 AI가 자동으로 전체 프레젠테이션을 생성해주는 서비스입니다. 파워포인트나 키노트 없이 브라우저에서 바로 작성·발표·공유할 수 있으며, 생성된 콘텐츠를 쉽게 편집할 수 있습니다. 프레젠테이션뿐 아니라 문서, 웹페이지 형식도 지원해 다양한 용도로 활용됩니다. 세련된 디자인 템플릿을 자동으로 적용하며, PDF·PowerPoint 내보내기도 지원합니다. 링크 하나로 공유할 수 있어 협업과 배포가 편리합니다.",
    url: "https://gamma.app",
    category: "other",
    tags: ["프레젠테이션", "슬라이드", "문서 생성", "디자인"],
    free: true,
    popular: true,
    features: ["텍스트→프레젠테이션 자동 생성", "문서·웹페이지 형식 지원", "세련된 디자인 자동 적용", "PDF·PowerPoint 내보내기", "링크로 즉시 공유"],
    pros: ["슬라이드 제작 시간 90% 단축", "디자인 감각 없어도 전문가 수준", "무료 플랜도 충분히 활용 가능"],
    cons: ["고도로 커스터마이징된 디자인에는 한계", "PowerPoint 고급 기능 대체 불가"],
    pricing: { free: "400크레딧(약 10개 덱) 무료", paid: "Plus $10/월 — 무제한 AI 생성, 커스텀 폰트" },
    useCases: ["사업 계획서 프레젠테이션", "수업·강의 자료 제작", "제품 피치덱", "보고서 시각화", "포트폴리오 웹페이지"],
    pricingPlans: [{name:"Free",price:"무료",features:["400 AI 슬라이드/월","기본 템플릿","내보내기 제한"],recommended:true},{name:"Pro",price:"$10/월",features:["무제한 슬라이드","고급 템플릿","PDF·PPT"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/gamma-1.png","https://ai.ktoolu.com/screenshots/gamma-2.png"],
    expertRating:{accuracy:3.6,easeOfUse:4.5,features:4.0,performance:4.1,value:4.4,innovation:4.2},
    whoIsFor:["프레젠터","마케터","교육자"],
    communityReviewSummary:{overall:"Gamma는 한국 사용자들 사이에서 'PPT 1분 자동 완성' 도구로 큰 인기를 끌고 있습니다. 텍스트 한 줄만 입력하면 디자인까지 완성되는 편의성이 가장 큰 장점입니다.",pros:[{keyword:"속도",content:"주제만 입력하면 목차·디자인까지 1분 안에 완성. PPT 제작 시간 90% 단축"},{keyword:"웹 기반",content:"설치 불필요. 브라우저에서 바로 사용. 내보내기도 PDF·PPT 지원"}],cons:[{keyword:"유료 전환",content:"무료는 400슬라이드/월 제한. 고급 템플릿은 Pro 필요"},{keyword:"한국어 템플릿",content:"영어 템플릿 대비 한국어 템플릿 다양성 부족"}],sources:[{name:"네이버 블로그",title:"감마AI 사용법 완벽 정리 및 활용후기",excerpt:"텍스트 한 줄로 PPT·문서·웹페이지 자동 생성. 디자인 작업 불필요."},{name:"네이버 블로그",title:"감마 AI 약 한 달간의 사용후기",excerpt:"PPT 자동화로 업무 효율 향상. ChatGPT·Claude와 비교 분석."}]},
  },

  {
    id: "manus",
    name: "Manus",
    description: "2025년 급부상한 AI 에이전트 플랫폼. 사람처럼 생각하고 행동하는 자율 AI 비서입니다.",
    longDescription: "Manus는 2025년 AI 업계에 돌풍을 일으킨 자율 AI 에이전트 플랫폼입니다. 기존 챗봇과 달리, Manus는 복잡한 작업을 스스로 계획하고 실행합니다. 웹 검색, 코드 실행, 파일 처리 등 다양한 도구를 자유자재로 사용하며 결과물을 만들어냅니다. '행동하는 AI'라는 콘셉트로 출시 직후 전 세계적으로 폭발적인 관심을 받았으며, GAIA 벤치마크에서 최고 성적을 기록했습니다.",
    url: "https://manus.im",
    category: "other",
    tags: ["AI 에이전트", "자율 작업", "2025", "플랫폼"],
    free: true,
    popular: true,
    features: ["자율적 작업 계획-실행", "웹 검색 통합", "코드 실행 환경", "파일 처리", "멀티 도구 사용"],
    pros: ["자율적 복잡 작업 수행", "사용자 친화적 UI", "다양한 도구 통합"],
    cons: ["아직 베타 단계", "작업 시간이 다소 김"],
    useCases: ["리서치 보고서 작성", "데이터 분석", "웹 스크래핑", "자동화된 문서 작업"],
    pricingPlans: [{name:"Free",price:"무료",features:["기본 에이전트","웹 검색","코드 실행"],recommended:true},{name:"Pro",price:"$29/월",features:["고급 에이전트","파일 처리","우선 처리"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/manus-1.png","https://ai.ktoolu.com/screenshots/manus-2.png"],
    expertRating:{accuracy:4.0,easeOfUse:3.8,features:4.2,performance:3.7,value:4.3,innovation:4.8},
    whoIsFor:["리서처","비즈니스 분석가","일반 사용자"],
    communityReviewSummary: {
      overall: "Manus는 2025년 AI 업계에 돌풍을 일으킨 자율 AI 에이전트입니다. 한국 사용자들은 복잡한 작업을 스스로 계획하고 실행하는 능력에 주목하고 있습니다.",
      pros: [{keyword:"자율 작업",content:"복잡한 리서치·데이터 분석을 스스로 계획하고 실행. 결과물까지 생성"}, {keyword:"멀티 도구",content:"웹 검색, 코드 실행, 파일 처리 등 다양한 도구 자유자재 사용"}],
      cons: [{keyword:"초기 단계",content:"아직 베타 수준, 작업 시간이 다소 김"}, {keyword:"신뢰성",content:"자율 작업 결과물의 정확성 검증 필요"}],
      sources: [
        {name:"네이버 블로그",title:"Manus AI 사용 후기, 리서치 자동화의 새 시대",excerpt:"리서치 보고서 작성에 활용. 자율적으로 웹 검색하고 결과물 정리."},
        {name:"네이버 블로그",title:"Manus AI 직접 써본 후기",excerpt:"복잡한 명령도 스스로 계획 세워서 실행. 아직 가끔 엉뚱한 결과물."},
      ],
    },
  },
  {
    id: "zapier-ai",
    name: "Zapier AI",
    description: "세계 최대 자동화 플랫폼의 AI 기능. 6,000개 이상의 앱을 연결해 워크플로우를 자동화합니다.",
    longDescription: "Zapier는 6,000개 이상의 앱을 코드 없이 연결하는 세계 최대 자동화 플랫폼으로, AI가 통합되어 더욱 강력해졌습니다. Zapier AI는 이메일, 스프레드시트, CRM 등에서 데이터를 추출-가공-전송하는 워크플로우를 AI가 자동으로 생성합니다. 자연어로 원하는 작업을 설명하면 AI가 적절한 트리거와 액션을 조합해 자동화를 만들어줍니다. GPT, Claude 등 AI 모델을 통합해 AI 기반 의사결정 자동화도 가능합니다.",
    url: "https://zapier.com",
    category: "other",
    tags: ["자동화", "워크플로우", "통합", "무코드"],
    free: true,
    popular: true,
    features: ["6,000+ 앱 통합", "AI 자동화 생성", "자연어로 자동화 생성", "AI 모델 통합", "멀티 스텝 워크플로우"],
    pros: ["압도적인 앱 연동 수", "코드 없이 자동화", "AI가 자동으로 워크플로우 생성"],
    cons: ["무료 플랜 제한적", "복잡한 워크플로우는 유료"],
    useCases: ["마케팅 자동화", "영업 리드 관리", "데이터 동기화", "고객 지원 자동화", "AI 기반 의사결정"],
    pricingPlans: [{name:"Free",price:"무료",features:["100 태스크/월","5개 Zap","기본 AI"],recommended:true},{name:"Starter",price:"$19.99/월",features:["750 태스크/월","20개 Zap","AI 자동화"]},{name:"Professional",price:"$49/월",features:["2,000 태스크/월","무제한 Zap","고급 AI"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/zapier-1.png","https://ai.ktoolu.com/screenshots/zapier-2.png"],
    expertRating:{accuracy:3.8,easeOfUse:4.2,features:4.6,performance:4.0,value:4.2,innovation:4.1},
    whoIsFor:["마케터","운영팀","스타트업"],
    communityReviewSummary:{overall:"Zapier는 한국 1인 창업가와 스타트업 사이에서 필수 자동화 도구로 자리잡았습니다. 코딩 없이 앱 간 데이터 흐름을 연결할 수 있는 점이 가장 큰 장점입니다.",pros:[{keyword:"무코드 자동화",content:"6000개 이상 앱 연동. 코딩 없이 업무 자동화 구축"},{keyword:"AI 통합",content:"자연어로 원하는 자동화 설명하면 AI가 Zap 생성"}],cons:[{keyword:"무료 제한",content:"100 태스크/월 제한. 실제 업무 자동화는 유료 필요"},{keyword:"복잡성",content:"복잡한 조건부 자동화는 Make나 n8n이 더 자유도 높음"}],sources:[{name:"네이버 블로그",title:"1인 창업가 필독 - 단순 챗봇 버리고 AI 멀티 에이전트",excerpt:"코딩 없이 시작. 구글 시트→이메일 자동 발송부터 시작 추천."},{name:"네이버 블로그",title:"AI 자동화 도구 비교 (Zapier, Make, n8n)",excerpt:"앱끼리 연결하는 다리 역할. 초보자가 가장 쉽게 시작할 수 있는 도구."}]},
  },
  // === AGENT / 자동화 ===
  {
    id: "kling",
    name: "Kling AI",
    description: "중국 Kuaishou의 고품질 AI 비디오 생성 모델. 텍스트와 이미지로 사실적인 영상을 생성합니다.",
    url: "https://kling.kuaishou.com",
    category: "video",
    tags: ["AI 비디오", "텍스트→비디오", "중국", "Kuaishou"],
    free: true,
    popular: true,
    features: ["텍스트→비디오 생성", "이미지→비디오", "고품질 모션", "다양한 스타일"],
    pricingPlans: [{name:"Free",price:"무료",features:["기본 생성","워터마크","제한적"],recommended:true},{name:"Pro",price:"$15/월",features:["무제한","고해상도","워터마크 제거"]}],
    screenshots:["https://ai.ktoolu.com/screenshots/kling-1.png"],
    expertRating:{accuracy:3.8,easeOfUse:3.9,features:4.0,performance:4.2,value:4.3,innovation:4.4},
    whoIsFor:["비디오 크리에이터","콘텐츠 제작자"],
  },
  {
    id: "veo",
    name: "Google Veo",
    description: "Google DeepMind의 AI 비디오 생성 모델. Gemini에 통합되어 고품질 영상을 생성합니다.",
    url: "https://deepmind.google/technologies/veo/",
    category: "video",
    tags: ["Google", "AI 비디오", "DeepMind", "고품질"],
    free: false,
    features: ["텍스트→비디오 생성", "고품질 영상", "Gemini 통합", "다양한 스타일"],
    pricingPlans: [{name:"Veo",price:"Gemini Advanced 포함",features:["텍스트→비디오","이미지→비디오","고해상도"],recommended:true}],
    screenshots:["https://ai.ktoolu.com/screenshots/veo-1.png"],
    expertRating:{accuracy:4.0,easeOfUse:3.8,features:3.9,performance:4.3,value:3.7,innovation:4.5},
    whoIsFor:["크리에이터","마케터"],
  },
  {
    id: "auto-gpt",
    name: "AutoGPT",
    description: "자율적으로 목표를 계획하고 실행하는 AI 에이전트. 복잡한 작업을 스스로 분해하고 처리합니다.",
    url: "https://agpt.co",
    category: "agent",
    tags: ["AI 에이전트", "자율 작업", "오픈소스", "자동화"],
    free: true,
    popular: true,
    features: ["자율 목표 실행", "코드 생성", "웹 검색", "파일 조작"],
    useCases: ["자동 리서치", "데이터 수집", "보고서 자동 생성"],
    pricingPlans: [{name:"Free",price:"무료",features:["기본 에이전트","웹 검색","오픈소스"],recommended:true},{name:"Cloud",price:"$20/월",features:["클라우드 실행","우선 처리","고급 도구"]}],
  },
  {
    id: "n8n",
    name: "n8n",
    description: "오픈소스 워크플로우 자동화 도구. AI 통합으로 복잡한 업무 흐름을 자동화합니다.",
    url: "https://n8n.io",
    category: "agent",
    tags: ["워크플로우", "자동화", "오픈소스", "노코드"],
    free: true,
    features: ["400+ 통합", "AI 노드", "조건부 로직", "오픈소스"],
    pricingPlans: [{name:"Self-hosted",price:"무료",features:["오픈소스","자체 호스팅","무제한"],recommended:true},{name:"Cloud",price:"$20/월",features:["클라우드","5k 실행/월","AI 기능"]}],
  },
  {
    id: "browser-use",
    name: "Browser Use",
    description: "AI가 브라우저를 직접 조작해 웹 작업을 자동화하는 오픈소스 에이전트 도구입니다.",
    url: "https://browser-use.com",
    category: "agent",
    tags: ["브라우저 자동화", "AI 에이전트", "오픈소스", "웹 스크래핑"],
    free: true,
    popular: true,
    features: ["브라우저 직접 조작", "로그인·클릭·입력 자동화", "웹 데이터 수집"],
    pricingPlans: [{name:"Open Source",price:"무료",features:["GitHub","자체 호스팅","API"],recommended:true}],
  },
  {
    id: "crewai",
    name: "CrewAI",
    description: "여러 AI 에이전트가 팀을 이뤄 협업하는 프레임워크. 역할 기반으로 복잡한 작업을 분산 처리합니다.",
    url: "https://crewai.com",
    category: "agent",
    tags: ["멀티 에이전트", "프레임워크", "오픈소스", "협업"],
    free: true,
    popular: true,
    features: ["역할 기반 에이전트", "팀 협업", "도구 통합", "순차/병렬 작업"],
    pricingPlans: [{name:"Open Source",price:"무료",features:["GitHub","자체 호스팅"],recommended:true},{name:"Cloud",price:"$19/월",features:["클라우드 실행","모니터링","팀 기능"]}],
  },
  {
    id: "flowise",
    name: "Flowise",
    description: "드래그 앤 드롭으로 LLM 워크플로우를 구축하는 오픈소스 도구. 코딩 없이 AI 파이프라인을 만듭니다.",
    url: "https://flowiseai.com",
    category: "agent",
    tags: ["노코드", "LLM", "워크플로우", "오픈소스"],
    free: true,
    popular: true,
    features: ["드래그 앤 드롭 UI", "LLM 체인 구축", "RAG 파이프라인", "API 노출"],
    pricingPlans: [{name:"Self-hosted",price:"무료",features:["오픈소스","무제한","커스텀"],recommended:true},{name:"Cloud",price:"$15/월",features:["클라우드","무제한 워크플로우","지원"]}],
  },
  {
    id: "autogen",
    name: "AutoGen",
    description: "Microsoft의 멀티 에이전트 대화 프레임워크. 여러 AI가 대화하며 문제를 해결합니다.",
    url: "https://microsoft.github.io/autogen/",
    category: "agent",
    tags: ["멀티 에이전트", "Microsoft", "오픈소스", "대화형"],
    free: true,
    popular: true,
    features: ["멀티 에이전트 대화", "코드 실행", "도구 사용", "인간 참여"],
    pricingPlans: [{name:"Open Source",price:"무료",features:["GitHub","자체 호스팅","전체 기능"],recommended:true}],
  },
];
