export type Category =
  | "all"
  | "text"
  | "image"
  | "video"
  | "coding"
  | "music"
  | "other";

export interface PricingPlan {
  name: string;
  price: string;
  features: string[];
  recommended?: boolean;
}

export interface ExpertRating {
  accuracy: number;
  easeOfUse: number;
  features: number;
  performance: number;
  value: number;
  innovation: number;
}

export interface AITool {
  id: string;
  name: string;
  description: string;
  longDescription?: string;
  url: string;
  category: Exclude<Category, "all">;
  tags: string[];
  free: boolean;
  popular?: boolean;
  features?: string[];
  pros?: string[];
  cons?: string[];
  pricing?: { free?: string; paid?: string };
  pricingPlans?: PricingPlan[];
  comparisonNotes?: string;
  useCases?: string[];
  screenshots?: string[];
  expertRating?: ExpertRating;
  whoIsFor?: string[];
  communityReviewSummary?: {
    overall: string;
    pros: { keyword: string; content: string }[];
    cons: { keyword: string; content: string }[];
    sources: { name: string; title: string; excerpt: string }[];
  };
}

export const categories: { value: Category; label: string; emoji: string }[] = [
  { value: "all", label: "전체", emoji: "🌐" },
  { value: "text", label: "텍스트 / 글쓰기", emoji: "✍️" },
  { value: "image", label: "이미지 생성", emoji: "🎨" },
  { value: "video", label: "비디오", emoji: "🎬" },
  { value: "coding", label: "코딩", emoji: "💻" },
  { value: "music", label: "음악", emoji: "🎵" },
  { value: "other", label: "기타", emoji: "✨" },
];

export const aiTools: AITool[] = [
  // === TEXT ===
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: "OpenAI의 가장 강력한 대화형 AI. GPT-4o 기반으로 텍스트, 이미지, 파일 분석 등 다양한 작업을 처리합니다.",
    longDescription: "ChatGPT는 OpenAI가 개발한 세계 최대 사용자 수를 보유한 대화형 AI입니다. GPT-4o 모델을 기반으로 텍스트 생성, 코드 작성, 이미지 분석, 파일 요약, 수학 풀이 등 거의 모든 지식 작업을 수행할 수 있습니다. 무료 플랜에서도 GPT-4o mini 모델을 사용할 수 있으며, Plus 구독 시 더 강력한 GPT-4o 모델과 DALL·E 이미지 생성, 고급 데이터 분석 기능을 이용할 수 있습니다. 플러그인 생태계와 GPT Store를 통해 다양한 전문 기능을 확장할 수 있어 업무 자동화, 학습, 창작 등 다양한 분야에서 활용됩니다.",
    url: "https://chat.openai.com",
    category: "text",
    tags: ["GPT-4o", "대화형 AI", "문서 분석", "OpenAI"],
    free: true,
    popular: true,
    features: ["GPT-4o 멀티모달 모델 지원", "이미지·파일·PDF 분석", "코드 작성 및 디버깅", "DALL·E 이미지 생성(Plus)", "고급 데이터 분석", "GPT Store 플러그인 확장"],
    pros: ["세계 최대 AI 사용자 커뮤니티", "가장 폭넓은 기능 지원", "무료 플랜으로도 충분히 활용 가능", "한국어 지원 우수"],
    cons: ["무료 플랜은 사용량 제한 있음", "학습 데이터 컷오프로 최신 정보 부재(웹 검색 없이)"],
    pricing: { free: "GPT-4o mini 무제한, GPT-4o 제한적 사용", paid: "Plus $20/월 — GPT-4o 우선 접근, 이미지 생성, 고급 분석" },
    useCases: ["보고서·이메일 초안 작성", "코드 작성 및 디버깅", "외국어 번역 및 학습", "데이터 분석 및 시각화", "아이디어 브레인스토밍"],
    pricingPlans: [
      { name: "Free", price: "무료", features: ["GPT-4o mini 무제한", "GPT-4o 제한적 사용", "파일 업로드 가능", "웹 검색 불가"], recommended: true },
      { name: "Plus", price: "$20/월", features: ["GPT-4o 우선 접근", "DALL·E 이미지 생성", "고급 데이터 분석", "메시지 5배 더 많이"] },
      { name: "Pro", price: "$200/월", features: ["GPT-4o 무제한", "고속 응답", "고급 데이터 분석 무제한", "Codex 통합"] },
      { name: "Team", price: "$25/인/월", features: ["Plus 기능 전체", "공유 작업공간", "팀 관리 콘솔"] },
    ],
    comparisonNotes: "일반 사용자: Free로 충분. GPT-4o 우선 접근이 필요하면 Plus. 고급 데이터 분석과 코드 작업이 많으면 Pro. 기업 팀은 Team.",
    screenshots: [
      "https://ai.ktoolu.com/screenshots/chatgpt-1.png",
      "https://ai.ktoolu.com/screenshots/chatgpt-2.png",
      "https://ai.ktoolu.com/screenshots/chatgpt-3.png"
    ],
    expertRating: { accuracy: 4.3, easeOfUse: 4.5, features: 4.8, performance: 4.5, value: 4.7, innovation: 4.6 },
    whoIsFor: ["AI 초보자 — 무료로 시작해보고 싶은 분", "개발자 — 코드 작성 및 디버깅이 필요한 분", "콘텐츠 크리에이터 — 글쓰기·번역이 필요한 분", "일반 사무직 — 보고서·이메일 자동화를 원하는 분"],
    communityReviewSummary: {
      overall: "한국 사용자들은 ChatGPT를 'AI 생산성의 첫걸음'으로 평가합니다. 클리앙·DC Inside 등에서 수집한 실제 사용 후기에 따르면, 전문직(변호사·개발자) 사용자들은 ChatGPT를 업무 필수 도구로 채택했으나 단일 모델 의존보다 여러 LLM(Claude, Gemini)을 병행 사용하는 추세입니다. 무료 버전만으로도 충분히 활용 가능하지만, 고급 작업을 위해서는 Plus($20/월) 이상 구독이 권장됩니다.",
      pros: [
        { keyword: "생산성 향상", content: "방대한 문서 검토/요약, 코드 작성, 법률 자문 초안 등 업무 효율을 극적으로 향상시킨다는 평가" },
        { keyword: "다양한 활용도", content: "코딩, 법률, 세무, 창작, 번역, 데이터 분석 등 거의 모든 분야에서 활용 가능" },
        { keyword: "접근성", content: "무료 버전만으로도 기초 작업 수행 가능, 카카오톡 쿠폰 등 한국형 결제 수단 지원" },
        { keyword: "지속적 발전", content: "GPT-4 → GPT-4o로의 업데이트로 성능이 지속적으로 향상 중" },
      ],
      cons: [
        { keyword: "환각", content: "법률/세무 등 전문 영역에서 잘못된 정보를 생성하는 경우가 있어 반드시 원문 검증이 필요" },
        { keyword: "비용 부담", content: "Pro($200/월) 등 고급 플랜은 개인 사용자에게 부담스러운 수준" },
        { keyword: "경쟁 심화", content: "Claude, Gemini, Perplexity 등 경쟁 모델 대비 전문 영역에서 차별성 감소 추세" },
        { keyword: "구독 전환 불편", content: "Plus→Pro 전환 시 활성 구독 문제 등 사용자 경험 개선 필요" },
      ],
      sources: [
        { name: "클리앙", title: "변호사로서 GPT, GEMINI, PERPLEXITY, CLAUDE 사용결과", excerpt: "대형로펌 세무 12년차 파트너 변호사. GPT PRO가 처음 AI 생산성을 느끼게 해줬으나, 법률업무에서는 Gemini와 Perplexity가 더 만족스러움." },
        { name: "클리앙", title: "최근 AI 코딩으로 SW개발자 영향에 대한 느낌", excerpt: "ChatGPT가 코딩 보조 도구로서 생산성을 크게 향상시킨다는 의견." },
        { name: "DC Inside", title: "팬싸 후기의 비하인드", excerpt: "무료버전은 AI 생성 내용이 부족해서 유료로 업그레이드, 유료 버전이 무료보다 생성 품질이 월등히 좋음." },
        { name: "네이버 블로그", title: "ChatGPT 제대로 활용하는 법! 장단점부터 프롬프트 작성법까지", excerpt: "SURF 구조(Subject, Request, Format, Scope)로 프롬프트 작성법 설명. 초보자가 사용법을 모르면 원하는 결과를 얻기 어려움." },
      ],
    },
  },
  {
    id: "claude",
    name: "Claude",
    description: "Anthropic의 AI 어시스턴트. 긴 문서 처리, 코드 작성, 분석에 뛰어나며 안전성에 중점을 둡니다.",
    longDescription: "Claude는 AI 안전 연구소 Anthropic이 개발한 대화형 AI로, 최대 200K 토큰(약 15만 단어)의 긴 컨텍스트 처리 능력이 핵심 강점입니다. 긴 문서 요약, 복잡한 코드베이스 분석, 세밀한 글쓰기 작업에서 탁월한 성능을 보여줍니다. '헌법적 AI' 방법론을 통해 안전하고 신뢰할 수 있는 답변을 제공하도록 설계되었습니다. Claude 3.5 Sonnet은 코딩 벤치마크에서 최상위 성능을 기록하며, 특히 뉘앙스가 중요한 글쓰기와 분석 작업에서 뛰어난 결과를 냅니다.",
    url: "https://claude.ai",
    category: "text",
    tags: ["Claude 3.5", "긴 컨텍스트", "안전 AI", "Anthropic"],
    free: true,
    popular: true,
    features: ["최대 200K 토큰 긴 컨텍스트", "코드 작성·분석·디버깅", "PDF·문서 업로드 분석", "세밀한 글쓰기 및 편집", "안전성 중심 설계"],
    pros: ["긴 문서 처리 능력 업계 최고 수준", "글쓰기 품질과 뉘앙스가 뛰어남", "안전하고 균형 잡힌 응답", "코딩 성능 우수"],
    cons: ["이미지 생성 기능 없음", "무료 플랜 사용량 제한"],
    pricing: { free: "Claude 3.5 Haiku 사용 가능, 일일 제한 있음", paid: "Pro $20/월 — Claude 3.5 Sonnet 우선 접근, 5배 더 많은 사용량" },
    useCases: ["긴 계약서·논문 분석", "복잡한 코드 리뷰", "고품질 글쓰기 및 편집", "리서치 보조", "다국어 번역"],
    pricingPlans: [
      { name: "Free", price: "무료", features: ["Claude 3.5 Haiku 사용", "일일 메시지 제한", "PDF 업로드 가능", "웹 검색 제한적"], recommended: true },
      { name: "Pro", price: "$20/월", features: ["Claude 3.5 Sonnet 우선", "5배 더 많은 사용량", "긴 문서 처리 최대", "우선 응답 속도"] },
      { name: "Team", price: "$30/인/월", features: ["Pro 기능 전체", "공유 작업공간", "중앙 관리 콘솔", "사용량 분석"] },
      { name: "Enterprise", price: "문의", features: ["맞춤형 모델", "SSO·보안 규정 준수", "전용 지원", "SLA 보장"] },
    ],
    comparisonNotes: "긴 문서·논문 분석이 주 목적: Free로 시작. 하루 5시간 이상 사용: Pro. 연구실·팀 단위: Team. 대규모 기업 보안: Enterprise.",
    screenshots: [
      "https://ai.ktoolu.com/screenshots/claude-1.png",
      "https://ai.ktoolu.com/screenshots/claude-2.png",
      "https://ai.ktoolu.com/screenshots/claude-3.png"
    ],
    expertRating: { accuracy: 4.6, easeOfUse: 4.3, features: 4.4, performance: 4.7, value: 4.5, innovation: 4.4 },
    whoIsFor: ["연구자·학생 — 긴 논문·문서 분석이 필요한 분", "개발자 — 코드 리뷰 및 복잡한 분석이 필요한 분", "작가·에디터 — 고품질 글쓰기가 중요한 분", "기업 문서 담당자 — 긴 계약서·보고서 처리자"],
    communityReviewSummary: {
      overall: "한국 사용자들 사이에서 Claude는 '코딩과 장문 글쓰기에서는 최고지만, 가격과 사용량 제한이 가장 큰 걸림돌'로 평가됩니다. 클리앙 사용기 게시판에서 수집한 실제 후기에 따르면, 개발자와 전문직 사용자들은 Claude의 코드 품질과 문맥 이해력을 높이 평가하면서도 Gemini나 GPT와 병행 사용하는 전략을 주로 채택합니다. 특히 법률/세무 등 전문 분야에서 GPT Pro보다 Claude Max의 딥리서치 성능이 더 우수하다는 평가도 있습니다.",
      pros: [
        { keyword: "코딩 품질", content: "코드 품질 최상급, 1,000행 이상 코드 생성 가능, 복잡한 디버깅에 강함. 플랜 모드로 체계적 작업 가능" },
        { keyword: "문맥 유지", content: "자연스러운 문체, 장문 글쓰기/문서 작업에서 문맥 흐름이 매우 우수함" },
        { keyword: "딥리서치", content: "GPT Pro보다 법률·전문 업무에서 딥리서치 결과가 더 만족스럽다는 평가" },
        { keyword: "안정성", content: "환각(hallucination) 빈도가 GPT/Gemini 대비 매우 낮음. 수백 회 중 1회 꼴" },
      ],
      cons: [
        { keyword: "가격 폭탄", content: "자동 캐싱 미지원으로 요금제에 큰 함정. 추가 사용량 방치 시 하루 $100 소진 가능. 1억 토큰당 $48.8로 가장 비쌈" },
        { keyword: "세션 제한", content: "세션 길이가 매우 짧아 10분마다 진행상황 정리 필요. $20 플랜은 30분 만에 제한 소진" },
        { keyword: "추상어 과민반응", content: "코딩시 불필요/불명확한 단어 사용 시 오작동. Claude.md에 제한 설정 필수" },
        { keyword: "멀티모달 약함", content: "이미지 생성, 실시간 검색 등은 GPT/Gemini 대비 제한적" },
      ],
      sources: [
        { name: "클리앙", title: "변호사로서 GPT, GEMINI, PERPLEXITY, CLAUDE 사용결과", excerpt: "CLAUDE MAX(5x, $110) 유지 중. GPT PRO보다 CLAUDE의 딥리서치가 더 빠르고 결과 만족도 높음. \"GPT는 이제 그만 구독해도 되겠다\"" },
        { name: "클리앙", title: "제미나이 2.5 pro, chatGPT, 클로드, Manus 3개월 굴려본 후기", excerpt: "코드 품질 우수. 세션 길이가 짧지만 환각은 수백회 중 1회로 매우 드묾. $100 플랜 유지 중." },
        { name: "클리앙", title: "바이브 코딩 하실 분들을 위한 작은 조언", excerpt: "4개월간 하루 평균 100커밋. Claude Sonnet 4.5 평가: 자동캐시 히트율 94~97%. $20 플랜은 30분도 안 돼 제한 소진." },
        { name: "네이버 블로그", title: "챗GPT와 클로드(Claude)에 대한 솔직한 사용 후기", excerpt: "문맥 유지 능력과 자연스러운 문체가 강점. 문서·이메일·기획·브레인스토밍에 적합." },
      ],
    },
  },
  {
    id: "gemini",
    name: "Gemini",
    description: "Google의 멀티모달 AI. Google 서비스와 완벽하게 통합되며 실시간 정보 검색이 가능합니다.",
    longDescription: "Gemini는 Google DeepMind가 개발한 멀티모달 AI로, Google 검색·Gmail·Docs·Drive 등 Google 생태계와 깊이 통합되어 있습니다. Gemini 1.5 Pro는 100만 토큰의 초장문 컨텍스트를 지원하며, Google 검색을 통한 실시간 정보 접근이 가능합니다. YouTube 영상 분석, Google 문서 요약 등 Google 서비스 사용자에게 특히 유용합니다. Gemini Advanced(Ultra 모델)는 복잡한 추론과 멀티모달 작업에서 최고 수준의 성능을 보여줍니다.",
    url: "https://gemini.google.com",
    category: "text",
    tags: ["멀티모달", "Google 통합", "실시간 검색", "Google"],
    free: true,
    popular: true,
    features: ["Google 서비스 완전 통합", "실시간 웹 검색", "최대 100만 토큰 컨텍스트", "이미지·영상·오디오 분석", "Google Workspace 연동"],
    pros: ["실시간 최신 정보 접근 가능", "Google 계정으로 즉시 사용", "Google Docs·Gmail과 완벽 연동", "무료 플랜이 강력함"],
    cons: ["Google 생태계 외 사용 시 장점 감소", "창의적 글쓰기는 타 모델 대비 약함"],
    pricing: { free: "Gemini 1.5 Flash 무제한", paid: "Advanced $19.99/월 — Gemini Ultra, 2TB 드라이브 포함" },
    useCases: ["실시간 뉴스·정보 검색", "Gmail 답장 초안 작성", "Google Docs 문서 요약", "YouTube 영상 내용 분석", "여행·쇼핑 리서치"],
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    description: "AI 기반 검색 엔진. 실시간 웹 검색과 AI를 결합해 출처가 명확한 답변을 제공합니다.",
    longDescription: "Perplexity AI는 기존 검색 엔진의 한계를 극복한 AI 검색 엔진입니다. 질문을 입력하면 실시간으로 수십 개의 웹 페이지를 검색·분석하여 출처가 명확한 요약 답변을 제공합니다. 각 답변에는 참고 출처 링크가 첨부되어 사실 확인이 쉽습니다. GPT-4, Claude, Mistral 등 다양한 AI 모델을 선택해 사용할 수 있으며, Copilot 기능으로 심층 리서치도 가능합니다. 학술 논문, 뉴스, 소셜 미디어 등 다양한 출처를 필터링할 수 있습니다.",
    url: "https://www.perplexity.ai",
    category: "text",
    tags: ["AI 검색", "실시간 정보", "출처 인용", "리서치"],
    free: true,
    popular: true,
    features: ["실시간 웹 검색 및 요약", "출처 링크 자동 첨부", "여러 AI 모델 선택 가능", "학술·뉴스 필터 검색", "공간 공유 및 협업"],
    pros: ["검색 결과에 출처가 명확히 표시됨", "최신 정보를 실시간으로 반영", "빠른 리서치에 최적화", "무료로도 충분히 유용"],
    cons: ["창작·글쓰기 작업엔 부적합", "깊은 분석보다 요약에 치중"],
    pricing: { free: "기본 검색 무제한", paid: "Pro $20/월 — 무제한 Copilot, 파일 업로드, 고급 모델" },
    useCases: ["최신 뉴스 및 트렌드 리서치", "제품 비교 및 구매 조사", "학술 자료 수집", "사실 확인(팩트 체크)", "시장 조사"],
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    description: "Notion에 내장된 AI 어시스턴트. 문서 작성, 요약, 번역 등 노트와 프로젝트 관리를 도와줍니다.",
    longDescription: "Notion AI는 세계적인 노트·협업 도구 Notion에 내장된 AI 어시스턴트입니다. 문서를 작성하는 중에 AI의 도움을 받아 초안 생성, 요약, 번역, 맞춤법 교정, 톤 변환 등을 바로 처리할 수 있습니다. 기존 Notion 페이지 내용을 참조해 답변하는 'Q&A' 기능으로 팀 위키나 회사 문서에서 빠르게 정보를 찾을 수 있습니다. Notion을 이미 사용 중인 팀이라면 별도 도구 없이 워크플로우를 크게 향상시킬 수 있습니다.",
    url: "https://www.notion.so/product/ai",
    category: "text",
    tags: ["문서 작성", "요약", "Notion 통합", "협업"],
    free: false,
    features: ["문서 내 인라인 AI 작성 보조", "페이지 요약 및 번역", "워크스페이스 Q&A", "자동 액션 아이템 추출", "톤·스타일 변환"],
    pros: ["Notion 워크플로우에 자연스럽게 통합", "팀 문서 전체를 AI가 학습해 Q&A 가능", "별도 탭 전환 없이 사용"],
    cons: ["Notion 구독자만 사용 가능", "독립 AI 도구보다 기능이 제한적"],
    pricing: { paid: "Notion Plus $10/월에 AI 애드온 $8/월 추가, 또는 AI 포함 플랜 $16/월" },
    useCases: ["회의록 자동 요약", "프로젝트 문서 초안 작성", "팀 위키 Q&A", "다국어 문서 번역", "보고서 구조화"],
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    description: "마케팅 카피, 블로그 포스트, 소셜 미디어 콘텐츠 생성에 특화된 AI 글쓰기 도구입니다.",
    longDescription: "Copy.ai는 마케터와 콘텐츠 크리에이터를 위한 AI 글쓰기 플랫폼입니다. 광고 카피, 이메일 뉴스레터, 블로그 포스트, 소셜 미디어 게시물 등 90가지 이상의 콘텐츠 템플릿을 제공합니다. 브랜드 보이스를 설정하면 일관된 톤으로 콘텐츠를 생성하며, 여러 언어로 동시에 콘텐츠를 제작할 수 있습니다. Workflow 기능으로 반복적인 콘텐츠 작업을 자동화할 수 있어 마케팅 팀의 생산성을 크게 높여줍니다.",
    url: "https://www.copy.ai",
    category: "text",
    tags: ["카피라이팅", "마케팅", "블로그", "SNS"],
    free: true,
    features: ["90가지 이상 콘텐츠 템플릿", "브랜드 보이스 설정", "다국어 콘텐츠 생성", "워크플로우 자동화", "팀 협업 기능"],
    pros: ["마케팅 특화 템플릿이 풍부함", "빠른 콘텐츠 대량 생산에 유리", "무료 플랜도 기본 기능 충분"],
    cons: ["범용 AI보다 창의성이 낮을 수 있음", "고급 기능은 유료 필요"],
    pricing: { free: "월 2,000 단어, 기본 템플릿", paid: "Pro $36/월 — 무제한 단어, 워크플로우, 5개 시트" },
    useCases: ["SNS 광고 카피 작성", "이메일 마케팅 캠페인", "제품 설명 대량 생성", "블로그 콘텐츠 계획", "랜딩 페이지 문구"],
  },
  {
    id: "jasper",
    name: "Jasper AI",
    description: "기업용 AI 콘텐츠 플랫폼. 브랜드 보이스를 학습해 일관된 마케팅 콘텐츠를 생성합니다.",
    longDescription: "Jasper AI는 기업 마케팅 팀을 위한 엔터프라이즈급 AI 콘텐츠 플랫폼입니다. 브랜드의 기존 콘텐츠, 가이드라인, 스타일 가이드를 학습해 회사 고유의 목소리로 콘텐츠를 생성합니다. SEO 최적화 기능, Google Docs·Chrome 익스텐션 연동, Surfer SEO 통합 등 실무 마케터에게 필요한 도구들이 잘 갖춰져 있습니다. 다국어 지원과 팀 협업 기능으로 글로벌 마케팅 팀에서도 활발히 사용됩니다.",
    url: "https://www.jasper.ai",
    category: "text",
    tags: ["기업용", "브랜드 마케팅", "콘텐츠 자동화"],
    free: false,
    features: ["브랜드 보이스 커스터마이징", "SEO 최적화 콘텐츠", "50가지 이상 콘텐츠 템플릿", "팀 협업 및 권한 관리", "API 연동"],
    pros: ["브랜드 일관성 유지가 탁월", "엔터프라이즈 보안 및 팀 관리", "SEO 도구와 통합"],
    cons: ["가격이 비쌈", "개인 사용자에게는 과도한 기능"],
    pricing: { paid: "Creator $39/월, Pro $59/월, Business 별도 문의" },
    useCases: ["브랜드 블로그 대량 발행", "글로벌 마케팅 캠페인", "제품 카탈로그 콘텐츠", "이메일 시퀀스 자동화", "SEO 콘텐츠 전략"],
  },
  {
    id: "grammarly",
    name: "Grammarly",
    description: "AI 기반 영문 교정 및 글쓰기 어시스턴트. 문법, 스타일, 명확성을 개선합니다.",
    longDescription: "Grammarly는 3000만 명 이상이 사용하는 세계 최대 영문 글쓰기 보조 도구입니다. 문법 오류 교정을 넘어 문장의 명확성, 어조, 참여도, 전달력까지 분석해 더 나은 글쓰기를 돕습니다. Chrome 확장 프로그램으로 Gmail, Google Docs, Twitter, LinkedIn 등 거의 모든 웹 텍스트 영역에서 실시간으로 작동합니다. Grammarly GO AI 기능으로 이메일 답장, 문서 초안을 자동 생성할 수 있으며, 표절 검사 기능도 제공합니다.",
    url: "https://www.grammarly.com",
    category: "text",
    tags: ["영문 교정", "문법 검사", "글쓰기 개선"],
    free: true,
    features: ["실시간 문법·맞춤법 교정", "문체·어조 분석 및 개선 제안", "표절 검사", "Chrome 확장 프로그램", "AI 글쓰기 보조(GO)"],
    pros: ["어느 웹사이트에서나 즉시 작동", "비영어권 사용자 영어 실력 향상에 최적", "무료 플랜도 핵심 교정 기능 제공"],
    cons: ["영어 전용 (한국어 지원 없음)", "고급 기능은 유료"],
    pricing: { free: "기본 문법·맞춤법 교정", paid: "Premium $12/월 — 고급 제안, 표절 검사, 어조 분석" },
    useCases: ["영문 이메일 작성", "영어 에세이 및 보고서 교정", "LinkedIn 프로필 개선", "비즈니스 문서 품질 향상", "영어 학습"],
  },

  // === IMAGE ===
  {
    id: "midjourney",
    name: "Midjourney",
    description: "가장 인기 있는 AI 이미지 생성 도구. Discord 기반으로 놀라운 아트워크와 사실적인 이미지를 만들어냅니다.",
    longDescription: "Midjourney는 예술적 감각과 품질 면에서 업계 최고로 평가받는 AI 이미지 생성 도구입니다. Discord 채널에서 명령어를 입력하는 방식으로 작동하며, 웹 인터페이스도 제공합니다. V6 모델은 사진에 가까운 사실성과 뛰어난 구성력을 자랑하며, 일관성 기능으로 동일한 캐릭터를 여러 이미지에서 유지할 수 있습니다. 상업적 이용이 가능하며, 패션, 광고, 게임, 영화 등 다양한 산업에서 전문가들이 활발히 사용합니다. 매달 수억 장의 이미지가 생성될 만큼 방대한 커뮤니티를 보유하고 있습니다.",
    url: "https://www.midjourney.com",
    category: "image",
    tags: ["아트워크", "Discord", "고품질", "상업적 사용"],
    free: false,
    popular: true,
    features: ["최고 수준의 예술적 품질", "캐릭터 일관성 유지", "다양한 스타일 프리셋", "업스케일링 및 변형", "상업적 사용 허가"],
    pros: ["이미지 품질과 예술성이 업계 최고", "활발한 커뮤니티와 풍부한 튜토리얼", "다양한 스타일 표현 가능"],
    cons: ["무료 플랜 없음", "Discord 기반이라 초보자에게 진입 장벽"],
    pricing: { paid: "Basic $10/월(200장), Standard $30/월(무제한 릴렉스), Pro $60/월" },
    useCases: ["광고·마케팅 비주얼 제작", "게임 콘셉트 아트", "소셜 미디어 이미지", "북 커버 디자인", "패션·제품 시각화"],
  },
  {
    id: "dalle3",
    name: "DALL·E 3",
    description: "OpenAI의 최신 이미지 생성 AI. 텍스트 설명을 정확하게 반영한 고품질 이미지를 생성합니다.",
    longDescription: "DALL·E 3는 OpenAI가 개발한 텍스트→이미지 생성 AI로, 텍스트 프롬프트를 정확하게 반영하는 능력이 핵심 강점입니다. ChatGPT Plus 구독자는 ChatGPT 대화 중에 바로 이미지를 생성할 수 있어 편의성이 높습니다. 이전 버전 대비 텍스트가 포함된 이미지 생성 능력이 크게 향상되었으며, 복잡한 장면 묘사도 정확하게 구현합니다. 안전 필터가 강력해 창작의 자유가 제한될 수 있지만, 상업적으로 안전한 이미지 생성에 적합합니다.",
    url: "https://openai.com/dall-e-3",
    category: "image",
    tags: ["OpenAI", "텍스트→이미지", "정확도", "ChatGPT 통합"],
    free: false,
    popular: true,
    features: ["프롬프트 정확도 높음", "ChatGPT 대화 내 이미지 생성", "이미지 내 텍스트 렌더링", "다양한 비율 지원", "API 제공"],
    pros: ["ChatGPT 사용자는 별도 가입 불필요", "프롬프트 의도 반영 정확도 우수", "API로 서비스 개발 가능"],
    cons: ["단독 구독 플랜 없음(ChatGPT Plus 필요)", "Midjourney 대비 예술성 낮음", "강한 안전 필터"],
    pricing: { paid: "ChatGPT Plus $20/월에 포함, API는 이미지당 $0.04~$0.12" },
    useCases: ["프레젠테이션용 커스텀 이미지", "블로그 썸네일", "제품 콘셉트 시각화", "교육 자료 삽화", "앱·웹 UI 목업"],
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    description: "오픈소스 이미지 생성 모델. 로컬 실행 가능하며 다양한 커스터마이징이 가능합니다.",
    longDescription: "Stable Diffusion은 Stability AI가 개발하고 오픈소스로 공개한 이미지 생성 모델입니다. 로컬 PC에서 직접 실행할 수 있어 인터넷 연결 없이 이미지를 무제한으로 생성할 수 있습니다. Civitai 등 커뮤니티에서 수만 개의 파인튜닝 모델을 무료로 다운로드해 특정 스타일에 최적화된 이미지를 생성할 수 있습니다. AUTOMATIC1111, ComfyUI 등 오픈소스 GUI를 통해 ControlNet, img2img 등 고급 기능을 활용할 수 있어 전문 사용자에게 강력한 도구입니다.",
    url: "https://stability.ai",
    category: "image",
    tags: ["오픈소스", "로컬 실행", "커스터마이징", "무료"],
    free: true,
    features: ["완전 무료·오픈소스", "로컬 PC 실행(GPU 필요)", "무제한 이미지 생성", "수만 개 커뮤니티 모델", "ControlNet 정밀 제어"],
    pros: ["한 번 설치 후 무제한 무료 사용", "프라이버시 보호(로컬 실행)", "커스터마이징 한계 없음"],
    cons: ["설치 및 설정이 복잡함", "고성능 GPU 필요(VRAM 8GB 이상 권장)", "초보자 진입 장벽 높음"],
    pricing: { free: "오픈소스 무료(로컬 실행), DreamStudio 클라우드는 크레딧 구매" },
    useCases: ["대량 이미지 생성 파이프라인", "특정 스타일 캐릭터 생성", "인물 사진 스타일 변환", "프라이버시가 중요한 이미지 작업", "AI 아트 연구"],
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    description: "Adobe의 AI 이미지 생성 도구. Photoshop, Illustrator와 통합되어 창작 워크플로우를 강화합니다.",
    longDescription: "Adobe Firefly는 Adobe가 개발한 생성형 AI로, Photoshop의 '생성형 채우기', Illustrator의 '벡터화' 등 기존 Adobe 도구에 자연스럽게 통합되어 있습니다. 상업적으로 안전한 이미지 생성을 위해 Adobe Stock 라이선스 콘텐츠와 저작권이 만료된 이미지만 학습 데이터로 사용했습니다. 따라서 생성된 이미지는 상업적 목적으로 안전하게 사용할 수 있습니다. Photoshop 내에서 배경 확장, 객체 제거, 요소 추가 등 편집 작업에 AI를 활용할 수 있어 디자이너와 사진작가에게 특히 유용합니다.",
    url: "https://firefly.adobe.com",
    category: "image",
    tags: ["Adobe 통합", "상업 라이선스", "제너레이티브 필", "크리에이티브"],
    free: true,
    popular: true,
    features: ["Photoshop·Illustrator 완전 통합", "상업적 사용 안전 보장", "생성형 채우기·확장", "텍스트 효과 생성", "벡터 이미지 생성"],
    pros: ["Adobe 제품 사용자에게 매우 편리", "상업적 라이선스 문제 없음", "무료 크레딧으로 시작 가능"],
    cons: ["Adobe 생태계 외 사용 불편", "Midjourney 대비 예술적 자유도 낮음"],
    pricing: { free: "월 25 크레딧 무료", paid: "Adobe Creative Cloud 구독에 포함, 추가 크레딧 구매 가능" },
    useCases: ["Photoshop 사진 편집 보조", "상업 광고 이미지 제작", "브랜드 비주얼 아이덴티티", "SNS 콘텐츠 디자인", "제품 사진 배경 교체"],
  },
  {
    id: "ideogram",
    name: "Ideogram",
    description: "텍스트 렌더링에 강점을 가진 AI 이미지 생성 도구. 로고, 포스터 디자인에 특히 유용합니다.",
    longDescription: "Ideogram은 AI 이미지 생성 도구 중 텍스트 렌더링 능력이 가장 뛰어난 서비스입니다. 기존 AI 이미지 생성 도구들이 이미지 안에 텍스트를 제대로 구현하지 못하는 한계를 극복해, 포스터·배너·로고 등 텍스트가 포함된 디자인 작업에 특화되어 있습니다. Magic Prompt 기능으로 간단한 설명만 입력해도 완성도 높은 프롬프트를 자동 완성해주며, 다양한 스타일과 종횡비를 지원합니다. 무료 플랜도 일정량의 이미지 생성을 지원해 부담 없이 시작할 수 있습니다.",
    url: "https://ideogram.ai",
    category: "image",
    tags: ["텍스트 렌더링", "로고", "포스터", "디자인"],
    free: true,
    features: ["업계 최고 텍스트 렌더링 정확도", "Magic Prompt 자동 완성", "다양한 디자인 스타일", "종횡비 자유 설정", "이미지 편집 기능"],
    pros: ["이미지 안 텍스트 구현이 압도적으로 우수", "무료 플랜 제공", "포스터·썸네일 제작에 최적"],
    cons: ["사실적 사진 생성은 Midjourney보다 약함", "고급 편집 기능 부족"],
    pricing: { free: "하루 10회 슬로우 생성", paid: "Basic $7/월, Plus $16/월 — 빠른 생성, 우선 처리" },
    useCases: ["유튜브 썸네일 제작", "이벤트 포스터·배너", "로고 초안 생성", "SNS 카드뉴스", "책 표지 디자인"],
  },
  {
    id: "leonardo-ai",
    name: "Leonardo AI",
    description: "게임 에셋, 캐릭터 디자인에 특화된 AI 이미지 생성 플랫폼. 다양한 파인튜닝 모델을 제공합니다.",
    longDescription: "Leonardo AI는 게임 개발자와 크리에이터를 위한 AI 이미지 생성 플랫폼입니다. 게임 에셋, 캐릭터, 배경, 아이템 등 게임 제작에 필요한 비주얼을 빠르게 생성할 수 있습니다. 자체 파인튜닝 기능으로 특정 스타일의 모델을 학습시켜 일관된 캐릭터와 세계관을 유지할 수 있습니다. 실시간 캔버스 편집, 모션 생성, 3D 텍스처 생성 등 고급 기능도 제공하며, 커뮤니티에서 공유된 다양한 파인튜닝 모델을 무료로 활용할 수 있습니다.",
    url: "https://leonardo.ai",
    category: "image",
    tags: ["게임 에셋", "캐릭터", "파인튜닝", "크리에이티브"],
    free: true,
    features: ["게임 에셋 특화 생성", "커스텀 모델 파인튜닝", "실시간 캔버스 편집", "모션 이미지 생성", "3D 텍스처 생성"],
    pros: ["게임·애니메이션 스타일 이미지에 강점", "무료 플랜이 넉넉함(일 150 토큰)", "파인튜닝으로 일관된 캐릭터 유지"],
    cons: ["일반 사실적 사진 생성은 다소 약함", "인터페이스 다소 복잡"],
    pricing: { free: "하루 150 토큰 무료", paid: "Apprentice $10/월, Artisan $24/월, Maestro $48/월" },
    useCases: ["게임 캐릭터 및 배경 디자인", "웹툰·만화 스타일 이미지", "NFT 아트 제작", "애니메이션 콘셉트 아트", "인디게임 에셋 제작"],
  },
  {
    id: "canva-ai",
    name: "Canva AI",
    description: "Canva에 통합된 AI 기능. 이미지 생성, 배경 제거, 마법 편집 등 디자인 작업을 자동화합니다.",
    longDescription: "Canva AI는 세계 1억 7000만 명이 사용하는 디자인 플랫폼 Canva에 통합된 AI 기능 모음입니다. '마법 미디어'로 텍스트 프롬프트에서 이미지를 생성하고, '배경 제거'로 클릭 한 번에 배경을 지우며, '마법 편집'으로 이미지 요소를 교체할 수 있습니다. AI 프레젠테이션 생성 기능은 주제만 입력하면 슬라이드 전체를 자동으로 만들어줍니다. 디자인 전문 지식 없이도 전문가 수준의 결과물을 만들 수 있어 초보자에게 특히 유용합니다.",
    url: "https://www.canva.com/ai-image-generator",
    category: "image",
    tags: ["디자인 통합", "배경 제거", "템플릿", "손쉬운 사용"],
    free: true,
    features: ["텍스트→이미지 생성", "원클릭 배경 제거", "AI 프레젠테이션 자동 생성", "마법 편집·확장", "AI 글쓰기 보조"],
    pros: ["디자인 초보자도 쉽게 사용", "Canva 디자인 도구와 완벽 연동", "무료 플랜도 기본 AI 기능 제공"],
    cons: ["전문 이미지 생성 도구보다 품질 낮음", "AI 기능 대부분 Pro 구독 필요"],
    pricing: { free: "기본 AI 기능 제한적 무료", paid: "Pro $15/월 — 모든 AI 기능, 프리미엄 템플릿 10만 개+" },
    useCases: ["SNS 게시물 디자인", "프레젠테이션 제작", "마케팅 배너 제작", "유튜브 썸네일", "명함·포스터 디자인"],
  },

  // === VIDEO ===
  {
    id: "runway",
    name: "Runway",
    description: "전문적인 AI 비디오 생성 및 편집 플랫폼. Gen-2로 텍스트/이미지를 고품질 비디오로 변환합니다.",
    longDescription: "Runway는 할리우드 영화 제작팀도 사용하는 전문 AI 비디오 플랫폼입니다. Gen-3 Alpha 모델로 텍스트 또는 이미지를 최대 10초의 고품질 비디오로 변환할 수 있으며, 실제 같은 움직임과 세밀한 디테일이 특징입니다. 비디오 편집, 배경 제거, 인페인팅, 오디오 분리 등 전문 편집 도구도 제공합니다. 영화 '에브리씽 에브리웨어 올 앳 원스' 등의 제작에 활용될 만큼 전문가들의 신뢰를 받고 있습니다.",
    url: "https://runwayml.com",
    category: "video",
    tags: ["비디오 생성", "Gen-3", "영상 편집", "크리에이티브"],
    free: true,
    popular: true,
    features: ["텍스트·이미지→비디오 생성", "전문 비디오 편집 도구", "배경 제거·인페인팅", "모션 브러시 제어", "팀 협업 기능"],
    pros: ["업계 최고 수준의 비디오 품질", "편집 도구까지 올인원 제공", "전문 크리에이터들의 검증"],
    cons: ["무료 플랜 크레딧 매우 제한적", "비디오 길이 최대 10초(Gen-3)"],
    pricing: { free: "125 크레딧 1회 제공", paid: "Standard $15/월(625크레딧), Pro $35/월(2250크레딧)" },
    useCases: ["단편 영화·광고 영상 제작", "뮤직비디오 비주얼", "소셜 미디어 숏폼 콘텐츠", "제품 데모 영상", "영화 특수효과 프리비즈"],
  },
  {
    id: "sora",
    name: "Sora",
    description: "OpenAI의 혁신적인 텍스트→비디오 AI. 최대 60초의 놀라운 사실적 영상을 생성합니다.",
    longDescription: "Sora는 OpenAI가 2024년 출시한 텍스트→비디오 생성 AI로, 물리 법칙을 이해하고 현실적인 장면을 구현하는 능력이 업계를 놀라게 했습니다. 텍스트 설명만으로 최대 1080p, 60초 길이의 고품질 영상을 생성할 수 있으며, 동일한 장면을 다양한 카메라 각도로 표현하거나 이미지를 영상으로 변환하는 기능도 제공합니다. ChatGPT Plus 구독자는 Sora를 바로 사용할 수 있어 접근성이 높습니다.",
    url: "https://sora.com",
    category: "video",
    tags: ["텍스트→비디오", "OpenAI", "고품질", "사실적"],
    free: false,
    popular: true,
    features: ["최대 60초 영상 생성", "1080p 고해상도 지원", "이미지→영상 변환", "다양한 화면 비율", "스토리보드 기능"],
    pros: ["물리적 사실성이 업계 최고 수준", "ChatGPT 연동으로 접근성 높음", "긴 영상 생성 가능"],
    cons: ["유료 구독 필요", "생성 속도가 느릴 수 있음", "일부 복잡한 동작 구현 한계"],
    pricing: { paid: "ChatGPT Plus $20/월 포함, Pro $200/월 — 무제한 생성" },
    useCases: ["광고·마케팅 영상 프로토타입", "영화 콘셉트 영상", "교육·강의 자료 영상화", "SNS 바이럴 콘텐츠", "스토리보드 시각화"],
  },
  {
    id: "pika",
    name: "Pika",
    description: "텍스트와 이미지로 비디오를 생성하는 AI. 쉬운 인터페이스로 빠르게 애니메이션을 만들 수 있습니다.",
    longDescription: "Pika는 사용자 친화적인 인터페이스로 빠르게 인기를 얻은 AI 비디오 생성 플랫폼입니다. 텍스트 설명이나 이미지를 입력하면 3~4초 만에 영상을 생성해주는 속도가 큰 장점입니다. 립싱크 기능으로 인물 사진에 음성을 입히거나, 기존 영상에 새로운 요소를 추가하는 편집 기능도 제공합니다. 디스코드와 웹 모두에서 사용 가능하며, 무료 플랜으로도 충분한 양의 영상을 생성할 수 있어 처음 AI 비디오를 경험하는 사람에게 적합합니다.",
    url: "https://pika.art",
    category: "video",
    tags: ["애니메이션", "이미지→비디오", "빠른 생성"],
    free: true,
    features: ["빠른 영상 생성(3~4초)", "이미지→비디오 변환", "립싱크 기능", "영상 편집 및 요소 추가", "다양한 비율 지원"],
    pros: ["생성 속도가 빠름", "무료 플랜이 충분히 넉넉함", "초보자도 쉽게 사용"],
    cons: ["영상 품질은 Runway·Sora보다 낮음", "최대 영상 길이 제한"],
    pricing: { free: "월 150크레딧 무료", paid: "Basic $8/월, Standard $28/월, Unlimited $58/월" },
    useCases: ["SNS 릴스·쇼츠 제작", "제품 애니메이션 광고", "사진 살아있게 만들기", "간단한 바이럴 영상", "스토리텔링 영상"],
  },
  {
    id: "heygen",
    name: "HeyGen",
    description: "AI 아바타로 마케팅 비디오를 생성하는 플랫폼. 100개 이상의 언어로 비디오 번역도 지원합니다.",
    longDescription: "HeyGen은 AI 아바타와 음성 합성 기술을 결합해 카메라 없이도 전문적인 발표 영상을 만들 수 있는 플랫폼입니다. 100가지 이상의 AI 아바타 중 선택하거나 본인 얼굴로 개인 아바타를 만들 수 있습니다. 가장 주목받는 기능은 '영상 번역'으로, 기존 영상을 업로드하면 입 모양까지 맞춰가며 100개 이상의 언어로 자동 더빙해줍니다. 온보딩 영상, 제품 설명, 교육 자료 등 반복 제작이 필요한 기업 영상에 특히 효과적입니다.",
    url: "https://www.heygen.com",
    category: "video",
    tags: ["AI 아바타", "비디오 번역", "마케팅", "다국어"],
    free: true,
    features: ["100+ AI 아바타", "개인 맞춤 아바타 생성", "100+ 언어 자동 번역·더빙", "텍스트→영상 생성", "팀 협업 기능"],
    pros: ["카메라 없이 전문 발표 영상 제작", "다국어 번역 더빙 기능이 뛰어남", "기업 영상 제작 비용 절감"],
    cons: ["무료 플랜은 워터마크 포함", "AI 아바타가 부자연스러울 수 있음"],
    pricing: { free: "1크레딧(1분 영상) 무료 체험", paid: "Creator $29/월, Business $89/월" },
    useCases: ["제품 소개 영상", "온보딩 트레이닝 자료", "다국어 마케팅 영상", "유튜브 콘텐츠 현지화", "e-Learning 강의"],
  },
  {
    id: "synthesia",
    name: "Synthesia",
    description: "AI 아바타 기반 기업용 비디오 제작 플랫폼. 텍스트만으로 전문적인 트레이닝 영상을 만듭니다.",
    longDescription: "Synthesia는 Fortune 500 기업들이 사용하는 엔터프라이즈급 AI 영상 제작 플랫폼입니다. 230개 이상의 AI 아바타와 140개 이상의 언어를 지원하며, 스크립트만 입력하면 전문 발표자가 등장하는 영상을 자동으로 생성합니다. 엄격한 보안 정책과 GDPR 준수로 기업 환경에 적합하며, LMS(학습 관리 시스템) 연동, SCORM 내보내기 등 기업 교육 도구와의 통합을 지원합니다. BBC, Reuters, Zoom 등 주요 기업들이 사용하고 있습니다.",
    url: "https://www.synthesia.io",
    category: "video",
    tags: ["기업용", "AI 아바타", "트레이닝 영상", "다국어"],
    free: false,
    features: ["230+ 다양한 AI 아바타", "140+ 언어 지원", "LMS 연동 및 SCORM 내보내기", "엔터프라이즈 보안", "브랜드 커스터마이징"],
    pros: ["기업 환경에 최적화된 보안·관리", "가장 자연스러운 AI 아바타", "LMS 통합으로 교육 시스템과 연동"],
    cons: ["가격이 높음", "개인 사용자보다 기업 대상"],
    pricing: { paid: "Starter $22/월(10분), Creator $67/월(30분), Enterprise 별도 문의" },
    useCases: ["직원 온보딩·교육 영상", "규정 준수 트레이닝", "제품 튜토리얼", "글로벌 기업 커뮤니케이션", "e-Learning 콘텐츠"],
  },
  {
    id: "kling",
    name: "Kling AI",
    description: "중국 Kuaishou가 개발한 AI 비디오 생성 도구. 2분 길이의 고품질 비디오 생성이 가능합니다.",
    longDescription: "Kling AI는 중국 최대 숏폼 플랫폼 Kuaishou가 개발한 AI 비디오 생성 도구로, 최대 2분 길이의 영상을 생성할 수 있는 것이 최대 강점입니다. 1080p 해상도와 30fps를 지원하며, 텍스트 또는 이미지를 입력으로 사용할 수 있습니다. 물리 시뮬레이션 능력이 뛰어나 물, 불, 연기 등 자연 현상을 사실적으로 구현합니다. 글로벌 버전은 국제 사용자도 이용할 수 있으며, 경쟁사 대비 합리적인 가격으로 긴 영상을 생성할 수 있어 주목받고 있습니다.",
    url: "https://klingai.com",
    category: "video",
    tags: ["긴 비디오", "고품질", "텍스트→비디오"],
    free: true,
    features: ["최대 2분 영상 생성", "1080p 30fps 지원", "물리 시뮬레이션 우수", "이미지→영상 변환", "카메라 움직임 제어"],
    pros: ["업계 최장 2분 영상 생성", "물리적 사실감이 뛰어남", "합리적인 가격"],
    cons: ["생성 속도가 느릴 수 있음", "서버가 해외에 있어 접속 속도 이슈"],
    pricing: { free: "일 66크레딧 무료", paid: "Standard $10/월, Pro $35/월" },
    useCases: ["긴 스토리 광고 영상", "뮤직비디오 제작", "영화 단편 제작", "자연 다큐멘터리 스타일 영상", "제품 시연 영상"],
  },

  // === CODING ===
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description: "GitHub과 OpenAI가 개발한 AI 코딩 어시스턴트. VS Code에서 실시간 코드 제안과 자동 완성을 제공합니다.",
    longDescription: "GitHub Copilot은 GitHub과 OpenAI가 공동 개발한 AI 코딩 어시스턴트로, 전 세계 개발자들이 가장 많이 사용하는 AI 코딩 도구입니다. VS Code, JetBrains, Neovim 등 주요 에디터에서 실시간 코드 자동 완성, 함수 생성, 주석→코드 변환을 지원합니다. Copilot Chat은 코드에 대한 질문, 설명, 리팩토링 제안을 대화 형식으로 제공합니다. GitHub 저장소의 방대한 코드를 학습해 다양한 언어와 프레임워크에서 높은 정확도를 보여주며, 개발 생산성을 평균 55% 향상시킨다는 연구 결과가 있습니다.",
    url: "https://github.com/features/copilot",
    category: "coding",
    tags: ["VS Code", "자동 완성", "GitHub 통합", "페어 프로그래밍"],
    free: false,
    popular: true,
    features: ["실시간 코드 자동 완성", "함수·클래스 전체 생성", "Copilot Chat 대화형 보조", "테스트 코드 자동 생성", "보안 취약점 감지"],
    pros: ["가장 널리 사용되는 코딩 AI", "다양한 에디터 지원", "GitHub 워크플로우와 완벽 통합"],
    cons: ["유료(학생·오픈소스는 무료)", "인터넷 연결 필수", "간혹 부정확한 코드 제안"],
    pricing: { free: "학생·인증 오픈소스 기여자 무료", paid: "Individual $10/월, Business $19/월/인" },
    useCases: ["반복적인 코드 패턴 자동화", "새로운 언어·프레임워크 빠른 학습", "단위 테스트 자동 생성", "코드 리뷰 및 리팩토링", "API 연동 코드 작성"],
  },
  {
    id: "cursor",
    name: "Cursor",
    description: "AI 네이티브 코드 에디터. Claude, GPT-4 기반으로 코드베이스 전체를 이해하고 편집합니다.",
    longDescription: "Cursor는 VS Code를 기반으로 만들어진 AI 네이티브 코드 에디터입니다. 단순한 자동 완성을 넘어, 프로젝트 전체 코드베이스를 분석해 문맥을 이해한 수정을 제안합니다. 'Cmd+K'로 자연어로 코드 편집을 지시하고, 'Composer' 기능으로 여러 파일에 걸친 복잡한 변경 사항을 한 번에 처리할 수 있습니다. Claude Sonnet, GPT-4o, Gemini 등 최신 AI 모델을 선택해 사용할 수 있으며, 코드베이스 검색·참조 기능으로 대규모 프로젝트에서도 정확한 제안을 제공합니다.",
    url: "https://cursor.sh",
    category: "coding",
    tags: ["AI 에디터", "코드베이스 분석", "자동 편집", "Claude"],
    free: true,
    popular: true,
    features: ["코드베이스 전체 컨텍스트 이해", "자연어로 코드 편집 지시", "멀티파일 Composer 편집", "여러 AI 모델 선택", "터미널 AI 보조"],
    pros: ["코드베이스 전체를 이해한 정확한 수정", "VS Code 익스텐션 그대로 사용 가능", "강력한 멀티파일 편집"],
    cons: ["코드를 외부 서버로 전송(프라이버시)", "무료 플랜은 사용량 제한"],
    pricing: { free: "2주 Pro 체험 후 기본 무료(제한적)", paid: "Pro $20/월 — 500 fast 요청, 무제한 slow 요청" },
    useCases: ["레거시 코드 리팩토링", "새 기능 빠른 개발", "버그 디버깅 자동화", "코드 문서화", "프로젝트 전체 구조 파악"],
  },
  {
    id: "v0",
    name: "v0 by Vercel",
    description: "텍스트 설명으로 React UI 컴포넌트를 생성하는 AI. shadcn/ui 기반의 코드를 즉시 생성합니다.",
    longDescription: "v0는 Vercel이 만든 AI UI 생성 도구로, 텍스트로 원하는 UI를 설명하면 즉시 React 컴포넌트 코드를 생성합니다. shadcn/ui, Tailwind CSS 기반의 깔끔하고 실제로 사용 가능한 코드를 생성하며, 생성된 컴포넌트를 채팅으로 수정하거나 Next.js 프로젝트에 바로 붙여넣을 수 있습니다. 디자인 목업 이미지를 업로드하면 그에 맞는 코드를 생성하는 기능도 있어 디자이너와 개발자 사이의 핸드오프를 가속화합니다.",
    url: "https://v0.dev",
    category: "coding",
    tags: ["UI 생성", "React", "shadcn/ui", "Vercel"],
    free: true,
    popular: true,
    features: ["텍스트→React 컴포넌트 생성", "shadcn/ui·Tailwind 기반", "이미지→코드 변환", "대화형 수정", "Next.js 직접 배포"],
    pros: ["프론트엔드 개발 속도 대폭 향상", "실제 사용 가능한 코드 품질", "Vercel 배포와 완벽 연동"],
    cons: ["React·Next.js 특화(다른 프레임워크 한계)", "복잡한 비즈니스 로직은 직접 작성 필요"],
    pricing: { free: "월 200크레딧 무료", paid: "Premium $20/월 — 5000크레딧, 우선 처리" },
    useCases: ["랜딩 페이지 빠른 프로토타입", "대시보드 UI 생성", "폼·테이블 컴포넌트 제작", "디자인 목업 코드화", "UI 컴포넌트 라이브러리 구축"],
  },
  {
    id: "bolt",
    name: "Bolt.new",
    description: "브라우저에서 풀스택 앱을 빠르게 프로토타이핑하는 AI 개발 도구. StackBlitz 기반으로 실행됩니다.",
    longDescription: "Bolt.new는 StackBlitz가 만든 브라우저 기반 AI 풀스택 개발 도구입니다. 자연어로 앱 아이디어를 설명하면 프론트엔드부터 백엔드, 데이터베이스 설정까지 완전한 풀스택 앱을 생성합니다. 브라우저 안에서 직접 코드를 실행하고 수정할 수 있어 로컬 환경 설정이 전혀 필요 없습니다. React, Vue, Svelte, Next.js, Remix 등 다양한 프레임워크를 지원하며, npm 패키지도 브라우저에서 바로 설치해 사용할 수 있습니다.",
    url: "https://bolt.new",
    category: "coding",
    tags: ["풀스택", "프로토타이핑", "StackBlitz", "브라우저 IDE"],
    free: true,
    features: ["브라우저에서 풀스택 앱 실행", "자연어로 앱 생성", "다양한 프레임워크 지원", "npm 패키지 즉시 설치", "Netlify·Vercel 원클릭 배포"],
    pros: ["로컬 환경 설정 불필요", "아이디어→실행 가능한 앱 속도 빠름", "초보자도 풀스택 개발 가능"],
    cons: ["복잡한 대규모 앱 개발에는 한계", "무료 플랜 토큰 제한"],
    pricing: { free: "일정 토큰 무료", paid: "Basic $20/월, Pro $50/월" },
    useCases: ["스타트업 MVP 빠른 프로토타입", "해커톤 프로젝트", "클라이언트 데모 앱", "학습용 풀스택 예제", "아이디어 검증용 앱"],
  },
  {
    id: "tabnine",
    name: "Tabnine",
    description: "프라이버시 중심의 AI 코드 완성 도구. 로컬 실행 옵션으로 코드를 외부 서버에 전송하지 않습니다.",
    longDescription: "Tabnine은 개발자 프라이버시와 보안을 최우선으로 하는 AI 코드 완성 도구입니다. 로컬 모델 실행 옵션으로 코드가 외부 서버에 전혀 전송되지 않아 금융, 의료, 정부 등 보안이 중요한 환경에서 안전하게 사용할 수 있습니다. 개인 코드베이스를 학습해 팀의 코딩 스타일과 패턴에 맞춘 제안을 제공하며, VS Code, JetBrains, Eclipse 등 주요 에디터를 지원합니다. 80개 이상의 프로그래밍 언어를 지원합니다.",
    url: "https://www.tabnine.com",
    category: "coding",
    tags: ["프라이버시", "로컬 실행", "코드 완성", "기업용"],
    free: true,
    features: ["로컬 모델 실행(코드 외부 전송 없음)", "팀 코드 스타일 학습", "80+ 언어 지원", "주요 에디터 플러그인", "기업 보안 정책 준수"],
    pros: ["보안이 중요한 환경에 최적", "팀 코딩 스타일에 맞춤화 가능", "안정적이고 빠른 자동 완성"],
    cons: ["Copilot·Cursor보다 AI 기능 제한적", "고급 기능은 유료"],
    pricing: { free: "기본 자동 완성 무료", paid: "Pro $12/월, Enterprise 별도 문의(로컬 모델 포함)" },
    useCases: ["금융·의료 기관 개발 환경", "사내 코드베이스 보안 유지", "팀 코딩 표준 자동 적용", "오프라인 개발 환경", "기업 IP 보호"],
  },
  {
    id: "codeium",
    name: "Codeium",
    description: "무료 AI 코딩 어시스턴트. 70개 이상의 언어와 40개 이상의 에디터를 지원하는 빠른 자동 완성 도구.",
    longDescription: "Codeium은 개인 개발자에게 완전 무료로 강력한 AI 코딩 어시스턴트를 제공하는 서비스입니다. 70개 이상의 프로그래밍 언어와 40개 이상의 에디터·IDE를 지원해 거의 모든 개발 환경에서 사용할 수 있습니다. Codeium Chat 기능으로 코드에 대한 질문, 버그 수정, 리팩토링 제안을 받을 수 있으며, 코드 설명 기능으로 복잡한 코드를 이해하는 데도 도움이 됩니다. GitHub Copilot의 무료 대안으로 많이 사용됩니다.",
    url: "https://codeium.com",
    category: "coding",
    tags: ["무료", "다국어 지원", "빠른 응답", "다양한 에디터"],
    free: true,
    features: ["완전 무료 개인 사용", "70+ 언어, 40+ 에디터 지원", "Codeium Chat 대화형 보조", "코드 설명 기능", "빠른 응답 속도"],
    pros: ["개인 사용자 완전 무료", "매우 넓은 언어·에디터 지원", "GitHub Copilot의 훌륭한 무료 대안"],
    cons: ["기업 플랜은 유료", "Copilot·Cursor 대비 고급 기능 부족"],
    pricing: { free: "개인 사용자 무제한 무료", paid: "Teams $12/월/인, Enterprise 별도 문의" },
    useCases: ["개인 사이드 프로젝트 개발", "코딩 학습 및 연습", "비용 없이 AI 코딩 어시스턴트 체험", "다양한 언어 개발", "오픈소스 프로젝트 기여"],
  },
  {
    id: "replit-ai",
    name: "Replit AI",
    description: "Replit IDE에 통합된 AI. 코드 생성, 디버깅, 설명을 제공하며 클라우드에서 바로 실행됩니다.",
    longDescription: "Replit AI는 클라우드 기반 IDE Replit에 통합된 AI 개발 도구입니다. 브라우저에서 코드를 작성하고 바로 실행할 수 있어 로컬 환경 설정이 필요 없으며, AI가 코드 생성, 디버깅, 오류 설명, 코드 변환을 도와줍니다. Ghostwriter Complete는 실시간 자동 완성을, Ghostwriter Chat은 대화형 코딩 보조를 제공합니다. 50개 이상의 프로그래밍 언어를 지원하며, 교육 목적으로 많이 사용됩니다. Replit Deployments로 만든 앱을 바로 배포할 수도 있습니다.",
    url: "https://replit.com",
    category: "coding",
    tags: ["클라우드 IDE", "디버깅", "코드 실행", "교육"],
    free: true,
    features: ["클라우드 브라우저 IDE", "AI 코드 생성·디버깅", "50+ 언어 즉시 실행", "원클릭 앱 배포", "실시간 협업"],
    pros: ["환경 설정 없이 즉시 코딩 시작", "교육 환경에 최적화", "앱 개발부터 배포까지 한 곳에서"],
    cons: ["로컬 IDE보다 성능 제한", "AI 기능 대부분 유료", "인터넷 연결 필수"],
    pricing: { free: "기본 IDE 무료(AI 기능 제한)", paid: "Core $20/월 — 전체 AI 기능, 더 많은 컴퓨팅 자원" },
    useCases: ["코딩 교육 및 학습", "빠른 코드 실험·프로토타입", "팀 코딩 인터뷰 연습", "서버 없는 봇·스크립트 실행", "학생 과제 개발"],
  },

  // === MUSIC ===
  {
    id: "suno",
    name: "Suno AI",
    description: "텍스트 프롬프트만으로 완성된 노래를 만드는 AI. 가사, 멜로디, 보컬까지 자동으로 생성합니다.",
    longDescription: "Suno AI는 텍스트 설명만으로 가사, 멜로디, 보컬, 악기 편성까지 완성된 노래를 생성하는 혁신적인 AI 음악 플랫폼입니다. '밝은 느낌의 K-pop 사랑 노래'처럼 간단한 설명만 입력하면 2분 내외의 완성된 곡을 즉시 만들어냅니다. 팝, 록, 힙합, 클래식, 재즈, 트로트 등 거의 모든 장르를 지원하며, 직접 가사를 작성해 원하는 내용의 노래를 만들 수도 있습니다. 무료 플랜으로도 하루 10곡을 생성할 수 있어 부담 없이 시작할 수 있습니다.",
    url: "https://suno.ai",
    category: "music",
    tags: ["노래 생성", "가사", "보컬", "다양한 장르"],
    free: true,
    popular: true,
    features: ["텍스트→완성 노래 생성", "직접 가사 입력 가능", "다양한 장르·스타일 지원", "2분 이상 노래 생성", "상업적 사용(유료 플랜)"],
    pros: ["음악 지식 없이도 완성된 노래 제작", "한국어 포함 다국어 가사 지원", "무료 플랜도 충분히 활용 가능"],
    cons: ["저작권 및 상업적 사용에 주의 필요(유료 플랜만)", "세밀한 편집 기능 부족"],
    pricing: { free: "하루 50크레딧(약 10곡) 무료", paid: "Pro $8/월 — 하루 2500크레딧, 상업적 사용 허가" },
    useCases: ["개인 취향 맞춤 음악 생성", "유튜브 배경음악", "생일·기념일 맞춤 노래", "광고 징글 제작", "음악 아이디어 스케치"],
  },
  {
    id: "udio",
    name: "Udio",
    description: "고품질 음악을 생성하는 AI 플랫폼. 다양한 장르와 스타일의 음악을 쉽게 만들 수 있습니다.",
    longDescription: "Udio는 Google DeepMind 출신 연구진이 설립한 AI 음악 생성 플랫폼으로, 전문 음악가 수준의 음질과 세밀한 스타일 표현이 강점입니다. 장르, 악기, 무드, BPM 등 다양한 파라미터로 음악을 정밀하게 제어할 수 있으며, 생성된 음악을 구간별로 연장하거나 편집하는 기능도 제공합니다. Suno와 함께 AI 음악 생성 시장을 선도하며, 특히 전자음악, 앰비언트, 팝 등의 장르에서 뛰어난 품질을 보여줍니다.",
    url: "https://www.udio.com",
    category: "music",
    tags: ["고품질 음악", "다양한 장르", "음악 생성"],
    free: true,
    popular: true,
    features: ["전문가 수준 음질", "세밀한 파라미터 제어", "음악 구간 연장·편집", "가사 직접 입력", "다양한 장르·스타일"],
    pros: ["음질이 매우 높음", "세밀한 음악 스타일 제어 가능", "무료 플랜 제공"],
    cons: ["Suno보다 인터페이스 복잡", "상업적 사용 정책 확인 필요"],
    pricing: { free: "월 100크레딧 무료", paid: "Standard $10/월, Pro $30/월 — 더 많은 크레딧, 상업적 사용" },
    useCases: ["유튜브·팟캐스트 배경음악", "게임 사운드트랙", "앨범 아이디어 스케치", "음악 프로듀서 작업 보조", "광고 음악 제작"],
  },
  {
    id: "mubert",
    name: "Mubert",
    description: "AI로 로열티 프리 배경음악을 생성하는 플랫폼. 영상, 팟캐스트, 게임용 음악에 최적화되어 있습니다.",
    longDescription: "Mubert는 콘텐츠 크리에이터를 위한 AI 배경음악 생성 플랫폼입니다. 무드, 장르, 영상 길이를 입력하면 해당 콘텐츠에 딱 맞는 로열티 프리 배경음악을 즉시 생성합니다. YouTube, Twitch, 팟캐스트, 앱 등 다양한 플랫폼에서 저작권 문제 없이 사용할 수 있습니다. API를 제공해 개발자가 앱·게임에 동적으로 음악을 통합할 수 있으며, 생성된 모든 음악은 Mubert 플랫폼 아티스트들의 음원을 AI가 조합해 만들기 때문에 독창적입니다.",
    url: "https://mubert.com",
    category: "music",
    tags: ["배경음악", "로열티 프리", "영상용", "API 제공"],
    free: true,
    features: ["로열티 프리 배경음악 즉시 생성", "영상 길이에 맞춘 음악", "API로 앱·게임 통합", "무드·장르 선택", "스트리밍 라이선스"],
    pros: ["저작권 걱정 없는 로열티 프리", "영상 길이 자동 맞춤", "API로 서비스 통합 가능"],
    cons: ["창작성보다 기능성 위주", "고품질 오리지널 음악 원할 때는 부적합"],
    pricing: { free: "개인 비상업적 사용 무료", paid: "Creator $14/월, Pro $39/월 — 상업적 라이선스" },
    useCases: ["유튜브 영상 배경음악", "팟캐스트 인트로·아웃트로", "게임 앰비언트 음악", "앱 UI 사운드", "스트리머 방송 배경음악"],
  },
  {
    id: "soundraw",
    name: "Soundraw",
    description: "무드, 장르, 길이를 선택해 맞춤 음악을 생성하는 AI. 영상 크리에이터에게 인기 있는 도구입니다.",
    longDescription: "Soundraw는 일본에서 개발된 AI 음악 생성 플랫폼으로, 영상 크리에이터와 마케터에게 특히 인기가 높습니다. 무드(행복한, 슬픈, 긴장감 있는 등), 장르, 악기, 템포, 길이를 직관적으로 선택하면 맞춤 음악이 즉시 생성됩니다. 생성된 음악의 구간별 악기 구성, 에너지 수준을 세밀하게 편집할 수 있어 영상 편집자에게 편리합니다. 구독하면 생성한 모든 곡을 상업적으로 사용할 수 있으며, 음원 라이선스가 영구적으로 유지됩니다.",
    url: "https://soundraw.io",
    category: "music",
    tags: ["맞춤 음악", "크리에이터", "무드 설정", "로열티 프리"],
    free: true,
    features: ["무드·장르·길이 직관적 선택", "구간별 악기·에너지 편집", "영구 상업 라이선스", "Adobe Premiere 플러그인", "무제한 음악 생성(구독)"],
    pros: ["영상 편집자 친화적 인터페이스", "세밀한 음악 편집 가능", "영구 라이선스로 안심 사용"],
    cons: ["무료 플랜은 다운로드 불가", "완전한 창작 도구보다 배경음악 도구에 가까움"],
    pricing: { free: "음악 미리 듣기만 가능", paid: "Creator $16.99/월 — 무제한 생성·다운로드, 상업적 사용" },
    useCases: ["유튜브 영상 배경음악", "광고·홍보 영상 음악", "SNS 릴스·쇼츠 음악", "웨비나·프레젠테이션 배경음악", "게임 프로토타입 음악"],
  },
  {
    id: "aiva",
    name: "AIVA",
    description: "클래식과 영화 OST 스타일 음악 작곡에 특화된 AI. 게임, 광고, 영화 음악 제작에 활용됩니다.",
    longDescription: "AIVA(Artificial Intelligence Virtual Artist)는 룩셈부르크에서 개발된 AI 작곡 도구로, 2016년 세계 최초로 공식 저작권을 인정받은 AI 음악가입니다. 클래식, 영화 OST, 게임 음악 등 감성적이고 드라마틱한 음악 스타일에 특화되어 있습니다. 기존 악보나 스타일을 참조해 새로운 곡을 작곡할 수 있으며, MIDI 파일을 내보내 DAW에서 추가 편집도 가능합니다. 영화감독, 게임 개발자, 광고 제작사 등 전문 크리에이터들이 활용합니다.",
    url: "https://www.aiva.ai",
    category: "music",
    tags: ["작곡 AI", "클래식", "영화 OST", "게임 음악"],
    free: true,
    features: ["클래식·OST 스타일 특화 작곡", "MIDI 파일 내보내기", "악보 참조 작곡", "다양한 감정·분위기 설정", "DAW 연동"],
    pros: ["감성적이고 전문적인 오케스트라 음악", "MIDI 내보내기로 추가 편집 가능", "무료 플랜으로 기본 작곡 가능"],
    cons: ["팝·전자음악 등 현대 장르는 약함", "다른 AI 음악 도구보다 인터페이스 복잡"],
    pricing: { free: "월 3곡 무료(비상업적)", paid: "Standard €11/월, Pro €33/월 — 상업적 사용, 무제한 생성" },
    useCases: ["인디게임 배경음악 작곡", "단편 영화 OST", "광고 감성 음악", "유튜브 채널 시그니처 음악", "명상·힐링 음악 제작"],
  },

  // === OTHER ===
  {
    id: "eleven-labs",
    name: "ElevenLabs",
    description: "가장 자연스러운 AI 음성 합성 플랫폼. 음성 클로닝, 텍스트→음성 변환으로 콘텐츠 제작에 혁명을 일으킵니다.",
    longDescription: "ElevenLabs는 현존하는 AI 음성 합성 중 가장 자연스럽고 감성적인 음성을 생성하는 플랫폼입니다. 텍스트를 입력하면 인간과 구분하기 어려운 수준의 음성으로 변환해주며, 단 1분의 목소리 샘플만으로 특정 사람의 음성을 복제하는 '음성 클로닝' 기능이 있습니다. 29개 언어를 지원하며 한국어도 자연스럽게 구현합니다. 유튜버, 팟캐스터, 게임 개발자, 오디오북 제작자 등 콘텐츠 크리에이터들이 제작 비용과 시간을 크게 절감하는 데 활용하고 있습니다.",
    url: "https://elevenlabs.io",
    category: "other",
    tags: ["음성 합성", "음성 클로닝", "TTS", "다국어"],
    free: true,
    popular: true,
    features: ["인간에 가까운 자연스러운 TTS", "음성 클로닝(1분 샘플)", "29개 언어 지원(한국어 포함)", "감정·속도·피치 조절", "API 제공"],
    pros: ["업계 최고 수준의 음성 자연스러움", "한국어 품질 우수", "다양한 목소리 라이브러리"],
    cons: ["무료 플랜 월 10,000자 제한", "음성 클로닝 악용 윤리 우려"],
    pricing: { free: "월 10,000자 무료", paid: "Starter $5/월(30,000자), Creator $22/월(100,000자)" },
    useCases: ["유튜브 내레이션 자동 생성", "오디오북 제작", "팟캐스트 AI 진행자", "게임 NPC 음성", "다국어 콘텐츠 더빙"],
  },
  {
    id: "descript",
    name: "Descript",
    description: "텍스트 기반 오디오/비디오 편집 AI. 스크립트를 편집하면 미디어도 자동으로 편집되는 혁신적인 도구.",
    longDescription: "Descript는 오디오·비디오 편집의 패러다임을 바꾼 AI 편집 도구입니다. 음성을 자동으로 텍스트로 변환한 뒤, 텍스트를 편집하면 해당 음성·영상도 함께 편집되는 혁신적인 방식으로 작동합니다. '어..', '음...' 같은 필러 단어를 원클릭으로 모두 제거하고, 목소리를 유지한 채 스크립트를 수정하는 Overdub 기능으로 재녹음 없이 수정이 가능합니다. 팟캐스트, 유튜브 영상, 인터뷰 등 말하는 콘텐츠 편집에 특히 강력합니다.",
    url: "https://www.descript.com",
    category: "other",
    tags: ["오디오 편집", "비디오 편집", "팟캐스트", "자막"],
    free: true,
    features: ["텍스트 편집으로 미디어 편집", "자동 전사(STT)", "필러 단어 자동 제거", "Overdub 목소리 수정", "자막 자동 생성"],
    pros: ["편집 비전문가도 쉽게 사용", "팟캐스트·인터뷰 편집 시간 대폭 절감", "자막 자동 생성으로 접근성 향상"],
    cons: ["전문 비디오 편집 기능은 한계", "무료 플랜은 워터마크·제한"],
    pricing: { free: "1시간 전사 무료, 워터마크", paid: "Hobbyist $24/월, Creator $40/월, Business $80/월" },
    useCases: ["팟캐스트 편집 및 제작", "유튜브 인터뷰 편집", "웨비나 녹화 편집", "자막 자동 생성", "오디오 클립 제작"],
  },
  {
    id: "chatpdf",
    name: "ChatPDF",
    description: "PDF 문서와 대화하는 AI. 논문, 계약서, 보고서를 업로드하고 내용에 대해 질문하세요.",
    longDescription: "ChatPDF는 PDF 문서를 업로드하고 그 내용에 대해 자연어로 질문할 수 있는 AI 서비스입니다. 수백 페이지의 논문, 계약서, 재무 보고서, 법률 문서 등을 빠르게 분석하고 핵심 내용을 파악하는 데 탁월합니다. 문서 내 특정 정보를 찾거나, 요약, 비교, 번역을 요청할 수 있으며, 답변에는 해당 내용이 문서의 몇 페이지에 있는지 출처를 명시해줍니다. 학생, 연구자, 법률·금융 전문가들에게 필수적인 리서치 도구입니다.",
    url: "https://www.chatpdf.com",
    category: "other",
    tags: ["PDF 분석", "문서 QA", "논문 요약", "리서치"],
    free: true,
    features: ["PDF 업로드 후 대화형 질의응답", "페이지 출처 명시", "요약·번역 기능", "여러 PDF 동시 분석", "한국어 지원"],
    pros: ["긴 문서를 빠르게 파악 가능", "출처 페이지 표시로 신뢰성 높음", "무료 플랜으로 기본 사용 가능"],
    cons: ["무료 플랜은 파일 크기 제한", "복잡한 표·이미지 분석 한계"],
    pricing: { free: "하루 2개 PDF, 최대 120페이지", paid: "Plus $5/월 — 하루 50개 PDF, 2000페이지" },
    useCases: ["학술 논문 빠른 리뷰", "계약서 주요 조항 파악", "재무 보고서 분석", "법률 문서 이해", "교재 학습 보조"],
  },
  {
    id: "d-id",
    name: "D-ID",
    description: "사진을 말하는 아바타로 변환하는 AI. 디지털 휴먼 기술로 교육, 마케팅 영상을 쉽게 제작합니다.",
    longDescription: "D-ID는 정지된 사진에 AI 음성과 입 모양을 합성해 실제로 말하는 것처럼 보이게 만드는 디지털 휴먼 플랫폼입니다. 인물 사진만 있으면 카메라 없이도 자연스러운 발표 영상을 만들 수 있어 교육 콘텐츠, 기업 홍보 영상, 마케팅 자료 제작에 활발히 사용됩니다. 텍스트를 입력하거나 음성 파일을 업로드하면 해당 내용을 아바타가 말하는 영상이 생성됩니다. 100개 이상의 언어를 지원하며, API를 통해 대화형 AI 아바타 서비스를 개발할 수도 있습니다.",
    url: "https://www.d-id.com",
    category: "other",
    tags: ["디지털 휴먼", "아바타", "교육 영상", "마케팅"],
    free: true,
    features: ["사진→말하는 아바타 변환", "텍스트·음성 파일 입력", "100+ 언어 지원", "대화형 AI 아바타 API", "맞춤 아바타 생성"],
    pros: ["카메라 없이 전문 발표 영상 제작", "얼굴 입 모양이 자연스러움", "다양한 언어로 즉시 현지화"],
    cons: ["무료 플랜 워터마크·크레딧 제한", "장시간 영상은 어색해 보일 수 있음"],
    pricing: { free: "20크레딧 무료 체험", paid: "Lite $5.9/월, Pro $49/월, Advanced $149/월" },
    useCases: ["교육 강의 영상 제작", "기업 안내 영상", "SNS 마케팅 영상", "다국어 제품 설명", "역사 인물 교육 콘텐츠"],
  },
  {
    id: "gamma",
    name: "Gamma",
    description: "AI로 프레젠테이션, 문서, 웹페이지를 자동 생성하는 도구. 아이디어만 입력하면 슬라이드를 만들어줍니다.",
    longDescription: "Gamma는 주제나 아이디어를 입력하면 AI가 자동으로 전체 프레젠테이션을 생성해주는 서비스입니다. 파워포인트나 키노트 없이 브라우저에서 바로 작성·발표·공유할 수 있으며, 생성된 콘텐츠를 쉽게 편집할 수 있습니다. 프레젠테이션뿐 아니라 문서, 웹페이지 형식도 지원해 다양한 용도로 활용됩니다. 세련된 디자인 템플릿을 자동으로 적용하며, PDF·PowerPoint 내보내기도 지원합니다. 링크 하나로 공유할 수 있어 협업과 배포가 편리합니다.",
    url: "https://gamma.app",
    category: "other",
    tags: ["프레젠테이션", "슬라이드", "문서 생성", "디자인"],
    free: true,
    popular: true,
    features: ["텍스트→프레젠테이션 자동 생성", "문서·웹페이지 형식 지원", "세련된 디자인 자동 적용", "PDF·PowerPoint 내보내기", "링크로 즉시 공유"],
    pros: ["슬라이드 제작 시간 90% 단축", "디자인 감각 없어도 전문가 수준", "무료 플랜도 충분히 활용 가능"],
    cons: ["고도로 커스터마이징된 디자인에는 한계", "PowerPoint 고급 기능 대체 불가"],
    pricing: { free: "400크레딧(약 10개 덱) 무료", paid: "Plus $10/월 — 무제한 AI 생성, 커스텀 폰트" },
    useCases: ["사업 계획서 프레젠테이션", "수업·강의 자료 제작", "제품 피치덱", "보고서 시각화", "포트폴리오 웹페이지"],
  },
  {
    id: "otter-ai",
    name: "Otter.ai",
    description: "회의와 인터뷰를 실시간으로 전사하는 AI. Zoom, Meet와 통합되어 자동으로 회의록을 작성합니다.",
    longDescription: "Otter.ai는 회의, 인터뷰, 강의를 실시간으로 전사하고 자동으로 회의록을 작성해주는 AI 서비스입니다. Zoom, Google Meet, Microsoft Teams와 연동해 화상회의에 자동으로 참가해 전사·요약을 진행합니다. 발언자를 자동으로 구분해 누가 어떤 말을 했는지 명확하게 기록하며, AI가 핵심 액션 아이템과 요약을 자동으로 추출합니다. 영어를 주로 지원하지만 한국어도 일부 지원하며, 팀 공유·편집·검색 기능으로 협업에도 유용합니다.",
    url: "https://otter.ai",
    category: "other",
    tags: ["회의 전사", "실시간", "Zoom 통합", "회의록"],
    free: true,
    features: ["실시간 회의 전사", "Zoom·Meet·Teams 자동 참가", "발언자 자동 구분", "AI 요약·액션 아이템 추출", "팀 공유 및 검색"],
    pros: ["회의록 작성 시간 완전 절약", "화상회의 플랫폼 완벽 통합", "무료 플랜도 기본 기능 충분"],
    cons: ["한국어 전사 정확도 영어보다 낮음", "무료 플랜 월 600분 제한"],
    pricing: { free: "월 600분 전사 무료", paid: "Pro $10/월 — 월 1200분, 고급 기능, Business $20/월" },
    useCases: ["비즈니스 회의 자동 기록", "인터뷰 전사", "강의·세미나 필기 보조", "팟캐스트 스크립트 생성", "영업 통화 기록"],
  },
  {
    id: "khroma",
    name: "Khroma",
    description: "AI가 개인 취향을 학습해 무한한 색상 팔레트를 생성하는 디자이너용 도구입니다.",
    longDescription: "Khroma는 디자이너의 색상 취향을 AI가 학습해 개인화된 무한 색상 팔레트를 생성하는 독특한 도구입니다. 처음 사용 시 좋아하는 색상 50개를 선택하면, AI가 해당 취향을 분석해 앞으로 좋아할 만한 색상 조합을 끊임없이 추천합니다. 타이포그래피, 그라디언트, 팔레트, 이미지 형태로 색상 조합을 미리 볼 수 있어 실제 디자인에 어떻게 적용될지 확인하기 쉽습니다. 완전 무료로 제공되며, 브랜드 색상 체계 구축이나 UI 컬러 팔레트 선정에 유용합니다.",
    url: "https://www.khroma.co",
    category: "other",
    tags: ["색상 팔레트", "디자인", "UI/UX", "브랜딩"],
    free: true,
    features: ["개인 취향 학습 AI 팔레트", "타이포그래피·그라디언트 미리보기", "무한 색상 조합 생성", "색상 저장 및 컬렉션", "완전 무료"],
    pros: ["개인 취향에 맞춘 색상 추천", "완전 무료", "다양한 형태로 미리보기"],
    cons: ["색상 선택 외 다른 기능 없음", "단순한 도구"],
    pricing: { free: "완전 무료" },
    useCases: ["브랜드 컬러 팔레트 구축", "UI/UX 색상 체계 선정", "웹사이트 디자인 배색", "포스터·인쇄물 색상 기획", "개인 디자인 스타일 개발"],
  },
];
